package com.carddemo.authorization.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * One authorization reply awaiting publication, held in the transactional outbox.
 *
 * <p>This table has no counterpart in the baseline, and its absence there is precisely why it exists
 * here. The baseline consumer publishes its reply BEFORE it persists or commits the decision:
 * {@code app/app-authorization-ims-db2-mq/cbl/COPAUA0C.cbl} performs {@code 7100-SEND-RESPONSE} at line
 * 461, reaching the no-syncpoint put at lines 753 to 758; performs {@code 8000-WRITE-AUTH-TO-DB} only
 * afterwards at line 464; and reaches its syncpoint at line 335 later still, because the whole paragraph
 * is performed at line 330. The put, the write and the commit are three separate units of work in that
 * order, so a failure after the put leaves an acquirer holding an answer that no committed row accounts
 * for -- and the request behind it was destroyed on read by the no-syncpoint get at line 389, so it
 * cannot be presented again to re-derive the decision. Writing the reply into this table inside the SAME
 * transaction as the decision, and publishing it afterwards, closes that window from the other side: the
 * row and the decision commit together or neither commits, no answer can precede the row that justifies
 * it, and the publisher can retry publication as often as it needs to without re-deciding anything.</p>
 *
 * <p>Trade-offs: the alternative was to keep publishing first and commit second, as the baseline does,
 * which trades a duplicate reply for an unjustified one. That is not obviously worse in isolation -- the
 * reply queue is a FIFO queue with a deduplication identifier, so a duplicate would be suppressed -- but
 * it makes the acquirer's answer arrive before the row that justifies it exists, so a subsequent inquiry
 * against a just-answered authorization can legitimately find nothing. The outbox has neither failure
 * mode and costs one extra row write per authorization.</p>
 *
 * <p>Assumptions: publication order is preserved by the identity column, which is monotonic, so the
 * publisher can drain in insertion order and the FIFO queue receives per-card messages in the order
 * the decisions were made. Ordering by the creation timestamp instead would be ambiguous for two rows
 * written inside the same microsecond, which two authorizations on the same card can be.</p>
 *
 * <p>Assumptions: the table name is UNQUALIFIED and resolves through the pinned connection
 * {@code search_path}, for the reason recorded on {@link PendingAuthSummary}.</p>
 */
@Entity
@Table(name = "auth_reply_outbox")
public class AuthReplyOutbox {

    /**
     * The default content type of a reply payload.
     *
     * <p>Assumptions: the baseline declares its message payload as a string format, so the field order
     * and the delimiter ARE the interface and the payload is comma-separated text rather than a
     * structured document. The value is carried on the message as an attribute so a consumer can tell a
     * migrated reply from the additive structured envelope offered alongside it.</p>
     */
    public static final String CONTENT_TYPE_CSV = "text/csv";

    /**
     * The surrogate publication-order key.
     *
     * <p>Assumptions: generated by the database rather than by the application, because the ordering
     * guarantee this column carries has to hold across every instance of the publisher, and only the
     * database sees all of them.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "outbox_id", nullable = false, updatable = false)
    private Long outboxId;

    /**
     * Where the reply must be sent, taken from the request message rather than from configuration.
     *
     * <p>Assumptions: the reply destination is a property of the REQUEST, exactly as the message
     * descriptor's reply-to queue field was in the baseline. Storing it on the row means a reply is
     * still deliverable after a restart that changed nothing about the running configuration, and it
     * means two acquirers with two reply queues can be served by one consumer.</p>
     */
    @Column(name = "reply_to_queue_url", nullable = false, length = 1024)
    private String replyQueueUrl;

    /**
     * The correlation identifier to echo back to the requester.
     */
    @Column(name = "correlation_id", length = 64)
    private String correlationId;

    /**
     * The ordering group the reply belongs to: the sixteen-character card number the reply answers for.
     *
     * <p>Assumptions: grouping by card preserves per-card ordering while leaving different cards free
     * to be delivered in parallel, which is what the queue's group semantics provide. A single constant
     * group would serialise every reply in the system behind one another; a per-message group would
     * preserve no ordering at all.</p>
     *
     * <p>Refactoring Rationale: the value stored here is the CARD NUMBER, and it was a keyed,
     * purpose-scoped token derived from it. The change is an alignment rather than a preference: sections
     * 0.4.1.8 and 0.7.6 of the technical specification freeze the reply queue's {@code MessageGroupId} as
     * {@code card_num}, and that specification is the agreed source of truth. The derivation preserved the
     * grouping semantic -- equal for equal cards -- but it changed the identity a queue observer, a
     * cross-account consumer or a second publisher built from the same specification would compute, so
     * two producers written to the frozen contract and to the derivation would place one card's messages
     * in two different groups and lose the ordering guarantee entirely. The column was renamed from
     * {@code order_group_token} by {@code V3__authorization_outbox_fifo_identities.sql} so that its name
     * describes what it holds.</p>
     *
     * <p>Trade-offs: the consequence is stated rather than left for a reader to discover, because it is
     * real. A group identifier is message METADATA: server-side encryption covers a message body and not
     * its metadata, so this value appears in queue telemetry, in send traces and to anything permitted to
     * observe the queue. What bounds that exposure is the deployment rather than this column -- the reply
     * queues are encrypted with a customer-managed key, reachable only through an interface endpoint
     * inside the private network, and readable only by the task roles the infrastructure grants -- and it
     * is the specification's own judgement that the frozen identity is worth that exposure. Anyone
     * revisiting the judgement has to revisit the specification, not this field.</p>
     *
     * <p>Assumptions: the declared width stays 128 although the value occupies sixteen characters. The
     * width is not a contract on the value, nothing reads this column as fixed width, and narrowing it
     * would rewrite the table to remove headroom that a widened grouping key would need.</p>
     */
    @Column(name = "order_group_id", nullable = false, length = 128)
    private String orderGroupId;

    /**
     * The deduplication identity: the acquirer's transaction identifier the reply answers.
     *
     * <p>Assumptions: identifying the authorization rather than hashing the payload makes duplicate
     * suppression independent of the bytes, so a re-published reply whose rendering changed is still
     * recognised as the same reply. A content hash would treat it as a new message and the acquirer would
     * receive two answers to one request.</p>
     *
     * <p>Refactoring Rationale: this stores the transaction identifier itself, where it stored a keyed
     * token over the card-and-transaction pair. The reason is the one recorded on the field above: the
     * technical specification freezes {@code MessageDeduplicationId} as {@code transaction_id}, and two
     * publishers -- one following the specification and one following the derivation -- would compute
     * different identities for one authorization, so a duplicate would not be suppressed at all. The
     * column was renamed from {@code deduplication_token} by the same migration.</p>
     */
    @Column(name = "deduplication_id", nullable = false, length = 128)
    private String deduplicationId;

    /**
     * The encoded reply body, in the wire format named by {@link #getContentType()}.
     */
    @Column(name = "payload", nullable = false)
    private String payload;

    /**
     * The wire format of {@link #getPayload()}.
     */
    @Column(name = "content_type", nullable = false, length = 64)
    private String contentType;

    /**
     * When the reply stops being worth sending, in coordinated universal time.
     *
     * <p>Assumptions: the baseline sets a five-second expiry on its reply message and the target queue
     * service has no per-message time to live, so the expiry travels as data instead -- on this row and
     * on the published message -- and the consumer at the far end honours it. That resolution is
     * recorded in {@code docs/adr/ADR-004-messaging.md}; without it, a reply delayed past its usefulness
     * would be delivered as though it were fresh.</p>
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    /**
     * When the row was written, in coordinated universal time.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * When the reply was successfully published, or {@code null} while it is still pending.
     *
     * <p>Assumptions: publication is recorded by setting this member rather than by deleting the row,
     * so a published reply remains auditable and a partial index over the null values keeps the
     * publisher's claim query reading only the pending rows.</p>
     *
     * <p>⚠️ Assumptions: this member is set ONLY by an accepted send. Nothing else may populate it.
     * Refactoring Rationale: a {@code retire} transition set it for a reply whose deadline had passed
     * WITHOUT sending anything, and the effect was a row asserting a publication that never happened --
     * which the retention sweep, whose predicate is this same column, then deleted. Both the transition
     * and its caller are withdrawn; a reply that cannot be delivered within its attempt budget reaches
     * {@link #abandon(java.time.LocalDateTime, String)} instead, which leaves this member null and is
     * excluded from that sweep for exactly this reason.</p>
     */
    @Column(name = "published_at")
    private LocalDateTime publishedAt;

    /**
     * How many transport send attempts have been made for this reply.
     *
     * <p>Refactoring Rationale: this counted three unrelated events and now counts one. A claim by
     * {@code OutboxRepository} advanced it, {@code OutboxPublisher} advanced it again when a send failed,
     * and it advanced a third time when an expired row was retired without being sent at all -- so its
     * value was neither a claim count nor a send count and answered no operational question. The claim
     * transition moved to {@link #claimVersion}, and the third event no longer exists at all: a row whose
     * deadline has passed is now SENT with the lateness reported rather than retired unsent, so one
     * increment corresponds to one transport call.</p>
     *
     * <p>Assumptions: the type is {@code Integer} and the column INTEGER, widened from a small integer by
     * {@code V2__authorization_outbox_claim_version.sql}. The old width was reachable: a permanently
     * failing row advanced the shared counter twice per drain pass, which at the default one-second poll
     * interval exhausted a small integer in under five hours, and the engine reports an integer overflow
     * as an error rather than wrapping -- so the drain transaction would abort and every reply behind that
     * row would stop being published.</p>
     */
    @Column(name = "attempts", nullable = false)
    private Integer attempts;

    /**
     * When this reply next becomes eligible for a publication attempt.
     *
     * <p>Assumptions: this single column carries BOTH the claim lease and the retry backoff, because
     * the two are the same statement of fact -- the instant before which no publisher should touch
     * this row. A claim moves it forward by the lease, a failed send moves it forward by the backoff,
     * and the ready predicate admits only rows whose instant has arrived. Refactoring Rationale: an
     * earlier revision had no such column, so a claim was an uncommitted row write held for the whole
     * publication pass, which forced the network send to occur inside the database transaction; and
     * the ready set was the globally oldest pending rows, so permanently failing heads were reselected
     * on every poll and starved every healthy group behind them.</p>
     *
     * <p>Trade-offs: the column is NOT NULL with a past default so that a newly inserted reply is
     * immediately eligible. A nullable column meaning "eligible now" was rejected because every
     * predicate would then need to spell the null case, and one that forgot it would silently exclude
     * every fresh row -- the failure mode being defended against.</p>
     */
    @Column(name = "next_attempt_at", nullable = false)
    private LocalDateTime nextAttemptAt;

    /**
     * When this reply was abandoned, if it was.
     *
     * <p>Assumptions: this is the terminal state and it is deliberately SEPARATE from the publication
     * instant. A published row was answered and an abandoned row never will be, so recording both in
     * one column would let a reply that was never sent read as delivered in any audit that joins on
     * publication.</p>
     */
    @Column(name = "abandoned_at")
    private LocalDateTime abandonedAt;

    /**
     * Why the last publication attempt failed, truncated to the column width.
     */
    @Column(name = "last_error", length = 256)
    private String lastError;

    /**
     * The width of {@link #lastError}, used to truncate a recorded reason rather than fail the write.
     *
     * <p>Assumptions: a diagnostic that does not fit must not be the reason a transaction rolls back.
     * Truncating keeps the row writable; letting the database reject it would turn a reporting detail
     * into a lost reply.</p>
     */
    private static final int LAST_ERROR_MAX_LENGTH = 256;

    /**
     * Creates an empty instance for the persistence provider to populate.
     *
     * <p>Assumptions: the specification requires a no-argument constructor. It is protected because an
     * outbox row with no destination and no payload is meaningless to any caller outside this
     * hierarchy.</p>
     */
    protected AuthReplyOutbox() {
        // Assumptions: empty by design; the provider assigns every mapped field after construction.
    }

    /**
     * Creates a pending outbox row.
     *
     * @param replyQueueUrl where the reply must be sent, taken from the request; must not be
     *     {@code null}
     * @param correlationId the correlation identifier to echo; may be {@code null}
     * @param orderGroupId the ordering group, which is the card number itself as the technical
     *     specification freezes it; must not be {@code null}
     * @param deduplicationId the deduplication identity, which is the acquirer's transaction
     *     identifier as the technical specification freezes it; must not be {@code null}
     * @param payload the encoded reply body; must not be {@code null}
     * @param expiresAt when the reply stops being worth sending, in coordinated universal time; may be
     *     {@code null} to mean it never expires
     * @param createdAt when this row was written, in coordinated universal time; must not be
     *     {@code null}
     */
    public AuthReplyOutbox(String replyQueueUrl, String correlationId, String orderGroupId,
            String deduplicationId, String payload, LocalDateTime expiresAt,
            LocalDateTime createdAt) {
        this.replyQueueUrl = replyQueueUrl;
        this.correlationId = correlationId;
        this.orderGroupId = orderGroupId;
        this.deduplicationId = deduplicationId;
        this.payload = payload;
        this.contentType = CONTENT_TYPE_CSV;
        this.expiresAt = expiresAt;
        this.createdAt = createdAt;
        this.attempts = 0;
        // WHY : Assumptions: a fresh reply is eligible AT its creation instant rather than at some
        // offset from it. The row is written inside the decision's transaction and the publisher runs
        // on its own poll, so any positive offset here would be a delay added to every reply for no
        // stated reason; the column is set rather than left to its database default because an
        // in-memory instance is read by the publisher's own tests before it is ever persisted.
        this.nextAttemptAt = createdAt;
    }

    /**
     * Returns the surrogate publication-order key.
     *
     * @return the outbox identifier, never {@code null} on a persisted instance
     */
    public Long getOutboxId() {
        return this.outboxId;
    }

    /**
     * Returns where the reply must be sent.
     *
     * @return the reply queue location, never {@code null} on a persisted instance
     */
    public String getReplyQueueUrl() {
        return this.replyQueueUrl;
    }

    /**
     * Returns the correlation identifier to echo back to the requester.
     *
     * @return the correlation identifier, or {@code null} when the request carried none
     */
    public String getCorrelationId() {
        return this.correlationId;
    }

    /**
     * Returns the ordering group the reply belongs to.
     *
     * @return the card number this reply answers for, which is the group identity the technical
     *     specification freezes; never {@code null} on a persisted instance
     */
    public String getOrderGroupId() {
        return this.orderGroupId;
    }

    /**
     * Returns the deduplication identity.
     *
     * @return the acquirer's transaction identifier, which is the deduplication identity the technical
     *     specification freezes; never {@code null} on a persisted instance
     */
    public String getDeduplicationId() {
        return this.deduplicationId;
    }

    /**
     * Returns the encoded reply body.
     *
     * @return the payload, never {@code null} on a persisted instance
     */
    public String getPayload() {
        return this.payload;
    }

    /**
     * Returns the wire format of the payload.
     *
     * @return the content type, never {@code null} on a persisted instance
     */
    public String getContentType() {
        return this.contentType;
    }

    /**
     * Returns when the reply stops being worth sending.
     *
     * @return the expiry instant in coordinated universal time, or {@code null} when it never expires
     */
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Returns when the row was written.
     *
     * @return the creation instant in coordinated universal time, never {@code null} on a persisted
     *     instance
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Returns when the reply was published.
     *
     * @return the publication instant in coordinated universal time, or {@code null} while pending
     */
    public LocalDateTime getPublishedAt() {
        return this.publishedAt;
    }

    /**
     * Returns how many transport send attempts have been made for this reply.
     *
     * @return the send-attempt count, never {@code null} on a persisted instance
     */
    public Integer getAttempts() {
        return this.attempts;
    }

    /**
     * Returns the instant before which no publisher should attempt this reply.
     *
     * @return the lease and backoff instant, never {@code null}
     */
    public LocalDateTime getNextAttemptAt() {
        return this.nextAttemptAt;
    }

    /**
     * Returns when this reply was abandoned.
     *
     * @return the abandonment instant, or {@code null} while the reply is still being attempted
     */
    public LocalDateTime getAbandonedAt() {
        return this.abandonedAt;
    }

    /**
     * Reports whether this reply has been abandoned and will never be attempted again.
     *
     * @return {@code true} when an abandonment instant has been recorded
     */
    public boolean isAbandoned() {
        return this.abandonedAt != null;
    }

    /**
     * Returns why the last publication attempt failed.
     *
     * @return the truncated failure reason, or {@code null} when no attempt has failed
     */
    public String getLastError() {
        return this.lastError;
    }

    /**
     * Reports whether this reply has already been published.
     *
     * @return {@code true} when a publication instant has been recorded
     */
    public boolean isPublished() {
        return this.publishedAt != null;
    }

    /**
     * Reports whether this reply has stopped being worth sending as of a stated instant.
     *
     * <p>Assumptions: a row with no expiry never goes stale, which is how a reply whose request carried
     * no expiry attribute is treated. Defaulting an absent expiry to "already expired" would silently
     * discard every reply to a requester that does not set one.</p>
     *
     * @param asOf the instant to judge staleness against, in coordinated universal time; must not be
     *     {@code null}
     * @return {@code true} when an expiry is recorded and {@code asOf} is at or after it
     */
    public boolean isExpiredAsOf(LocalDateTime asOf) {
        return this.expiresAt != null && !asOf.isBefore(this.expiresAt);
    }

    /**
     * Records that the reply was published.
     *
     * @param publishedAt the instant publication succeeded, in coordinated universal time; must not be
     *     {@code null}
     */
    public void markPublished(LocalDateTime publishedAt) {
        this.publishedAt = publishedAt;
        this.lastError = null;
    }

    /**
     * Records why an attempt failed and when the next one may be made.
     *
     * <p>Refactoring Rationale: this method DOES NOT increment the attempt counter, and the removal is
     * the point of it. The counter is advanced in exactly one place -- the claiming statement that
     * takes the row -- so every attempt is counted once whether it then succeeds, fails or is
     * abandoned. The method it replaces incremented here as well, so a failed publication was counted
     * twice: the stored number was double the attempts actually made, and because the column was
     * sixteen bits a row whose reply queue stayed unreachable reached the signed limit in half the
     * expected time and wrapped negative, at which point every attempt-bounded predicate read it as a
     * fresh row and retried it forever.</p>
     *
     * <p>Assumptions: the reason is truncated rather than rejected when it exceeds the column, because
     * losing the diagnostic entirely to a formatting concern would leave an operator with a failing row
     * and no shape of the failure. The backoff instant is a parameter rather than computed here so that
     * the policy -- how long, growing how -- stays with the publisher that owns the retry budget, and
     * this class stays a record of what happened.</p>
     *
     * @param reason why the attempt failed; may be {@code null}, and is truncated to the column width
     * @param nextAttemptAt the instant before which no publisher should attempt this reply again, in
     *     coordinated universal time; must not be {@code null}
     */
    public void recordFailure(String reason, LocalDateTime nextAttemptAt) {
        this.nextAttemptAt = nextAttemptAt;
        if (reason == null || reason.length() <= LAST_ERROR_MAX_LENGTH) {
            this.lastError = reason;
        } else {
            this.lastError = reason.substring(0, LAST_ERROR_MAX_LENGTH);
        }
    }

    /**
     * Abandons this reply permanently, leaving the reason that ended it on the row.
     *
     * <p>Assumptions: abandonment does NOT set the publication instant, so an abandoned reply can
     * never be counted as delivered. It is removed from the ready set by the terminal column alone,
     * which is why that column and the publication column are distinct.</p>
     *
     * <p>⚠️ Assumptions: this is now the ONLY terminal outcome for a reply that never reached the wire,
     * and a passed deadline no longer produces one of its own. Refactoring Rationale: a withdrawn
     * {@code retire} transition ended a stale reply by marking it published, which both asserted a
     * delivery that had not occurred and exposed the row to the retention sweep. Every undeliverable
     * reply now arrives here instead, so the two properties that make an undelivered reply investigable
     * -- a null publication instant and exclusion from the sweep -- hold for all of them rather than for
     * the subset whose queue was unreachable rather than slow.</p>
     *
     * <p>Trade-offs: the payload and the diagnostic are retained rather than cleared, so an operator
     * can see which reply was given up on and why. The accepted cost is that a row carrying a primary
     * account number in its payload persists beyond the retention sweep -- which is deliberate: this
     * is a reply the committed decision says was owed and never delivered, and removing it silently
     * would destroy the only evidence of that.</p>
     *
     * @param abandonedAt the instant the reply was given up on, in coordinated universal time; must
     *     not be {@code null}
     * @param reason why it was given up on; may be {@code null}, and is truncated to the column width
     */
    public void abandon(LocalDateTime abandonedAt, String reason) {
        this.abandonedAt = abandonedAt;
        if (reason == null || reason.length() <= LAST_ERROR_MAX_LENGTH) {
            this.lastError = reason;
        } else {
            this.lastError = reason.substring(0, LAST_ERROR_MAX_LENGTH);
        }
    }
}
