package com.carddemo.authorization.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * One authorization reply awaiting publication, held in the transactional outbox.
 *
 * <p>This table has no counterpart in the baseline, and its absence there is precisely why it exists
 * here. The baseline consumer commits its database work with a syncpoint at
 * {@code app/app-authorization-ims-db2-mq/cbl/COPAUA0C.cbl} line 335 and then publishes the reply with
 * a no-syncpoint put at line 753. Those are two separate units of work, so a failure between them
 * leaves an authorization that the data says was decided and an acquirer that never received an answer.
 * Writing the reply into this table inside the SAME transaction as the decision, and publishing it
 * afterwards, closes that window: the row and the decision commit together or neither commits, and the
 * publisher can then retry publication as often as it needs to without re-deciding anything.</p>
 *
 * <p>Trade-offs: the alternative was to publish first and commit second, which trades a lost reply for
 * a duplicate one. That is not obviously worse in isolation -- the reply queue is a FIFO queue with a
 * deduplication identifier, so a duplicate would be suppressed -- but it makes the acquirer's answer
 * arrive before the row that justifies it exists, so a subsequent inquiry against a just-answered
 * authorization can legitimately find nothing. The outbox has neither failure mode and costs one extra
 * row write per authorization.</p>
 *
 * <p>Assumptions: publication order is preserved by the identity column, which is monotonic, so the
 * publisher can drain in insertion order and the FIFO queue receives per-card messages in the order
 * the decisions were made. Ordering by the creation timestamp instead would be ambiguous for two rows
 * written inside the same microsecond, which two authorizations on the same card can be.</p>
 *
 * <p>Assumptions: the table name is UNQUALIFIED and resolves through the pinned connection
 * {@code search_path}, for the reason recorded on {@link PendingAuthSummary}.</p>
 */
@Entity
@Table(name = "auth_reply_outbox")
public class AuthReplyOutbox {

    /**
     * The default content type of a reply payload.
     *
     * <p>Assumptions: the baseline declares its message payload as a string format, so the field order
     * and the delimiter ARE the interface and the payload is comma-separated text rather than a
     * structured document. The value is carried on the message as an attribute so a consumer can tell a
     * migrated reply from the additive structured envelope offered alongside it.</p>
     */
    public static final String CONTENT_TYPE_CSV = "text/csv";

    /**
     * The surrogate publication-order key.
     *
     * <p>Assumptions: generated by the database rather than by the application, because the ordering
     * guarantee this column carries has to hold across every instance of the publisher, and only the
     * database sees all of them.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "outbox_id", nullable = false, updatable = false)
    private Long outboxId;

    /**
     * Where the reply must be sent, taken from the request message rather than from configuration.
     *
     * <p>Assumptions: the reply destination is a property of the REQUEST, exactly as the message
     * descriptor's reply-to queue field was in the baseline. Storing it on the row means a reply is
     * still deliverable after a restart that changed nothing about the running configuration, and it
     * means two acquirers with two reply queues can be served by one consumer.</p>
     */
    @Column(name = "reply_queue_url", nullable = false, length = 1024)
    private String replyQueueUrl;

    /**
     * The correlation identifier to echo back to the requester.
     */
    @Column(name = "correlation_id", length = 64)
    private String correlationId;

    /**
     * The ordering group the reply belongs to, which is the card number.
     *
     * <p>Assumptions: grouping by card preserves per-card ordering while leaving different cards free
     * to be delivered in parallel, which is what the queue's group semantics provide. A single constant
     * group would serialise every reply in the system behind one another; a per-message group would
     * preserve no ordering at all.</p>
     */
    @Column(name = "message_group_id", nullable = false, length = 128)
    private String messageGroupId;

    /**
     * The deduplication identifier, which is the acquirer's transaction identifier.
     *
     * <p>Assumptions: using the transaction identifier rather than a content hash makes duplicate
     * suppression independent of the payload, so a re-decided authorization that produces a
     * byte-different reply is still recognised as the same reply. A content hash would treat it as a new
     * message and the acquirer would receive two answers to one request.</p>
     */
    @Column(name = "deduplication_id", nullable = false, length = 128)
    private String deduplicationId;

    /**
     * The encoded reply body, in the wire format named by {@link #getContentType()}.
     */
    @Column(name = "payload", nullable = false)
    private String payload;

    /**
     * The wire format of {@link #getPayload()}.
     */
    @Column(name = "content_type", nullable = false, length = 64)
    private String contentType;

    /**
     * When the reply stops being worth sending, in coordinated universal time.
     *
     * <p>Assumptions: the baseline sets a five-second expiry on its reply message and the target queue
     * service has no per-message time to live, so the expiry travels as data instead -- on this row and
     * on the published message -- and the consumer at the far end honours it. That resolution is
     * recorded in {@code docs/adr/ADR-004-messaging.md}; without it, a reply delayed past its usefulness
     * would be delivered as though it were fresh.</p>
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    /**
     * When the row was written, in coordinated universal time.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * When the reply was successfully published, or {@code null} while it is still pending.
     *
     * <p>Assumptions: publication is recorded by setting this member rather than by deleting the row,
     * so a published reply remains auditable and a partial index over the null values keeps the
     * publisher's claim query reading only the pending rows.</p>
     */
    @Column(name = "published_at")
    private LocalDateTime publishedAt;

    /**
     * How many publication attempts have been made.
     */
    @Column(name = "attempts", nullable = false)
    private Short attempts;

    /**
     * Why the last publication attempt failed, truncated to the column width.
     */
    @Column(name = "last_error", length = 256)
    private String lastError;

    /**
     * The width of {@link #lastError}, used to truncate a recorded reason rather than fail the write.
     *
     * <p>Assumptions: a diagnostic that does not fit must not be the reason a transaction rolls back.
     * Truncating keeps the row writable; letting the database reject it would turn a reporting detail
     * into a lost reply.</p>
     */
    private static final int LAST_ERROR_MAX_LENGTH = 256;

    /**
     * Creates an empty instance for the persistence provider to populate.
     *
     * <p>Assumptions: the specification requires a no-argument constructor. It is protected because an
     * outbox row with no destination and no payload is meaningless to any caller outside this
     * hierarchy.</p>
     */
    protected AuthReplyOutbox() {
        // Assumptions: empty by design; the provider assigns every mapped field after construction.
    }

    /**
     * Creates a pending outbox row.
     *
     * @param replyQueueUrl where the reply must be sent, taken from the request; must not be
     *     {@code null}
     * @param correlationId the correlation identifier to echo; may be {@code null}
     * @param messageGroupId the ordering group, which is the card number; must not be {@code null}
     * @param deduplicationId the deduplication identifier, which is the transaction identifier; must
     *     not be {@code null}
     * @param payload the encoded reply body; must not be {@code null}
     * @param expiresAt when the reply stops being worth sending, in coordinated universal time; may be
     *     {@code null} to mean it never expires
     * @param createdAt when this row was written, in coordinated universal time; must not be
     *     {@code null}
     */
    public AuthReplyOutbox(String replyQueueUrl, String correlationId, String messageGroupId,
            String deduplicationId, String payload, LocalDateTime expiresAt,
            LocalDateTime createdAt) {
        this.replyQueueUrl = replyQueueUrl;
        this.correlationId = correlationId;
        this.messageGroupId = messageGroupId;
        this.deduplicationId = deduplicationId;
        this.payload = payload;
        this.contentType = CONTENT_TYPE_CSV;
        this.expiresAt = expiresAt;
        this.createdAt = createdAt;
        this.attempts = 0;
    }

    /**
     * Returns the surrogate publication-order key.
     *
     * @return the outbox identifier, never {@code null} on a persisted instance
     */
    public Long getOutboxId() {
        return this.outboxId;
    }

    /**
     * Returns where the reply must be sent.
     *
     * @return the reply queue location, never {@code null} on a persisted instance
     */
    public String getReplyQueueUrl() {
        return this.replyQueueUrl;
    }

    /**
     * Returns the correlation identifier to echo back to the requester.
     *
     * @return the correlation identifier, or {@code null} when the request carried none
     */
    public String getCorrelationId() {
        return this.correlationId;
    }

    /**
     * Returns the ordering group the reply belongs to.
     *
     * @return the message group identifier, never {@code null} on a persisted instance
     */
    public String getMessageGroupId() {
        return this.messageGroupId;
    }

    /**
     * Returns the deduplication identifier.
     *
     * @return the deduplication identifier, never {@code null} on a persisted instance
     */
    public String getDeduplicationId() {
        return this.deduplicationId;
    }

    /**
     * Returns the encoded reply body.
     *
     * @return the payload, never {@code null} on a persisted instance
     */
    public String getPayload() {
        return this.payload;
    }

    /**
     * Returns the wire format of the payload.
     *
     * @return the content type, never {@code null} on a persisted instance
     */
    public String getContentType() {
        return this.contentType;
    }

    /**
     * Returns when the reply stops being worth sending.
     *
     * @return the expiry instant in coordinated universal time, or {@code null} when it never expires
     */
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Returns when the row was written.
     *
     * @return the creation instant in coordinated universal time, never {@code null} on a persisted
     *     instance
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Returns when the reply was published.
     *
     * @return the publication instant in coordinated universal time, or {@code null} while pending
     */
    public LocalDateTime getPublishedAt() {
        return this.publishedAt;
    }

    /**
     * Returns how many publication attempts have been made.
     *
     * @return the attempt count, never {@code null} on a persisted instance
     */
    public Short getAttempts() {
        return this.attempts;
    }

    /**
     * Returns why the last publication attempt failed.
     *
     * @return the truncated failure reason, or {@code null} when no attempt has failed
     */
    public String getLastError() {
        return this.lastError;
    }

    /**
     * Reports whether this reply has already been published.
     *
     * @return {@code true} when a publication instant has been recorded
     */
    public boolean isPublished() {
        return this.publishedAt != null;
    }

    /**
     * Reports whether this reply has stopped being worth sending as of a stated instant.
     *
     * <p>Assumptions: a row with no expiry never goes stale, which is how a reply whose request carried
     * no expiry attribute is treated. Defaulting an absent expiry to "already expired" would silently
     * discard every reply to a requester that does not set one.</p>
     *
     * @param asOf the instant to judge staleness against, in coordinated universal time; must not be
     *     {@code null}
     * @return {@code true} when an expiry is recorded and {@code asOf} is at or after it
     */
    public boolean isExpiredAsOf(LocalDateTime asOf) {
        return this.expiresAt != null && !asOf.isBefore(this.expiresAt);
    }

    /**
     * Records that the reply was published.
     *
     * @param publishedAt the instant publication succeeded, in coordinated universal time; must not be
     *     {@code null}
     */
    public void markPublished(LocalDateTime publishedAt) {
        this.publishedAt = publishedAt;
        this.lastError = null;
    }

    /**
     * Records a failed publication attempt and its reason.
     *
     * <p>Assumptions: the attempt count and the reason are written together and the count is
     * incremented even when the reason does not fit, because the count is what a retry policy reads and
     * losing it to a formatting concern would make a permanently-failing row retry forever.</p>
     *
     * @param reason why the attempt failed; may be {@code null}, and is truncated to the column width
     */
    public void recordFailedAttempt(String reason) {
        this.attempts = (short) (this.attempts + 1);
        if (reason == null || reason.length() <= LAST_ERROR_MAX_LENGTH) {
            this.lastError = reason;
        } else {
            this.lastError = reason.substring(0, LAST_ERROR_MAX_LENGTH);
        }
    }
}
