package com.carddemo.authorization.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.carddemo.authorization.domain.PendingAuthDetail;
import com.carddemo.authorization.domain.PendingAuthDetailKey;
import com.carddemo.authorization.domain.PendingAuthSummary;
import com.carddemo.authorization.mapper.PendingAuthDetailMapper;
import com.carddemo.authorization.mapper.PendingAuthSummaryMapper;
import com.carddemo.authorization.repository.PendingAuthDetailRepository;
import com.carddemo.authorization.repository.PendingAuthSummaryRepository;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Limit;

/**
 * Drives {@link LoadService} and {@link UnloadService} against the committed extract fixtures.
 *
 * <p><b>Purpose.</b> The two services are the migrated forms of
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBLOD.CBL},
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBUNL.CBL} and
 * {@code app/app-authorization-ims-db2-mq/cbl/DBUNLDGS.CBL}. Between them they define a file format, so
 * the property worth asserting is that the format survives a full circuit: bytes in through the loader,
 * rows out through the unloader, and the same bytes back. A test that only checked the loader called save
 * would pass for a loader that decoded every field into the wrong column.
 *
 * <p>Assumptions: the fixtures are the oracle rather than anything this class computes. The four files
 * were generated by the Python ETL codec in
 * {@code data-migration/src/carddemo_migration/copybook/packed.py}, an independently written transcription
 * of the same copybooks, so a byte-identical circuit through the Java codec is a cross-language agreement
 * rather than the Java codec agreeing with itself.
 *
 * <p>Assumptions: the repositories are STATEFUL doubles rather than fixed stubs, and that is a
 * requirement rather than a convenience. Within one load the loader inserts a summary and then, for each
 * child, asks whether that child's parent exists -- so a double answering a fixed value for existence
 * would either report every child orphaned or every summary already present, and neither is the situation
 * under test. A real repository answers correctly here because an existence query flushes the pending
 * inserts of its own transaction before it runs; the doubles below reproduce that by remembering what was
 * saved.
 *
 * <p>Alternatives Considered: a container-backed test with a real database. Rejected as the primary form
 * because both services are pure translations between a byte stream and repository calls -- neither
 * declares a query and neither writes SQL -- so a container would add startup cost without asserting
 * anything these doubles cannot. The committed repository integration test covers the persistence side.
 *
 * <p>A test class accepts no parameter, yields no value and raises nothing, so this block carries no
 * parameter, return or exception at-clause.
 */
@ExtendWith(MockitoExtension.class)
class AuthorizationExtractRoundTripTest {

    /** The class-path directory the committed fixtures live in. */
    private static final String ROOT = "/fixtures/";

    /** The hierarchical unload's summary file: two hundred-byte roots, highest account first. */
    private static final String PREFIXED_SUMMARY = "unload-prefixed-summary-100.bin";

    /** The hierarchical unload's child file: four two-hundred-and-six-byte prefixed records. */
    private static final String PREFIXED_DETAIL = "unload-prefixed-detail-206.bin";

    /** The sequential unload's summary file: the same two roots, lowest account first. */
    private static final String SEQUENTIAL_SUMMARY = "unload-gsam-summary-100.bin";

    /** The sequential unload's child file: four bare two-hundred-byte segments. */
    private static final String SEQUENTIAL_DETAIL = "unload-gsam-detail-200.bin";

    /** The lower of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_ONE = 10_000_000_001L;

    /** The higher of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_TWO = 10_000_000_002L;

    /** The number of roots the summary fixtures hold. */
    private static final int ROOT_COUNT = 2;

    /** The number of children the detail fixtures hold. */
    private static final int CHILD_COUNT = 4;

    /**
     * The width of the raw complement key IMS sequences the child twins on.
     *
     * <p>Assumptions: eight, from {@code FIELD NAME=(PAUT9CTS,SEQ,U),START=1,BYTES=8,TYPE=C} at
     * {@code app/app-authorization-ims-db2-mq/ims/DBPAUTP0.dbd} L37 -- the packed date and packed time
     * complements together, at the head of every segment.
     */
    private static final int RAW_KEY_WIDTH = 8;

    /** The summary repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthSummaryRepository summaries;

    /** The authorization repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthDetailRepository details;

    /** The summaries the doubles have accepted, in save order. */
    private final List<PendingAuthSummary> storedRoots = new ArrayList<>();

    /** The authorizations the doubles have accepted, in save order. */
    private final List<PendingAuthDetail> storedChildren = new ArrayList<>();

    /**
     * Makes the summary double remember what it is given and answer existence from that.
     */
    private void givenSummariesRemember() {
        when(this.summaries.save(any())).thenAnswer(invocation -> {
            PendingAuthSummary saved = invocation.getArgument(0);
            this.storedRoots.add(saved);
            return saved;
        });
        when(this.summaries.existsById(any())).thenAnswer(invocation -> {
            Long accountId = invocation.getArgument(0);
            return this.storedRoots.stream()
                    .anyMatch(root -> accountId.equals(root.getAccountId()));
        });
    }

    /**
     * Makes the authorization double remember what it is given and answer existence from that.
     */
    private void givenDetailsRemember() {
        when(this.details.save(any())).thenAnswer(invocation -> {
            PendingAuthDetail saved = invocation.getArgument(0);
            this.storedChildren.add(saved);
            return saved;
        });
        when(this.details.existsById(any())).thenAnswer(invocation -> {
            PendingAuthDetailKey key = invocation.getArgument(0);
            return this.storedChildren.stream().anyMatch(child -> key.equals(child.getId()));
        });
    }

    /**
     * Loads both prefixed fixtures through the loader and returns what it reported.
     *
     * @return the loader's own counts
     */
    private LoadService.LoadOutcome loadBothFixtures() {
        return new LoadService(this.summaries, this.details)
                .load(open(PREFIXED_SUMMARY), open(PREFIXED_DETAIL));
    }

    /**
     * The loader loads both roots and all four children, and attributes each child to its own parent.
     *
     * <p>Assumptions: the child prefixes ALTERNATE between the two accounts in this fixture rather than
     * being grouped, which is what makes the attribution assertion meaningful. A loader that carried the
     * previous record's account forward would produce a plausible result on a grouped file and the wrong
     * one here.</p>
     *
     * <p>Assumptions: the roots are asserted to load in FILE order, which this fixture deliberately writes
     * highest account first. A loader that sorted its input would make this fixture and its ascending
     * sibling indistinguishable, which is the reason the pair exists.</p>
     */
    @Test
    @DisplayName("the loader loads two roots and four children, attributing each child to its own parent")
    void theLoaderLoadsBothFilesAndAttributesEveryChild() {
        givenSummariesRemember();
        givenDetailsRemember();

        LoadService.LoadOutcome outcome = loadBothFixtures();

        assertThat(outcome.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.inserted()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.alreadyPresent()).isZero();
        assertThat(outcome.orphaned()).isZero();

        assertThat(this.storedRoots)
                .extracting(PendingAuthSummary::getAccountId)
                .containsExactly(ACCOUNT_TWO, ACCOUNT_ONE);
        assertThat(this.storedChildren)
                .extracting(child -> child.getId().getAccountId())
                .as("each child's account comes from its own six-byte packed prefix")
                .containsExactly(ACCOUNT_ONE, ACCOUNT_TWO, ACCOUNT_ONE, ACCOUNT_TWO);
    }

    /**
     * Re-running a completed load inserts nothing and reports every record as already present.
     *
     * <p>Assumptions: this is the reference program's treatment of the duplicate-segment status -- its L256
     * to L258 and L329 to L331 report the duplicate and continue -- and it is what makes a partially
     * completed load safely re-runnable. Asserting that the stored state did not GROW is the important
     * half: an upsert would satisfy a count assertion while silently replacing a row an operator had since
     * corrected online.</p>
     */
    @Test
    @DisplayName("re-running a completed load inserts nothing and counts every record already present")
    void aRerunSkipsEveryRecordRatherThanOverwritingIt() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();

        LoadService.LoadOutcome rerun = loadBothFixtures();

        assertThat(rerun.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(rerun.inserted()).isZero();
        assertThat(rerun.alreadyPresent()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(rerun.orphaned()).isZero();
        assertThat(this.storedRoots).hasSize(ROOT_COUNT);
        assertThat(this.storedChildren).hasSize(CHILD_COUNT);
    }

    /**
     * A child whose parent is absent is skipped and counted separately, not refused.
     *
     * <p>Assumptions: the reference program discards such a child silently -- its insert sits inside the
     * branch a successful parent position opens at L305, and a failed position falls past both the insert
     * and the abend test nested within that branch -- so refusing it here would abort a load the reference
     * completes. The skip is counted and logged, which the reference does not do, so an operator can see
     * that the two extract files disagree.</p>
     *
     * <p>Assumptions: the orphan count is asserted DISTINCT from the already-present count, because summing
     * them would hide a real disagreement between the two files inside the ordinary outcome of a
     * re-run.</p>
     */
    @Test
    @DisplayName("a child whose parent summary is absent is skipped as orphaned, not refused")
    void anOrphanedChildIsSkippedAndCountedSeparately() {
        when(this.summaries.existsById(any())).thenReturn(false);

        LoadService.LoadOutcome outcome = new LoadService(this.summaries, this.details)
                .loadDetails(open(PREFIXED_DETAIL));

        assertThat(outcome.read()).isEqualTo(CHILD_COUNT);
        assertThat(outcome.inserted()).isZero();
        assertThat(outcome.alreadyPresent()).isZero();
        assertThat(outcome.orphaned()).isEqualTo(CHILD_COUNT);
        verify(this.details, never()).save(any());
    }

    /**
     * A stream whose length is not a whole number of records is refused before any row is written.
     *
     * <p>Assumptions: a remainder means the file was produced against a different layout or was truncated
     * in transit, and every offset after the first short record would then be wrong -- so the alternative
     * to refusing is loading plausible values into the wrong columns. The message names the stride, because
     * the likeliest cause is one of these two files being handed to the other's reader: the strides are
     * 100 and 206.</p>
     */
    @Test
    @DisplayName("a stream that is not a whole number of records is refused, naming the stride")
    void aPartialRecordIsRefused() {
        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .as("the 206-byte child file divided by the 100-byte root stride leaves a remainder")
                .isThrownBy(() -> loader.loadSummaries(open(PREFIXED_DETAIL)))
                .withMessageContaining("must hold a whole number of 100-byte records");

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_SUMMARY)))
                .withMessageContaining("must hold a whole number of 206-byte records");

        verify(this.summaries, never()).save(any());
        verify(this.details, never()).save(any());
    }

    /**
     * A hierarchical unload of the loaded rows reproduces the two fixture files byte for byte.
     *
     * <p>Assumptions: the circuit is closed rather than each direction being checked against a
     * hand-written expectation. Decoding and re-encoding through independent code paths and getting the
     * original bytes back is what detects an offset error in a packed money field, which a hand-written
     * expectation authored from the same misreading would not.</p>
     *
     * <p>Assumptions: the root file is reproduced in ASCENDING account order, which is why the ascending
     * sibling fixture is the comparison target and not the descending one this case loaded from. The unload
     * walks the table by key, so its output order is the table's and not the input file's; the two fixtures
     * exist as a pair precisely so that ordering is asserted rather than assumed, and a service that echoed
     * its input would fail here.</p>
     */
    @Test
    @DisplayName("a hierarchical unload of the loaded rows reproduces both fixture files byte for byte")
    void theHierarchicalUnloadReproducesTheFixtures() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        UnloadService.UnloadOutcome outcome = new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.PREFIXED, roots, children);

        assertThat(outcome.rootsWritten()).isEqualTo(ROOT_COUNT);
        assertThat(outcome.childrenWritten()).isEqualTo(CHILD_COUNT);
        assertThat(roots.toByteArray())
                .as("the unload emits roots in ascending key order, whatever order they were loaded in")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.toByteArray()).isEqualTo(prefixedChildrenGroupedByAccount());
    }

    /**
     * A sequential unload writes the same roots and BARE child segments, six bytes shorter each.
     *
     * <p>Assumptions: the two forms differ only in the child record, which is what lets one service serve
     * both reference programs. {@code cbl/DBUNLDGS.CBL} passes the segment alone to both of its inserts at
     * L302 to L304 and L321 to L323, so its child stride is 200 where the hierarchical form's is 206. The
     * root file is asserted IDENTICAL between the two forms, because both reference programs move the whole
     * hundred-byte root with no prefix.</p>
     */
    @Test
    @DisplayName("a sequential unload writes the same roots and bare 200-byte child segments")
    void theSequentialUnloadOmitsTheChildPrefix() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.SEQUENTIAL, roots, children);

        assertThat(roots.toByteArray())
                .as("the root record is the same in both forms")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.size())
                .as("four bare segments of 200 against four prefixed records of 206")
                .isEqualTo(CHILD_COUNT * PendingAuthDetailMapper.segmentLength())
                .isNotEqualTo(CHILD_COUNT * PendingAuthDetailMapper.unloadRecordLength());
        assertThat(children.toByteArray()).isEqualTo(bareChildrenGroupedByAccount());
    }

    /**
     * Confirms the declared strides are the geometry the fixtures were written to.
     *
     * <p>Assumptions: this guards the whole class. Every assertion above divides a fixture by a stride the
     * mappers declare, so a stride that drifted from the fixtures would turn every case here into a decode
     * of the wrong bytes -- and several would still pass, because a file divided by a wrong-but-factor
     * stride yields records that decode to something.</p>
     */
    @Test
    @DisplayName("the fixtures divide exactly by the strides the mappers declare")
    void theFixtureGeometryMatchesTheDeclaredStrides() {
        assertThat(PendingAuthSummaryMapper.unloadRecordLength()).isEqualTo(100);
        assertThat(PendingAuthDetailMapper.segmentLength()).isEqualTo(200);
        assertThat(PendingAuthDetailMapper.unloadRecordLength()).isEqualTo(206);

        assertThat(bytes(PREFIXED_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(SEQUENTIAL_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(PREFIXED_DETAIL)).hasSize(CHILD_COUNT * 206);
        assertThat(bytes(SEQUENTIAL_DETAIL)).hasSize(CHILD_COUNT * 200);
    }

    /**
     * Answers the two repository walk methods from the rows the doubles have accepted.
     *
     * <p>Assumptions: the answers reproduce the ORDER the two query methods declare -- ascending account
     * for the outer walk, newest first within one account for the inner one -- because that order is the
     * contract the unload depends on and a double that returned insertion order would let a broken walk
     * pass. The page LIMIT is honoured for the same class of reason: the service decides a walk is
     * finished by receiving a page shorter than it asked for, so a double that ignored the limit would be
     * defining that signal rather than exercising it.</p>
     */
    private void givenWalksAnswerFromStoredRows() {
        when(this.summaries.findByAccountIdGreaterThanOrderByAccountIdAsc(any(), any()))
                .thenAnswer(invocation -> {
                    long after = invocation.<Long>getArgument(0).longValue();
                    Limit limit = invocation.getArgument(1);
                    return this.storedRoots.stream()
                            .filter(root -> root.getAccountId().longValue() > after)
                            .sorted((left, right) ->
                                    Long.compare(left.getAccountId(), right.getAccountId()))
                            .limit(limit.max())
                            .toList();
                });
        when(this.details.findByIdAccountIdOrderByIdAuthDateDescIdAuthTimeDesc(any()))
                .thenAnswer(invocation -> {
                    Long accountId = invocation.getArgument(0);
                    return this.storedChildren.stream()
                            .filter(child -> accountId.equals(child.getId().getAccountId()))
                            .sorted(AuthorizationExtractRoundTripTest::newestFirst)
                            .toList();
                });
    }

    /**
     * Rebuilds the expected prefixed child file in the order the reference walk emits.
     *
     * <p>Assumptions: the expectation is the fixture's own four records REORDERED, never re-encoded. The
     * fixture writes the two accounts alternating, and an unload writes one account's children before
     * moving to the next, so the two files hold the same four records in different orders. Reordering the
     * committed bytes keeps the fixture as the oracle for their CONTENT while letting the case assert the
     * order the walk produces.</p>
     *
     * <p>Assumptions: within one account the order is the RAW eight-byte key ascending, compared as
     * unsigned bytes, and that is derived from the reference declaration rather than from this migration's
     * decode. {@code ims/DBPAUTP0.dbd} L37 declares the child's unique sequence field over those eight
     * bytes as {@code TYPE=C}, so IMS sequences twins by byte-wise comparison of the stored NINES
     * COMPLEMENT -- and ascending on a complement is newest-first on the value. Stating the expectation
     * this way rather than by sorting the decoded keys is deliberate: it keeps the ordering expectation
     * independent of the decode the unload itself performs, so a decode that inverted the complement would
     * fail here instead of moving the expectation with it.</p>
     *
     * @return the four committed 206-byte records, account one's pair first and each pair newest first
     */
    private static byte[] prefixedChildrenGroupedByAccount() {
        return regroup(bytes(PREFIXED_DETAIL), PendingAuthDetailMapper.unloadRecordLength(),
                PendingAuthDetailMapper::unloadedAccountId);
    }

    /**
     * Compares two child records by the raw complement key IMS sequences twins on.
     *
     * @param left the first record, prefixed
     * @param right the second record, prefixed
     * @return a negative value when {@code left} sorts first in complement byte order
     */
    private static int byRawComplementKey(byte[] left, byte[] right) {
        int keyOffset = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
        int keyEnd = keyOffset + RAW_KEY_WIDTH;
        return Arrays.compareUnsigned(Arrays.copyOfRange(left, keyOffset, keyEnd),
                Arrays.copyOfRange(right, keyOffset, keyEnd));
    }

    /**
     * Rebuilds the expected bare child file, with the four segments grouped by account.
     *
     * <p>Assumptions: the segments come from the PREFIXED fixture with the prefix stripped, and not from
     * the sequential fixture. The sequential fixture's own records carry no account at all, so grouping
     * them by account is not something their bytes can support; stripping the prefix from the attributable
     * file is the only way to state the expectation without re-encoding anything.</p>
     *
     * @return the four committed segments with their prefixes removed, account one's pair first
     */
    private static byte[] bareChildrenGroupedByAccount() {
        byte[] grouped = prefixedChildrenGroupedByAccount();
        int stride = PendingAuthDetailMapper.unloadRecordLength();
        ByteArrayOutputStream bare = new ByteArrayOutputStream();
        for (int offset = 0; offset < grouped.length; offset += stride) {
            byte[] segment = PendingAuthDetailMapper.unloadedSegment(
                    Arrays.copyOfRange(grouped, offset, offset + stride));
            bare.write(segment, 0, segment.length);
        }
        return bare.toByteArray();
    }

    /**
     * Groups fixed-length records by a key read from each, preserving order within each group.
     *
     * @param image the whole fixture
     * @param stride the declared record length
     * @param keyOf reads the grouping key from one record
     * @return the same records concatenated, grouped by ascending key
     */
    private static byte[] regroup(byte[] image, int stride, Function<byte[], Long> keyOf) {
        Map<Long, List<byte[]>> grouped = new LinkedHashMap<>();
        for (int offset = 0; offset < image.length; offset += stride) {
            byte[] record = Arrays.copyOfRange(image, offset, offset + stride);
            grouped.computeIfAbsent(keyOf.apply(record), key -> new ArrayList<>()).add(record);
        }
        ByteArrayOutputStream ordered = new ByteArrayOutputStream();
        grouped.keySet().stream().sorted().forEach(key -> {
            List<byte[]> beneath = new ArrayList<>(grouped.get(key));
            beneath.sort(AuthorizationExtractRoundTripTest::byRawComplementKey);
            beneath.forEach(record -> ordered.write(record, 0, record.length));
        });
        return ordered.toByteArray();
    }

    /**
     * Orders two authorizations newest first, which is the order the inner walk declares.
     *
     * @param left the first authorization
     * @param right the second authorization
     * @return a negative value when {@code left} is newer, positive when older, zero when equal
     */
    private static int newestFirst(PendingAuthDetail left, PendingAuthDetail right) {
        PendingAuthDetailKey leftKey = left.getId();
        PendingAuthDetailKey rightKey = right.getId();
        int byDate = Integer.compare(rightKey.getAuthDate(), leftKey.getAuthDate());
        return byDate != 0 ? byDate
                : Integer.compare(rightKey.getAuthTime(), leftKey.getAuthTime());
    }

    /**
     * Reads a fixture from the test class path as a stream.
     *
     * @param name the file name inside the fixture directory
     * @return a stream over every byte of the file
     */
    private static InputStream open(String name) {
        return new ByteArrayInputStream(bytes(name));
    }

    /**
     * Reads a fixture from the test class path in full.
     *
     * @param name the file name inside the fixture directory
     * @return every byte of the file, unmodified
     * @throws AssertionError if the fixture is absent from the class path
     * @throws UncheckedIOException if the stream cannot be read
     */
    private static byte[] bytes(String name) {
        try (InputStream stream =
                AuthorizationExtractRoundTripTest.class.getResourceAsStream(ROOT + name)) {
            if (stream == null) {
                throw new AssertionError("fixture " + name + " is not on the test class path");
            }
            return stream.readAllBytes();
        } catch (IOException failure) {
            throw new UncheckedIOException("fixture " + name + " could not be read", failure);
        }
    }
}
