package com.carddemo.authorization.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.carddemo.authorization.domain.PendingAuthDetail;
import com.carddemo.authorization.domain.PendingAuthDetailKey;
import com.carddemo.authorization.domain.PendingAuthSummary;
import com.carddemo.authorization.mapper.PendingAuthDetailMapper;
import com.carddemo.authorization.mapper.PendingAuthSummaryMapper;
import com.carddemo.authorization.repository.PendingAuthDetailRepository;
import com.carddemo.authorization.repository.PendingAuthSummaryRepository;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Limit;

/**
 * Drives {@link LoadService} and {@link UnloadService} against the committed extract fixtures.
 *
 * <p><b>Purpose.</b> The two services are the migrated forms of
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBLOD.CBL},
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBUNL.CBL} and
 * {@code app/app-authorization-ims-db2-mq/cbl/DBUNLDGS.CBL}. Between them they define a file format, so
 * the property worth asserting is that the format survives a full circuit: bytes in through the loader,
 * rows out through the unloader, and the same bytes back. A test that only checked the loader called save
 * would pass for a loader that decoded every field into the wrong column.
 *
 * <p>Assumptions: the fixtures are the oracle rather than anything this class computes. The four files
 * were generated by the Python ETL codec in
 * {@code data-migration/src/carddemo_migration/copybook/packed.py}, an independently written transcription
 * of the same copybooks, so a byte-identical circuit through the Java codec is a cross-language agreement
 * rather than the Java codec agreeing with itself.
 *
 * <p>Assumptions: the repositories are STATEFUL doubles rather than fixed stubs, and that is a
 * requirement rather than a convenience. Within one load the loader inserts a summary and then, for each
 * child, asks whether that child's parent exists -- so a double answering a fixed value for existence
 * would either report every child orphaned or every summary already present, and neither is the situation
 * under test. A real repository answers correctly here because an existence query flushes the pending
 * inserts of its own transaction before it runs; the doubles below reproduce that by remembering what was
 * saved.
 *
 * <p>Alternatives Considered: a container-backed test with a real database. Rejected as the primary form
 * because both services are pure translations between a byte stream and repository calls -- neither
 * declares a query and neither writes SQL -- so a container would add startup cost without asserting
 * anything these doubles cannot. The committed repository integration test covers the persistence side.
 *
 * <p>A test class accepts no parameter, yields no value and raises nothing, so this block carries no
 * parameter, return or exception at-clause.
 */
@ExtendWith(MockitoExtension.class)
class AuthorizationExtractRoundTripTest {

    /** The class-path directory the committed fixtures live in. */
    private static final String ROOT = "/fixtures/";

    /** The hierarchical unload's summary file: two hundred-byte roots, highest account first. */
    private static final String PREFIXED_SUMMARY = "unload-prefixed-summary-100.bin";

    /** The hierarchical unload's child file: four two-hundred-and-six-byte prefixed records. */
    private static final String PREFIXED_DETAIL = "unload-prefixed-detail-206.bin";

    /** The sequential unload's summary file: the same two roots, lowest account first. */
    private static final String SEQUENTIAL_SUMMARY = "unload-gsam-summary-100.bin";

    /** The sequential unload's child file: four bare two-hundred-byte segments. */
    private static final String SEQUENTIAL_DETAIL = "unload-gsam-detail-200.bin";

    /** The lower of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_ONE = 10_000_000_001L;

    /** The higher of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_TWO = 10_000_000_002L;

    /** The number of roots the summary fixtures hold. */
    private static final int ROOT_COUNT = 2;

    /** The number of children the detail fixtures hold. */
    private static final int CHILD_COUNT = 4;

    /**
     * The width of the raw complement key IMS sequences the child twins on.
     *
     * <p>Assumptions: eight, from {@code FIELD NAME=(PAUT9CTS,SEQ,U),START=1,BYTES=8,TYPE=C} at
     * {@code app/app-authorization-ims-db2-mq/ims/DBPAUTP0.dbd} L37 -- the packed date and packed time
     * complements together, at the head of every segment.
     */
    private static final int RAW_KEY_WIDTH = 8;

    /** The summary repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthSummaryRepository summaries;

    /** The authorization repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthDetailRepository details;

    /** The summaries the doubles have accepted, in save order. */
    private final List<PendingAuthSummary> storedRoots = new ArrayList<>();

    /** The authorizations the doubles have accepted, in save order. */
    private final List<PendingAuthDetail> storedChildren = new ArrayList<>();

    /**
     * Makes the summary double remember what it is given and answer existence from that.
     */
    private void givenSummariesRemember() {
        when(this.summaries.save(any())).thenAnswer(invocation -> {
            PendingAuthSummary saved = invocation.getArgument(0);
            this.storedRoots.add(saved);
            return saved;
        });
        when(this.summaries.existsById(any())).thenAnswer(invocation -> {
            Long accountId = invocation.getArgument(0);
            return this.storedRoots.stream()
                    .anyMatch(root -> accountId.equals(root.getAccountId()));
        });
    }

    /**
     * Makes the authorization double remember what it is given and answer existence from that.
     */
    private void givenDetailsRemember() {
        when(this.details.save(any())).thenAnswer(invocation -> {
            PendingAuthDetail saved = invocation.getArgument(0);
            this.storedChildren.add(saved);
            return saved;
        });
        when(this.details.existsById(any())).thenAnswer(invocation -> {
            PendingAuthDetailKey key = invocation.getArgument(0);
            return this.storedChildren.stream().anyMatch(child -> key.equals(child.getId()));
        });
    }

    /**
     * Loads both prefixed fixtures through the loader and returns what it reported.
     *
     * @return the loader's own counts
     */
    private LoadService.LoadOutcome loadBothFixtures() {
        return new LoadService(this.summaries, this.details)
                .load(open(PREFIXED_SUMMARY), open(PREFIXED_DETAIL));
    }

    /**
     * The loader loads both roots and all four children, and attributes each child to its own parent.
     *
     * <p>Assumptions: the child prefixes ALTERNATE between the two accounts in this fixture rather than
     * being grouped, which is what makes the attribution assertion meaningful. A loader that carried the
     * previous record's account forward would produce a plausible result on a grouped file and the wrong
     * one here.</p>
     *
     * <p>Assumptions: the roots are asserted to load in FILE order, which this fixture deliberately writes
     * highest account first. A loader that sorted its input would make this fixture and its ascending
     * sibling indistinguishable, which is the reason the pair exists.</p>
     */
    @Test
    @DisplayName("the loader loads two roots and four children, attributing each child to its own parent")
    void theLoaderLoadsBothFilesAndAttributesEveryChild() {
        givenSummariesRemember();
        givenDetailsRemember();

        LoadService.LoadOutcome outcome = loadBothFixtures();

        assertThat(outcome.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.inserted()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.alreadyPresent()).isZero();
        assertThat(outcome.inserted() + outcome.alreadyPresent())
                .as("a load that returns accounted for every record it read")
                .isEqualTo(outcome.read());

        assertThat(this.storedRoots)
                .extracting(PendingAuthSummary::getAccountId)
                .containsExactly(ACCOUNT_TWO, ACCOUNT_ONE);
        assertThat(this.storedChildren)
                .extracting(child -> child.getId().getAccountId())
                .as("each child's account comes from its own six-byte packed prefix")
                .containsExactly(ACCOUNT_ONE, ACCOUNT_TWO, ACCOUNT_ONE, ACCOUNT_TWO);
    }

    /**
     * Re-running a completed load inserts nothing and reports every record as already present.
     *
     * <p>Assumptions: this is the reference program's treatment of the duplicate-segment status -- its L256
     * to L258 and L329 to L331 report the duplicate and continue -- and it is what makes a partially
     * completed load safely re-runnable. Asserting that the stored state did not GROW is the important
     * half: an upsert would satisfy a count assertion while silently replacing a row an operator had since
     * corrected online.</p>
     */
    @Test
    @DisplayName("re-running a completed load inserts nothing and counts every record already present")
    void aRerunSkipsEveryRecordRatherThanOverwritingIt() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();

        LoadService.LoadOutcome rerun = loadBothFixtures();

        assertThat(rerun.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(rerun.inserted()).isZero();
        assertThat(rerun.alreadyPresent()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(this.storedRoots).hasSize(ROOT_COUNT);
        assertThat(this.storedChildren).hasSize(CHILD_COUNT);
    }

    /**
     * A condition that is neither success nor a duplicate propagates rather than being counted.
     *
     * <p>Assumptions: this is the other half of the idempotence ruling and it is asserted separately,
     * because tolerating a duplicate and swallowing everything else are the two readings of
     * {@code cbl/PAUDBLOD.CBL} L256 to L262 that a test has to tell apart. Its L256 to L258 report the
     * duplicate status and continue; its L259 to L262 reach the abend for every other status, and L332 to
     * L336 do the same for a child. A loader that caught broadly would satisfy the re-run case above and
     * still report a successful load having stored less than it read.</p>
     */
    @Test
    @DisplayName("a store failure that is not a duplicate propagates instead of being counted as a skip")
    void aFailureThatIsNotADuplicatePropagates() {
        when(this.summaries.existsById(any())).thenReturn(false);
        when(this.summaries.save(any())).thenThrow(new IllegalStateException("store unavailable"));

        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(IllegalStateException.class)
                .isThrownBy(() -> loader.loadSummaries(open(PREFIXED_SUMMARY)))
                .withMessage("store unavailable");
    }

    /**
     * Divergence D-C: a child whose parent summary is absent is refused, and the refusal names the account.
     *
     * <p>Assumptions: this asserts divergence D-C, recorded on {@link LoadService} and registered in
     * {@code docs/architecture/cobol-to-service-traceability.md}. The reference program passes such a child
     * over in silence: its insert sits inside the branch a successful parent position opens at
     * {@code cbl/PAUDBLOD.CBL} L305, and a failed position falls past the insert AND past the abend test
     * nested inside that branch, reaching L315 without inserting or reporting. The target refuses
     * instead.</p>
     *
     * <p>Assumptions: the assertion is on the ACCOUNT the refusal carries and not merely on its type,
     * because carrying the key is the whole point of the divergence. A refusal that named no account would
     * leave an operator with exactly what the reference program leaves them -- the knowledge that something
     * was wrong and no way to find which record -- so a test that accepted any exception would pass for an
     * implementation that had recovered none of the value.</p>
     *
     * <p>Assumptions: the case also asserts that NOTHING was written. The refusal is raised inside the same
     * transaction the load runs in, so on a real store the rollback discards the earlier records; the
     * double cannot roll back, so the assertion is made directly against the save.</p>
     */
    @Test
    @DisplayName("D-C: a child whose parent summary is absent is refused, naming the account")
    void anUnresolvableParentIsRefusedAndNamesTheAccount() {
        when(this.summaries.existsById(any())).thenReturn(false);

        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)))
                .satisfies(refused -> {
                    assertThat(refused.getAccountId())
                            .as("the first prefixed record of this fixture names the lower account")
                            .isEqualTo(ACCOUNT_ONE);
                    assertThat(refused.getRecordOrdinal())
                            .as("the refusal locates the record, one-based, so the file can be read at it")
                            .isEqualTo(1);
                    assertThat(refused).hasMessageContaining(String.valueOf(ACCOUNT_ONE));
                });

        verify(this.details, never()).save(any());
    }

    /**
     * Divergence D-C: the refusal stops the pass rather than continuing through the remaining records.
     *
     * <p>Assumptions: this is asserted separately from the case above because the two properties are
     * independent, and an implementation can have one without the other. A loader that logged the account
     * and then carried on would produce a refusal carrying the right key and still lose the remaining
     * records, which is the outcome the divergence exists to prevent. What fixes the count at one is that
     * the parent check precedes the save for every record and raises on the first failure: the fixture
     * holds four children whose parents are all absent, and exactly one is reached.</p>
     */
    @Test
    @DisplayName("D-C: the refusal ends the pass at the first unresolvable record")
    void anUnresolvableParentEndsThePass() {
        when(this.summaries.existsById(any())).thenReturn(false);

        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)));

        verify(this.summaries, times(1)).existsById(any());
        verify(this.details, never()).existsById(any());
        verify(this.details, never()).save(any());
    }

    /**
     * A child record whose six-byte prefix does not decode is refused, naming the record.
     *
     * <p>Assumptions: this is the second condition {@code cbl/PAUDBLOD.CBL} passes over. Its
     * {@code 3000-READ-CHILD-SEG-FILE} guards the insert with {@code IF ROOT-SEG-KEY IS NUMERIC} at
     * <strong>L275</strong> and supplies no {@code ELSE}, so a prefix failing that test takes the record
     * out of the run with no message at all.</p>
     *
     * <p>Assumptions: the corrupted prefix is built by writing a byte whose low nibble is a DIGIT into the
     * sign position, which is the last of the six. A packed field's final nibble is its sign, so a digit
     * there is exactly what the reference numeric test rejects, and it is a corruption the length check
     * cannot catch -- the record is still 206 bytes.</p>
     *
     * <p>Assumptions: the refusal is asserted to name the ordinal and NOT an account, because an
     * undecodable prefix names none. That asymmetry with D-C is the reason the two refusals are separate
     * types rather than one carrying an optional key.</p>
     */
    @Test
    @DisplayName("a child record whose packed prefix does not decode is refused, naming the record")
    void anUndecodablePrefixIsRefused() {
        byte[] corrupted = bytes(PREFIXED_DETAIL).clone();
        int signByte = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength() - 1;
        corrupted[signByte] = (byte) 0x05;

        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(LoadService.MalformedParentKeyException.class)
                .isThrownBy(() -> loader.loadDetails(new ByteArrayInputStream(corrupted)))
                .satisfies(refused -> assertThat(refused.getRecordOrdinal()).isEqualTo(1))
                .withMessageContaining("record 1")
                .havingCause()
                .isInstanceOf(IllegalArgumentException.class);

        verify(this.details, never()).save(any());
    }

    /**
     * The six-byte prefix is decoded as PACKED decimal, and a text reading of it yields another number.
     *
     * <p>Assumptions: this asserts the prefix's storage regime rather than the loader's plumbing, because a
     * reader that took those six bytes as characters would not fail -- it would attribute the child to a
     * different account, which is a wrong answer rather than an error. The case therefore states both
     * readings and asserts they disagree, so an implementation that switched to a text read would fail here
     * instead of loading plausible rows under the wrong account.</p>
     *
     * <p>Assumptions: the packed reading is the one the reference declaration fixes.
     * {@code cbl/PAUDBLOD.CBL} <strong>L47</strong> declares the prefix
     * {@code 05 ROOT-SEG-KEY PIC S9(11) COMP-3}, six bytes carrying two digits each and a sign nibble.</p>
     */
    @Test
    @DisplayName("the packed prefix decodes to an account a text reading of the same bytes does not give")
    void theParentPrefixIsReadAsPackedDecimalAndNotAsText() {
        byte[] first = Arrays.copyOfRange(bytes(PREFIXED_DETAIL), 0,
                PendingAuthDetailMapper.unloadRecordLength());
        int prefixWidth = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
        String asText = new String(Arrays.copyOfRange(first, 0, prefixWidth),
                StandardCharsets.ISO_8859_1);

        assertThat(PendingAuthDetailMapper.unloadedAccountId(first))
                .as("the packed reading is the account the fixture was written for")
                .isEqualTo(ACCOUNT_ONE);
        assertThat(asText.trim())
                .as("the same six bytes read as characters are not the digits of that account")
                .isNotEqualTo(String.valueOf(ACCOUNT_ONE));

        givenSummariesRemember();
        givenDetailsRemember();
        this.summaries.save(PendingAuthSummaryMapper.fromExtractRecord(Arrays.copyOfRange(
                bytes(PREFIXED_SUMMARY), PendingAuthSummaryMapper.unloadRecordLength(),
                ROOT_COUNT * PendingAuthSummaryMapper.unloadRecordLength())));

        LoadService.LoadOutcome outcome = new LoadService(this.summaries, this.details)
                .loadDetails(new ByteArrayInputStream(first));

        assertThat(outcome.inserted()).isEqualTo(1);
        assertThat(this.storedChildren)
                .singleElement()
                .extracting(child -> child.getId().getAccountId())
                .isEqualTo(ACCOUNT_ONE);
    }

    /**
     * Loading the child file before the summary file is refused, which is why the two passes are ordered.
     *
     * <p>Assumptions: {@code MAIN-PARA} at {@code cbl/PAUDBLOD.CBL} <strong>L169 to L187</strong> runs its
     * root loop at L177 to L178 to exhaustion before its child loop at L180 to L181 begins, and this case
     * asserts the ordering is load-bearing rather than incidental. Reversing the two passes refuses the
     * first child, because no parent has been written yet -- so a loader that interleaved them, or that
     * ran the child pass first, would fail here rather than silently attributing children to rows that do
     * not exist.</p>
     */
    @Test
    @DisplayName("the child pass depends on the root pass having run first, so the order is asserted")
    void theTwoPassesRunInTheReferenceOrder() {
        givenSummariesRemember();
        givenDetailsRemember();
        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .as("the child pass alone finds no parent, because the root pass writes them")
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)));

        LoadService.LoadOutcome ordered =
                loader.load(open(PREFIXED_SUMMARY), open(PREFIXED_DETAIL));

        assertThat(ordered.inserted()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(this.storedRoots).hasSize(ROOT_COUNT);
        assertThat(this.storedChildren).hasSize(CHILD_COUNT);
    }

    /**
     * A stream whose length is not a whole number of records is refused before any row is written.
     *
     * <p>Assumptions: a remainder means the file was produced against a different layout or was truncated
     * in transit, and every offset after the first short record would then be wrong -- so the alternative
     * to refusing is loading plausible values into the wrong columns. The message names the stride, because
     * the likeliest cause is one of these two files being handed to the other's reader: the strides are
     * 100 and 206.</p>
     */
    @Test
    @DisplayName("a stream that is not a whole number of records is refused, naming the stride")
    void aPartialRecordIsRefused() {
        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .as("the 206-byte child file divided by the 100-byte root stride leaves a remainder")
                .isThrownBy(() -> loader.loadSummaries(open(PREFIXED_DETAIL)))
                .withMessageContaining("must hold a whole number of 100-byte records");

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_SUMMARY)))
                .withMessageContaining("must hold a whole number of 206-byte records");

        verify(this.summaries, never()).save(any());
        verify(this.details, never()).save(any());
    }

    /**
     * A truncated record ends the pass rather than leaving the reader turning on the same bytes.
     *
     * <p>Assumptions: this asserts the removal of the non-termination hazard in the reference read loops.
     * Both end only when a status of {@code '10'} sets an end flag -- {@code END-ROOT-SEG-FILE} at
     * {@code cbl/PAUDBLOD.CBL} L233 and {@code END-CHILD-SEG-FILE} at its L285 -- and each has one further
     * branch that sets no flag and does not abend, at <strong>L235</strong> and <strong>L287</strong>
     * respectively. Under the {@code PERFORM ... UNTIL} at L178 and L181, reaching that branch leaves both
     * the flag and the file position unchanged, so the loop reads the same condition again.</p>
     *
     * <p>Assumptions: the case is expressed as a bounded assertion rather than as a plain call, because the
     * property under test is TERMINATION and a test that merely called the method would hang rather than
     * fail if the property were lost. Failing inside a timeout is the difference between a red build and a
     * stuck one.</p>
     */
    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    @DisplayName("a truncated final record terminates the pass instead of being read repeatedly")
    void aTruncatedRecordTerminatesRatherThanLooping() {
        byte[] whole = bytes(PREFIXED_SUMMARY);
        byte[] truncated = Arrays.copyOfRange(whole, 0, whole.length - 1);
        LoadService loader = new LoadService(this.summaries, this.details);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> loader.loadSummaries(new ByteArrayInputStream(truncated)))
                .withMessageContaining("must hold a whole number of 100-byte records");

        verify(this.summaries, never()).save(any());
    }

    /**
     * A hierarchical unload of the loaded rows reproduces the two fixture files byte for byte.
     *
     * <p>Assumptions: the circuit is closed rather than each direction being checked against a
     * hand-written expectation. Decoding and re-encoding through independent code paths and getting the
     * original bytes back is what detects an offset error in a packed money field, which a hand-written
     * expectation authored from the same misreading would not.</p>
     *
     * <p>Assumptions: the root file is reproduced in ASCENDING account order, which is why the ascending
     * sibling fixture is the comparison target and not the descending one this case loaded from. The unload
     * walks the table by key, so its output order is the table's and not the input file's; the two fixtures
     * exist as a pair precisely so that ordering is asserted rather than assumed, and a service that echoed
     * its input would fail here.</p>
     */
    @Test
    @DisplayName("a hierarchical unload of the loaded rows reproduces both fixture files byte for byte")
    void theHierarchicalUnloadReproducesTheFixtures() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        UnloadService.UnloadOutcome outcome = new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.PREFIXED, roots, children);

        assertThat(outcome.rootsWritten()).isEqualTo(ROOT_COUNT);
        assertThat(outcome.childrenWritten()).isEqualTo(CHILD_COUNT);
        assertThat(roots.toByteArray())
                .as("the unload emits roots in ascending key order, whatever order they were loaded in")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.toByteArray()).isEqualTo(prefixedChildrenGroupedByAccount());
    }

    /**
     * A sequential unload writes the same roots and BARE child segments, six bytes shorter each.
     *
     * <p>Assumptions: the two forms differ only in the child record, which is what lets one service serve
     * both reference programs. {@code cbl/DBUNLDGS.CBL} passes the segment alone to both of its inserts at
     * L302 to L304 and L321 to L323, so its child stride is 200 where the hierarchical form's is 206. The
     * root file is asserted IDENTICAL between the two forms, because both reference programs move the whole
     * hundred-byte root with no prefix.</p>
     */
    @Test
    @DisplayName("a sequential unload writes the same roots and bare 200-byte child segments")
    void theSequentialUnloadOmitsTheChildPrefix() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.SEQUENTIAL, roots, children);

        assertThat(roots.toByteArray())
                .as("the root record is the same in both forms")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.size())
                .as("four bare segments of 200 against four prefixed records of 206")
                .isEqualTo(CHILD_COUNT * PendingAuthDetailMapper.segmentLength())
                .isNotEqualTo(CHILD_COUNT * PendingAuthDetailMapper.unloadRecordLength());
        assertThat(children.toByteArray()).isEqualTo(bareChildrenGroupedByAccount());
    }

    /**
     * Confirms the declared strides are the geometry the fixtures were written to.
     *
     * <p>Assumptions: this guards the whole class. Every assertion above divides a fixture by a stride the
     * mappers declare, so a stride that drifted from the fixtures would turn every case here into a decode
     * of the wrong bytes -- and several would still pass, because a file divided by a wrong-but-factor
     * stride yields records that decode to something.</p>
     */
    @Test
    @DisplayName("the fixtures divide exactly by the strides the mappers declare")
    void theFixtureGeometryMatchesTheDeclaredStrides() {
        assertThat(PendingAuthSummaryMapper.unloadRecordLength()).isEqualTo(100);
        assertThat(PendingAuthDetailMapper.segmentLength()).isEqualTo(200);
        assertThat(PendingAuthDetailMapper.unloadRecordLength()).isEqualTo(206);

        assertThat(bytes(PREFIXED_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(SEQUENTIAL_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(PREFIXED_DETAIL)).hasSize(CHILD_COUNT * 206);
        assertThat(bytes(SEQUENTIAL_DETAIL)).hasSize(CHILD_COUNT * 200);
    }

    /**
     * Answers the two repository walk methods from the rows the doubles have accepted.
     *
     * <p>Assumptions: the answers reproduce the ORDER the two query methods declare -- ascending account
     * for the outer walk, newest first within one account for the inner one -- because that order is the
     * contract the unload depends on and a double that returned insertion order would let a broken walk
     * pass. The page LIMIT is honoured for the same class of reason: the service decides a walk is
     * finished by receiving a page shorter than it asked for, so a double that ignored the limit would be
     * defining that signal rather than exercising it.</p>
     */
    private void givenWalksAnswerFromStoredRows() {
        when(this.summaries.findByAccountIdGreaterThanOrderByAccountIdAsc(any(), any()))
                .thenAnswer(invocation -> {
                    long after = invocation.<Long>getArgument(0).longValue();
                    Limit limit = invocation.getArgument(1);
                    return this.storedRoots.stream()
                            .filter(root -> root.getAccountId().longValue() > after)
                            .sorted((left, right) ->
                                    Long.compare(left.getAccountId(), right.getAccountId()))
                            .limit(limit.max())
                            .toList();
                });
        when(this.details.findByIdAccountIdOrderByIdAuthDateDescIdAuthTimeDesc(any()))
                .thenAnswer(invocation -> {
                    Long accountId = invocation.getArgument(0);
                    return this.storedChildren.stream()
                            .filter(child -> accountId.equals(child.getId().getAccountId()))
                            .sorted(AuthorizationExtractRoundTripTest::newestFirst)
                            .toList();
                });
    }

    /**
     * Rebuilds the expected prefixed child file in the order the reference walk emits.
     *
     * <p>Assumptions: the expectation is the fixture's own four records REORDERED, never re-encoded. The
     * fixture writes the two accounts alternating, and an unload writes one account's children before
     * moving to the next, so the two files hold the same four records in different orders. Reordering the
     * committed bytes keeps the fixture as the oracle for their CONTENT while letting the case assert the
     * order the walk produces.</p>
     *
     * <p>Assumptions: within one account the order is the RAW eight-byte key ascending, compared as
     * unsigned bytes, and that is derived from the reference declaration rather than from this migration's
     * decode. {@code ims/DBPAUTP0.dbd} L37 declares the child's unique sequence field over those eight
     * bytes as {@code TYPE=C}, so IMS sequences twins by byte-wise comparison of the stored NINES
     * COMPLEMENT -- and ascending on a complement is newest-first on the value. Stating the expectation
     * this way rather than by sorting the decoded keys is deliberate: it keeps the ordering expectation
     * independent of the decode the unload itself performs, so a decode that inverted the complement would
     * fail here instead of moving the expectation with it.</p>
     *
     * @return the four committed 206-byte records, account one's pair first and each pair newest first
     */
    private static byte[] prefixedChildrenGroupedByAccount() {
        return regroup(bytes(PREFIXED_DETAIL), PendingAuthDetailMapper.unloadRecordLength(),
                PendingAuthDetailMapper::unloadedAccountId);
    }

    /**
     * Compares two child records by the raw complement key IMS sequences twins on.
     *
     * @param left the first record, prefixed
     * @param right the second record, prefixed
     * @return a negative value when {@code left} sorts first in complement byte order
     */
    private static int byRawComplementKey(byte[] left, byte[] right) {
        int keyOffset = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
        int keyEnd = keyOffset + RAW_KEY_WIDTH;
        return Arrays.compareUnsigned(Arrays.copyOfRange(left, keyOffset, keyEnd),
                Arrays.copyOfRange(right, keyOffset, keyEnd));
    }

    /**
     * Rebuilds the expected bare child file, with the four segments grouped by account.
     *
     * <p>Assumptions: the segments come from the PREFIXED fixture with the prefix stripped, and not from
     * the sequential fixture. The sequential fixture's own records carry no account at all, so grouping
     * them by account is not something their bytes can support; stripping the prefix from the attributable
     * file is the only way to state the expectation without re-encoding anything.</p>
     *
     * @return the four committed segments with their prefixes removed, account one's pair first
     */
    private static byte[] bareChildrenGroupedByAccount() {
        byte[] grouped = prefixedChildrenGroupedByAccount();
        int stride = PendingAuthDetailMapper.unloadRecordLength();
        ByteArrayOutputStream bare = new ByteArrayOutputStream();
        for (int offset = 0; offset < grouped.length; offset += stride) {
            byte[] segment = PendingAuthDetailMapper.unloadedSegment(
                    Arrays.copyOfRange(grouped, offset, offset + stride));
            bare.write(segment, 0, segment.length);
        }
        return bare.toByteArray();
    }

    /**
     * Groups fixed-length records by a key read from each, preserving order within each group.
     *
     * @param image the whole fixture
     * @param stride the declared record length
     * @param keyOf reads the grouping key from one record
     * @return the same records concatenated, grouped by ascending key
     */
    private static byte[] regroup(byte[] image, int stride, Function<byte[], Long> keyOf) {
        Map<Long, List<byte[]>> grouped = new LinkedHashMap<>();
        for (int offset = 0; offset < image.length; offset += stride) {
            byte[] record = Arrays.copyOfRange(image, offset, offset + stride);
            grouped.computeIfAbsent(keyOf.apply(record), key -> new ArrayList<>()).add(record);
        }
        ByteArrayOutputStream ordered = new ByteArrayOutputStream();
        grouped.keySet().stream().sorted().forEach(key -> {
            List<byte[]> beneath = new ArrayList<>(grouped.get(key));
            beneath.sort(AuthorizationExtractRoundTripTest::byRawComplementKey);
            beneath.forEach(record -> ordered.write(record, 0, record.length));
        });
        return ordered.toByteArray();
    }

    /**
     * Orders two authorizations newest first, which is the order the inner walk declares.
     *
     * @param left the first authorization
     * @param right the second authorization
     * @return a negative value when {@code left} is newer, positive when older, zero when equal
     */
    private static int newestFirst(PendingAuthDetail left, PendingAuthDetail right) {
        PendingAuthDetailKey leftKey = left.getId();
        PendingAuthDetailKey rightKey = right.getId();
        int byDate = Integer.compare(rightKey.getAuthDate(), leftKey.getAuthDate());
        return byDate != 0 ? byDate
                : Integer.compare(rightKey.getAuthTime(), leftKey.getAuthTime());
    }

    /**
     * Reads a fixture from the test class path as a stream.
     *
     * @param name the file name inside the fixture directory
     * @return a stream over every byte of the file
     */
    private static InputStream open(String name) {
        return new ByteArrayInputStream(bytes(name));
    }

    /**
     * Reads a fixture from the test class path in full.
     *
     * @param name the file name inside the fixture directory
     * @return every byte of the file, unmodified
     * @throws AssertionError if the fixture is absent from the class path
     * @throws UncheckedIOException if the stream cannot be read
     */
    private static byte[] bytes(String name) {
        try (InputStream stream =
                AuthorizationExtractRoundTripTest.class.getResourceAsStream(ROOT + name)) {
            if (stream == null) {
                throw new AssertionError("fixture " + name + " is not on the test class path");
            }
            return stream.readAllBytes();
        } catch (IOException failure) {
            throw new UncheckedIOException("fixture " + name + " could not be read", failure);
        }
    }
}
