package com.carddemo.authorization.service;


import com.carddemo.authorization.domain.PendingAuthDetail;
import com.carddemo.authorization.domain.PendingAuthDetailKey;
import com.carddemo.authorization.domain.PendingAuthSummary;
import com.carddemo.authorization.mapper.PendingAuthDetailMapper;
import com.carddemo.authorization.mapper.PendingAuthSummaryMapper;
import com.carddemo.authorization.repository.PendingAuthDetailRepository;
import com.carddemo.authorization.repository.PendingAuthSummaryRepository;
import com.carddemo.common.codec.CopybookLayout;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Limit;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.TransactionTemplate;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Drives {@link LoadService} and {@link UnloadService} against the committed extract fixtures.
 *
 * <p><b>Purpose.</b> The two services are the migrated forms of
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBLOD.CBL},
 * {@code app/app-authorization-ims-db2-mq/cbl/PAUDBUNL.CBL} and
 * {@code app/app-authorization-ims-db2-mq/cbl/DBUNLDGS.CBL}. Between them they define a file format, so
 * the property worth asserting is that the format survives a full circuit: bytes in through the loader,
 * rows out through the unloader, and the same bytes back. A test that only checked the loader called save
 * would pass for a loader that decoded every field into the wrong column.
 *
 * <p>Assumptions: the fixtures are the oracle rather than anything this class computes. The four files
 * were generated by the Python ETL codec in
 * {@code data-migration/src/carddemo_migration/copybook/packed.py}, an independently written transcription
 * of the same copybooks, so a byte-identical circuit through the Java codec is a cross-language agreement
 * rather than the Java codec agreeing with itself.
 *
 * <p>Assumptions: the repositories are STATEFUL doubles rather than fixed stubs, and that is a
 * requirement rather than a convenience. Within one load the loader inserts a summary and then, for each
 * child, asks whether that child's parent exists -- so a double answering a fixed value for existence
 * would either report every child orphaned or every summary already present, and neither is the situation
 * under test. A real repository answers correctly here because an existence query flushes the pending
 * inserts of its own transaction before it runs; the doubles below reproduce that by remembering what was
 * saved.
 *
 * <p>Alternatives Considered: a container-backed test with a real database. Rejected as the primary form
 * because both services are pure translations between a byte stream and repository calls -- neither
 * declares a query and neither writes SQL -- so a container would add startup cost without asserting
 * anything these doubles cannot. The committed repository integration test covers the persistence side.
 *
 * <p>A test class accepts no parameter, yields no value and raises nothing, so this block carries no
 * parameter, return or exception at-clause.
 */
@ExtendWith(MockitoExtension.class)
class AuthorizationExtractRoundTripTest {

    /** The class-path directory the committed fixtures live in. */
    private static final String ROOT = "/fixtures/";

    /** The hierarchical unload's summary file: two hundred-byte roots, highest account first. */
    private static final String PREFIXED_SUMMARY = "unload-prefixed-summary-100.bin";

    /** The hierarchical unload's child file: four two-hundred-and-six-byte prefixed records. */
    private static final String PREFIXED_DETAIL = "unload-prefixed-detail-206.bin";

    /** The sequential unload's summary file: the same two roots, lowest account first. */
    private static final String SEQUENTIAL_SUMMARY = "unload-gsam-summary-100.bin";

    /** The sequential unload's child file: four bare two-hundred-byte segments. */
    private static final String SEQUENTIAL_DETAIL = "unload-gsam-detail-200.bin";

    /** The lower of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_ONE = 10_000_000_001L;

    /** The higher of the two accounts the fixtures carry. */
    private static final Long ACCOUNT_TWO = 10_000_000_002L;

    /** The number of roots the summary fixtures hold. */
    private static final int ROOT_COUNT = 2;

    /** The number of children the detail fixtures hold. */
    private static final int CHILD_COUNT = 4;

    /** The single-record fixture whose fraud position holds a character the column cannot store. */
    private static final String FRAUD_POSITION_OUT_OF_DOMAIN = "pautdtl1-auth-fraud-invalid.bin";

    /** The name of the one-byte field that fixture exists to put out of domain. */
    private static final String FRAUD_FIELD = "PA-AUTH-FRAUD";

    /**
     * The width of the raw complement key IMS sequences the child twins on.
     *
     * <p>Assumptions: eight, from {@code FIELD NAME=(PAUT9CTS,SEQ,U),START=1,BYTES=8,TYPE=C} at
     * {@code app/app-authorization-ims-db2-mq/ims/DBPAUTP0.dbd} L37 -- the packed date and packed time
     * complements together, at the head of every segment.
     */
    private static final int RAW_KEY_WIDTH = 8;

    /** The summary repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthSummaryRepository summaries;

    /** The authorization repository the loader writes and the unloader walks. */
    @Mock
    private PendingAuthDetailRepository details;

    /** The summaries the doubles have accepted, in save order. */
    private final List<PendingAuthSummary> storedRoots = new ArrayList<>();

    /** The authorizations the doubles have accepted, in save order. */
    private final List<PendingAuthDetail> storedChildren = new ArrayList<>();

    /**
     * Makes the summary double remember what it is given and answer existence from that.
     */
    private void givenSummariesRemember() {
        // WHY : Refactoring Rationale: the double answers the BATCHED presence query and the
        //       conflict-tolerant insert, and the single-row save, the batched save and the identity probe
        //       it answered at various points before are all gone. The loader settles presence for a whole
        //       chunk in one statement and then writes each fresh row with a statement that tolerates a
        //       conflict, so a double shaped around either mechanism alone would leave these cases unable
        //       to observe the loader they now exercise.
        // WHY : Assumptions: the insert double returns 1 for a row it stores and 0 for one whose key it
        //       already holds, which is the row count the statement reports. Answering 1 unconditionally
        //       would make every re-run look like a fresh insert and the re-run case would pass while
        //       asserting nothing.
        when(this.summaries.insertSummaryIfAbsent(any())).thenAnswer(invocation -> {
            PendingAuthSummary row = invocation.getArgument(0);
            boolean known = this.storedRoots.stream()
                    .anyMatch(stored -> stored.getAccountId().equals(row.getAccountId()));
            if (known) {
                return Integer.valueOf(0);
            }
            this.storedRoots.add(row);
            return Integer.valueOf(1);
        });
        when(this.summaries.findExistingAccountIds(any())).thenAnswer(invocation -> {
            Collection<Long> wanted = invocation.getArgument(0);
            return this.storedRoots.stream().map(PendingAuthSummary::getAccountId)
                    .filter(wanted::contains).toList();
        });
    }

    /**
     * Makes the authorization double remember what it is given and answer existence from that.
     */
    private void givenDetailsRemember() {
        when(this.details.insertDetailIfAbsent(any())).thenAnswer(invocation -> {
            PendingAuthDetail row = invocation.getArgument(0);
            boolean known = this.storedChildren.stream()
                    .anyMatch(stored -> stored.getId().equals(row.getId()));
            if (known) {
                return Integer.valueOf(0);
            }
            this.storedChildren.add(row);
            return Integer.valueOf(1);
        });
        when(this.details.findExistingIds(any())).thenAnswer(invocation -> {
            Collection<PendingAuthDetailKey> wanted = invocation.getArgument(0);
            return this.storedChildren.stream().map(PendingAuthDetail::getId)
                    .filter(wanted::contains).toList();
        });
    }

    /**
     * Builds a transaction template whose transactions begin and commit without a database.
     *
     * <p>Assumptions: a real template over a mock manager is used rather than a stub that simply runs the
     * callback, because the loader now depends on the transaction ENDING per chunk -- that is what bounds
     * its persistence context -- and a stub that never asked for a transaction would let a loader which
     * stopped opening one still pass. The manager returns a mock status, so the template begins, runs the
     * callback once and commits.</p>
     *
     * @return a transaction template that begins and commits without a database
     */
    private static TransactionTemplate chunkTransactions() {
        PlatformTransactionManager manager = mock(PlatformTransactionManager.class);
        // WHY : Assumptions: the stub is LENIENT because a malformed extract is refused before any
        //       transaction is opened -- the record reader raises while reading the first chunk, which
        //       happens outside the template -- so the cases about malformed input legitimately never ask
        //       this manager for anything. That ordering is a property worth keeping: a truncated file
        //       costs a message rather than a transaction and a connection.
        lenient().when(manager.getTransaction(any())).thenReturn(mock(TransactionStatus.class));
        TransactionTemplate template = new TransactionTemplate(manager);
        template.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
        return template;
    }

    /**
     * Loads both prefixed fixtures through the loader and returns what it reported.
     *
     * @return the loader's own counts
     */
    private LoadService.LoadOutcome loadBothFixtures() {
        return new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS)
                .load(open(PREFIXED_SUMMARY), open(PREFIXED_DETAIL));
    }

    /**
     * The loader loads both roots and all four children, and attributes each child to its own parent.
     *
     * <p>Assumptions: the child prefixes ALTERNATE between the two accounts in this fixture rather than
     * being grouped, which is what makes the attribution assertion meaningful. A loader that carried the
     * previous record's account forward would produce a plausible result on a grouped file and the wrong
     * one here.</p>
     *
     * <p>Assumptions: the roots are asserted to load in FILE order, which this fixture deliberately writes
     * highest account first. A loader that sorted its input would make this fixture and its ascending
     * sibling indistinguishable, which is the reason the pair exists.</p>
     */
    @Test
    @DisplayName("the loader loads two roots and four children, attributing each child to its own parent")
    void theLoaderLoadsBothFilesAndAttributesEveryChild() {
        givenSummariesRemember();
        givenDetailsRemember();

        LoadService.LoadOutcome outcome = loadBothFixtures();

        assertThat(outcome.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.inserted()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(outcome.alreadyPresent()).isZero();
        assertThat(outcome.inserted() + outcome.alreadyPresent())
                .as("a load that returns accounted for every record it read")
                .isEqualTo(outcome.read());

        assertThat(this.storedRoots)
                .extracting(PendingAuthSummary::getAccountId)
                .containsExactly(ACCOUNT_TWO, ACCOUNT_ONE);
        assertThat(this.storedChildren)
                .extracting(child -> child.getId().getAccountId())
                .as("each child's account comes from its own six-byte packed prefix")
                .containsExactly(ACCOUNT_ONE, ACCOUNT_TWO, ACCOUNT_ONE, ACCOUNT_TWO);
    }

    /**
     * Re-running a completed load inserts nothing and reports every record as already present.
     *
     * <p>Assumptions: this is the reference program's treatment of the duplicate-segment status -- its L256
     * to L258 and L329 to L331 report the duplicate and continue -- and it is what makes a partially
     * completed load safely re-runnable. Asserting that the stored state did not GROW is the important
     * half: an upsert would satisfy a count assertion while silently replacing a row an operator had since
     * corrected online.</p>
     */
    @Test
    @DisplayName("re-running a completed load inserts nothing and counts every record already present")
    void aRerunSkipsEveryRecordRatherThanOverwritingIt() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();

        LoadService.LoadOutcome rerun = loadBothFixtures();

        assertThat(rerun.read()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(rerun.inserted()).isZero();
        assertThat(rerun.alreadyPresent()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(this.storedRoots).hasSize(ROOT_COUNT);
        assertThat(this.storedChildren).hasSize(CHILD_COUNT);
    }


    /**
     * A row created by another writer between the read and the write is counted, never overwritten.
     *
     * <p>Purpose: this is the property the conflict-tolerant statement buys that no read can buy. The
     * chunk-wide presence query reads correctly inside the load's own transaction, so a root repeated
     * within one file is caught -- but it says nothing about a row another transaction committed since, and
     * a save through the persistence context would replace such a row in every column. Here the insert
     * refuses every record, which is what a concurrent creator leaves behind, and the loader must report
     * the records as already present without a second attempt of any kind.
     *
     * <p>Assumptions: the presence query is deliberately left UNSTUBBED, so it answers empty and every
     * record reaches the write looking absent. That is what puts the whole burden of this case on the
     * statement: stubbing the query to report the rows present would satisfy the same three counts through
     * the read path and prove nothing about the write.
     *
     * <p>Assumptions: the double refuses records the loader has NEVER seen, which is why this case is not
     * the re-run case above in a different order. The re-run exercises a duplicate the loader itself
     * created; this exercises one it cannot have known about, and only the second distinguishes an insert
     * that tolerates a conflict from a probe that happens to have been correct.
     *
     * <p>Assumptions: the inherited save is asserted never to be called at all. That assertion is the guard
     * against the failure returning, because the write path is one statement now and a later edit adding a
     * fallback save on the zero-row arm would restore the overwrite exactly.
     */
    @Test
    @DisplayName("a row created by another writer is counted as present and is never overwritten")
    void aRacedInsertIsCountedRatherThanOverwriting() {
        when(this.summaries.insertSummaryIfAbsent(any())).thenReturn(Integer.valueOf(0));

        LoadService.LoadOutcome outcome =
                new LoadService(this.summaries, this.details, chunkTransactions(),
                        LoadService.DEFAULT_MAX_RECORDS)
                        .loadSummaries(open(PREFIXED_SUMMARY));

        assertThat(outcome.read()).isEqualTo(ROOT_COUNT);
        assertThat(outcome.inserted()).isZero();
        assertThat(outcome.alreadyPresent()).isEqualTo(ROOT_COUNT);
        verify(this.summaries, never()).save(any());
        verify(this.summaries, never()).existsById(any());
    }

    /**
     * An extract holding more records than the configured ceiling is refused before any row is written.
     *
     * <p>Purpose: the read is bounded by a stated number rather than by the heap. This drives the ceiling
     * down to one record against a two-record file, so the refusal is reached on the second record, and
     * asserts both halves of the contract: the message names the property an operator would raise, and
     * nothing was written for the record that was read before the ceiling was hit.
     *
     * <p>Assumptions: the ceiling is asserted through the CONSTRUCTOR rather than through a property
     * source, because the binding is a constructor parameter and a test that went through a context would
     * assert the container's binding rather than this class's behaviour. The property NAME is asserted in
     * the message, which is what ties the two together -- the same constant is what the annotation binds.
     *
     * <p>Assumptions: the refusal is an {@link IllegalArgumentException} and not a bespoke type, matching
     * the remainder refusal beside it. Both say the same thing about the file -- that it is not the file
     * this reader was given -- and an operator's response to either is to correct the job definition.
     */
    @Test
    @DisplayName("an extract beyond the record ceiling is refused, naming the property to raise")
    void anExtractBeyondTheCeilingIsRefused() {
        LoadService bounded = new LoadService(this.summaries, this.details, chunkTransactions(), 1);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> bounded.loadSummaries(open(PREFIXED_SUMMARY)))
                .withMessageContaining("at most 1 records")
                .withMessageContaining(LoadService.MAX_RECORDS_PROPERTY);

        verify(this.summaries, never()).insertSummaryIfAbsent(any());
    }

    /**
     * A ceiling that admits nothing is refused when the loader is built, not when a load is attempted.
     *
     * <p>Purpose: a ceiling of zero or below would refuse every extract including an empty one, which is a
     * configuration mistake rather than a policy. Refusing at construction means a container configured
     * that way fails at startup, where the cause is obvious, instead of on the first load hours later.
     *
     * <p>Assumptions: both zero and a negative value are exercised, because the check is a single
     * comparison and a later edit narrowing it to equality with zero would pass a test that tried only
     * zero. The refusal names the property so that an operator reads the name to correct rather than the
     * name of a constructor parameter they cannot see.
     */
    @Test
    @DisplayName("a ceiling that admits no records is refused when the loader is built")
    void aCeilingAdmittingNothingIsRefusedAtConstruction() {
        for (int ceiling : new int[] {0, -1}) {
            assertThatExceptionOfType(IllegalArgumentException.class)
                    .as("a ceiling of %d admits no extract at all", ceiling)
                    .isThrownBy(() -> new LoadService(this.summaries, this.details, chunkTransactions(), ceiling))
                    .withMessageContaining(LoadService.MAX_RECORDS_PROPERTY)
                    .withMessageContaining(String.valueOf(ceiling));
        }
    }

    /**
     * A condition that is neither success nor a duplicate propagates rather than being counted.
     *
     * <p>Assumptions: this is the other half of the idempotence ruling and it is asserted separately,
     * because tolerating a duplicate and swallowing everything else are the two readings of
     * {@code cbl/PAUDBLOD.CBL} L256 to L262 that a test has to tell apart. Its L256 to L258 report the
     * duplicate status and continue; its L259 to L262 reach the abend for every other status, and L332 to
     * L336 do the same for a child. A loader that caught broadly would satisfy the re-run case above and
     * still report a successful load having stored less than it read.</p>
     */
    @Test
    @DisplayName("a store failure that is not a duplicate propagates instead of being counted as a skip")
    void aFailureThatIsNotADuplicatePropagates() {
        when(this.summaries.findExistingAccountIds(any())).thenReturn(List.of());
        when(this.summaries.insertSummaryIfAbsent(any()))
                .thenThrow(new IllegalStateException("store unavailable"));

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(IllegalStateException.class)
                .isThrownBy(() -> loader.loadSummaries(open(PREFIXED_SUMMARY)))
                .withMessage("store unavailable");
    }

    /**
     * Divergence D-C: a child whose parent summary is absent is refused, carrying the account in typed
     * form and not in its message.
     *
     * <p>Assumptions: this asserts divergence D-C, recorded on {@link LoadService} and registered in
     * {@code docs/architecture/cobol-to-service-traceability.md}. The reference program passes such a child
     * over in silence: its insert sits inside the branch a successful parent position opens at
     * {@code cbl/PAUDBLOD.CBL} L305, and a failed position falls past the insert AND past the abend test
     * nested inside that branch, reaching L315 without inserting or reporting. The target refuses
     * instead.</p>
     *
     * <p>Assumptions: the assertion is on the ACCOUNT the refusal carries and not merely on its type,
     * because carrying the key is the whole point of the divergence. A refusal that named no account would
     * leave an operator with exactly what the reference program leaves them -- the knowledge that something
     * was wrong and no way to find which record -- so a test that accepted any exception would pass for an
     * implementation that had recovered none of the value. The key is read through the typed ACCESSOR,
     * which is where it lives.</p>
     *
     * <p>Refactoring Rationale: this case additionally asserted that the account identifier appears IN the
     * refusal's message, and that assertion has been inverted to assert it does not. It was pinning a
     * violation of the binding observability contract, which names account identifiers among the values a
     * durable diagnostic may not hold and requires them omitted rather than shortened -- and a throwable's
     * message is such a diagnostic, because whatever catches it writes it and an orchestrator surfaces it
     * with the failed task. The divergence this case defends is unaffected: what it exists to prove is
     * that the refusal LOCATES the failure where the reference program loses it, and the two accessors
     * asserted above carry that. Inverting rather than deleting the assertion is deliberate, because the
     * property is now the opposite one and it is worth holding: an implementation that reinstated the
     * interpolation would fail here rather than pass silently.</p>
     *
     * <p>Refactoring Rationale: this case ASSERTED that the account appeared in the exception message, and
     * it now asserts the opposite while keeping the assertion on the typed accessor. The message reaches
     * the log through a stack trace whether or not the raising site intended that, so the old assertion
     * required the identifier to be logged for every unresolved child -- a test that held the disclosure
     * in place. The value an operator needs is still carried, and it is carried where a caller has to ask
     * for it. Both halves are asserted, because an implementation that dropped the accessor as well would
     * satisfy a bare absence assertion.</p>
     *
     * <p>Assumptions: the case also asserts that NOTHING was written. The refusal is raised inside the same
     * transaction the load runs in, so on a real store the rollback discards the earlier records; the
     * double cannot roll back, so the assertion is made directly against the save.</p>
     */
    @Test
    @DisplayName("D-C: a child whose parent summary is absent is refused, naming the account")
    void anUnresolvableParentIsRefusedAndNamesTheAccount() {
        when(this.summaries.findExistingAccountIds(any())).thenReturn(List.of());

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)))
                .satisfies(refused -> {
                    assertThat(refused.getAccountId())
                            .as("the first prefixed record of this fixture names the lower account")
                            .isEqualTo(ACCOUNT_ONE);
                    assertThat(refused.getRecordOrdinal())
                            .as("the refusal locates the record, one-based, so the file can be read at it")
                            .isEqualTo(1);
                    // WHY : Assumptions: the message is asserted to name the ORDINAL and NOT the
                    //   account. Both halves are needed: without the first the message could be left
                    //   with nothing an operator can act on, and without the second an implementation
                    //   could reinstate the prohibited value while still satisfying the first.
                    assertThat(refused)
                            .as("the message must locate the record it refused")
                            .hasMessageContaining("record 1");
                    assertThat(refused.getMessage())
                            .as("an account identifier may not appear in a durable diagnostic, and a"
                                    + " throwable message is one")
                            .doesNotContain(String.valueOf(ACCOUNT_ONE));
                });

        verify(this.details, never()).insertDetailIfAbsent(any());
    }

    /**
     * Divergence D-C: the refusal stops the pass rather than continuing through the remaining records.
     *
     * <p>Assumptions: this is asserted separately from the case above because the two properties are
     * independent, and an implementation can have one without the other. A loader that logged the account
     * and then carried on would produce a refusal carrying the right key and still lose the remaining
     * records, which is the outcome the divergence exists to prevent. What fixes the count at one is that
     * the parent check precedes the save for every record and raises on the first failure: the fixture
     * holds four children whose parents are all absent, and exactly one is reached.</p>
     */
    @Test
    @DisplayName("D-C: the refusal ends the pass at the first unresolvable record")
    void anUnresolvableParentEndsThePass() {
        when(this.summaries.findExistingAccountIds(any())).thenReturn(List.of());

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)));

        // WHY : Refactoring Rationale: the assertion counts the BATCHED presence query rather than the
        //       per-record probe, and one call is now the whole first chunk rather than one record. That
        //       is the property the change was made for: the number of statements a load issues is a
        //       function of its chunk count, not of its record count.
        verify(this.summaries, times(1)).findExistingAccountIds(any());
        verify(this.details, never()).findExistingIds(any());
        // WHY : Assumptions: the write named here is the conflict-tolerant insert the loader actually
        //       issues. Naming the inherited save instead would forbid a call the loader never makes on
        //       any path, and an absence assertion aimed at an unused method cannot fail.
        verify(this.details, never()).insertDetailIfAbsent(any());
    }

    /**
     * A child record whose six-byte prefix does not decode is refused, naming the record.
     *
     * <p>Assumptions: this is the second condition {@code cbl/PAUDBLOD.CBL} passes over. Its
     * {@code 3000-READ-CHILD-SEG-FILE} guards the insert with {@code IF ROOT-SEG-KEY IS NUMERIC} at
     * <strong>L275</strong> and supplies no {@code ELSE}, so a prefix failing that test takes the record
     * out of the run with no message at all.</p>
     *
     * <p>Assumptions: the corrupted prefix is built by writing a byte whose low nibble is a DIGIT into the
     * sign position, which is the last of the six. A packed field's final nibble is its sign, so a digit
     * there is exactly what the reference numeric test rejects, and it is a corruption the length check
     * cannot catch -- the record is still 206 bytes.</p>
     *
     * <p>Assumptions: the refusal is asserted to name the ordinal and NOT an account, because an
     * undecodable prefix names none. That asymmetry with D-C is the reason the two refusals are separate
     * types rather than one carrying an optional key.</p>
     */
    @Test
    @DisplayName("a child record whose packed prefix does not decode is refused, naming the record")
    void anUndecodablePrefixIsRefused() {
        byte[] corrupted = bytes(PREFIXED_DETAIL).clone();
        int signByte = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength() - 1;
        corrupted[signByte] = (byte) 0x05;

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(LoadService.MalformedParentKeyException.class)
                .isThrownBy(() -> loader.loadDetails(new ByteArrayInputStream(corrupted)))
                .satisfies(refused -> assertThat(refused.getRecordOrdinal()).isEqualTo(1))
                .withMessageContaining("record 1")
                .havingCause()
                .isInstanceOf(IllegalArgumentException.class);

        verify(this.details, never()).insertDetailIfAbsent(any());
    }

    /**
     * A record whose fraud position is outside the column's domain is refused, and nothing is written.
     *
     * <p>Purpose: this is the loader-side half of the fraud-domain contract. Its engine-side half,
     * {@code fixtures.PendingAuthFraudDomainRepositoryIT}, proves the check constraint refuses the same
     * image when it is written through plain JDBC; this case proves the LOADER never presents it, because
     * the mapper it decodes through refuses the record first.
     *
     * <p>Refactoring Rationale: the mapper used to drop an out-of-domain position SILENTLY, leaving the
     * entity unmarked. That made this the most dangerous shape a defect can take: the row loaded clean,
     * the constraint never saw the offending byte because the entity presented null, and an authorization
     * the source said had been marked arrived in the target unmarked. The extract is the second writer of
     * that column, so an invariant asserted only in the marking flow bound nothing here.
     *
     * <p>Assumptions: the record is SYNTHESISED from a valid prefix and the out-of-domain segment rather
     * than committed as a third fixture. The prefix of the committed detail extract is a well-formed
     * packed account identifier, so pairing it with that segment isolates the fraud byte as the only
     * thing wrong with the record -- which is what {@link #theSameRecordLoadsOnceItsFraudPositionIsInDomain()}
     * then proves by changing that byte alone and watching the same record load.
     *
     * <p>Assumptions: the constrained byte's position is READ from the layout registry rather than written
     * as a literal, so a registry that moved the field would relocate this case with it rather than
     * leaving it asserting about a neighbour.
     *
     * <p>This test takes no parameter and returns no value.</p>
     */
    @Test
    @DisplayName("a record whose fraud position is out of domain is refused and nothing is written")
    void anOutOfDomainFraudPositionIsRefusedByTheLoader() {
        byte[] record = prefixedRecordCarrying(bytes(FRAUD_POSITION_OUT_OF_DOMAIN));
        assertThat(record[prefixWidth() + fraudOffset()])
                .as("the synthesised record carries the fixture's out-of-domain position")
                .isEqualTo((byte) 'Y');

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(LoadService.MalformedSegmentException.class)
                .isThrownBy(() -> loader.loadDetails(new ByteArrayInputStream(record)))
                .satisfies(refused -> assertThat(refused.getRecordOrdinal()).isEqualTo(1))
                .withMessageContaining("record 1")
                .havingCause()
                .withMessageContaining("'Y'")
                .withMessageContaining("outside the domain");

        verify(this.details, never()).insertDetailIfAbsent(any());
        assertThat(this.storedChildren)
                .as("the refusal precedes every write, so no authorization was stored")
                .isEmpty();
    }

    /**
     * The same record loads once its fraud position holds one of the two marking characters.
     *
     * <p>Purpose: this is what makes the refusal above discriminate. Without it, a case asserting that a
     * record is refused proves only that SOMETHING about the record is unacceptable, and would stay green
     * if the loader had begun refusing every record of this fixture for an unrelated reason.
     *
     * <p>Assumptions: the byte is changed to the reported marking and nothing else is touched, and the
     * fixture's report date is already valid at its declared width, so the marking applies. The stored
     * authorization is then read back to confirm the position SURVIVED the load rather than merely
     * failing to refuse it -- which is the state the old behaviour produced.
     *
     * <p>Assumptions: the parent summary is loaded from the committed summary extract first, because the
     * loader refuses a child naming an account with no summary row. That ordering is the load's own
     * contract and not a fixture convenience.
     *
     * <p>This test takes no parameter and returns no value.</p>
     */
    @Test
    @DisplayName("the same record loads once its fraud position is one of the two marking characters")
    void theSameRecordLoadsOnceItsFraudPositionIsInDomain() {
        givenSummariesRemember();
        givenDetailsRemember();
        byte[] record = prefixedRecordCarrying(bytes(FRAUD_POSITION_OUT_OF_DOMAIN));
        record[prefixWidth() + fraudOffset()] = (byte) PendingAuthDetail.FRAUD_REPORTED.charAt(0);

        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);
        loader.loadSummaries(open(PREFIXED_SUMMARY));
        LoadService.LoadOutcome outcome =
                loader.loadDetails(new ByteArrayInputStream(record));

        assertThat(outcome.inserted())
                .as("the record differs from the refused one in one byte and that byte is now in domain")
                .isEqualTo(1);
        assertThat(this.storedChildren).hasSize(1);
        assertThat(this.storedChildren.get(0).getAuthFraud())
                .as("the marking survives the load rather than being normalised to unmarked")
                .isEqualTo(PendingAuthDetail.FRAUD_REPORTED);
        assertThat(this.storedChildren.get(0).getFraudReportDate())
                .as("the report date accompanying the marking is carried with it")
                .isNotNull();
    }

    /**
     * The six-byte prefix is decoded as PACKED decimal, and a text reading of it yields another number.
     *
     * <p>Assumptions: this asserts the prefix's storage regime rather than the loader's plumbing, because a
     * reader that took those six bytes as characters would not fail -- it would attribute the child to a
     * different account, which is a wrong answer rather than an error. The case therefore states both
     * readings and asserts they disagree, so an implementation that switched to a text read would fail here
     * instead of loading plausible rows under the wrong account.</p>
     *
     * <p>Assumptions: the packed reading is the one the reference declaration fixes.
     * {@code cbl/PAUDBLOD.CBL} <strong>L47</strong> declares the prefix
     * {@code 05 ROOT-SEG-KEY PIC S9(11) COMP-3}, six bytes carrying two digits each and a sign nibble.</p>
     */
    @Test
    @DisplayName("the packed prefix decodes to an account a text reading of the same bytes does not give")
    void theParentPrefixIsReadAsPackedDecimalAndNotAsText() {
        byte[] first = Arrays.copyOfRange(bytes(PREFIXED_DETAIL), 0,
                PendingAuthDetailMapper.unloadRecordLength());
        int prefixWidth = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
        String asText = new String(Arrays.copyOfRange(first, 0, prefixWidth),
                StandardCharsets.ISO_8859_1);

        assertThat(PendingAuthDetailMapper.unloadedAccountId(first))
                .as("the packed reading is the account the fixture was written for")
                .isEqualTo(ACCOUNT_ONE);
        assertThat(asText.trim())
                .as("the same six bytes read as characters are not the digits of that account")
                .isNotEqualTo(String.valueOf(ACCOUNT_ONE));

        givenSummariesRemember();
        givenDetailsRemember();
        // WHY : Assumptions: the parent is seeded through the conflict-tolerant insert, because that is
        //       the only write the double answers -- the loader writes each fresh row with a statement
        //       that tolerates a conflict rather than through the persistence context. Seeding through
        //       either save would silently not be remembered, and this case would then fail for a missing
        //       parent rather than for the packed reading it is actually about.
        this.summaries.insertSummaryIfAbsent(PendingAuthSummaryMapper.fromExtractRecord(
                Arrays.copyOfRange(bytes(PREFIXED_SUMMARY),
                        PendingAuthSummaryMapper.unloadRecordLength(),
                        ROOT_COUNT * PendingAuthSummaryMapper.unloadRecordLength())));

        LoadService.LoadOutcome outcome = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS)
                .loadDetails(new ByteArrayInputStream(first));

        assertThat(outcome.inserted()).isEqualTo(1);
        assertThat(this.storedChildren)
                .singleElement()
                .extracting(child -> child.getId().getAccountId())
                .isEqualTo(ACCOUNT_ONE);
    }

    /**
     * Loading the child file before the summary file is refused, which is why the two passes are ordered.
     *
     * <p>Assumptions: {@code MAIN-PARA} at {@code cbl/PAUDBLOD.CBL} <strong>L169 to L187</strong> runs its
     * root loop at L177 to L178 to exhaustion before its child loop at L180 to L181 begins, and this case
     * asserts the ordering is load-bearing rather than incidental. Reversing the two passes refuses the
     * first child, because no parent has been written yet -- so a loader that interleaved them, or that
     * ran the child pass first, would fail here rather than silently attributing children to rows that do
     * not exist.</p>
     */
    @Test
    @DisplayName("the child pass depends on the root pass having run first, so the order is asserted")
    void theTwoPassesRunInTheReferenceOrder() {
        givenSummariesRemember();
        givenDetailsRemember();
        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(LoadService.UnresolvedParentException.class)
                .as("the child pass alone finds no parent, because the root pass writes them")
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_DETAIL)));

        LoadService.LoadOutcome ordered =
                loader.load(open(PREFIXED_SUMMARY), open(PREFIXED_DETAIL));

        assertThat(ordered.inserted()).isEqualTo(ROOT_COUNT + CHILD_COUNT);
        assertThat(this.storedRoots).hasSize(ROOT_COUNT);
        assertThat(this.storedChildren).hasSize(CHILD_COUNT);
    }

    /**
     * A stream whose length is not a whole number of records is refused before any row is written.
     *
     * <p>Assumptions: a remainder means the file was produced against a different layout or was truncated
     * in transit, and every offset after the first short record would then be wrong -- so the alternative
     * to refusing is loading plausible values into the wrong columns. The message names the stride, because
     * the likeliest cause is one of these two files being handed to the other's reader: the strides are
     * 100 and 206.</p>
     */
    @Test
    @DisplayName("a stream that is not a whole number of records is refused, naming the stride")
    void aPartialRecordIsRefused() {
        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .as("the 206-byte child file divided by the 100-byte root stride leaves a remainder")
                .isThrownBy(() -> loader.loadSummaries(open(PREFIXED_DETAIL)))
                .withMessageContaining("must hold a whole number of 100-byte records");

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> loader.loadDetails(open(PREFIXED_SUMMARY)))
                .withMessageContaining("must hold a whole number of 206-byte records");

        verify(this.summaries, never()).insertSummaryIfAbsent(any());
        verify(this.details, never()).insertDetailIfAbsent(any());
    }

    /**
     * A truncated record ends the pass rather than leaving the reader turning on the same bytes.
     *
     * <p>Assumptions: this asserts the removal of the non-termination hazard in the reference read loops.
     * Both end only when a status of {@code '10'} sets an end flag -- {@code END-ROOT-SEG-FILE} at
     * {@code cbl/PAUDBLOD.CBL} L233 and {@code END-CHILD-SEG-FILE} at its L285 -- and each has one further
     * branch that sets no flag and does not abend, at <strong>L235</strong> and <strong>L287</strong>
     * respectively. Under the {@code PERFORM ... UNTIL} at L178 and L181, reaching that branch leaves both
     * the flag and the file position unchanged, so the loop reads the same condition again.</p>
     *
     * <p>Assumptions: the case is expressed as a bounded assertion rather than as a plain call, because the
     * property under test is TERMINATION and a test that merely called the method would hang rather than
     * fail if the property were lost. Failing inside a timeout is the difference between a red build and a
     * stuck one.</p>
     */
    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    @DisplayName("a truncated final record terminates the pass instead of being read repeatedly")
    void aTruncatedRecordTerminatesRatherThanLooping() {
        byte[] whole = bytes(PREFIXED_SUMMARY);
        byte[] truncated = Arrays.copyOfRange(whole, 0, whole.length - 1);
        LoadService loader = new LoadService(this.summaries, this.details, chunkTransactions(),
                LoadService.DEFAULT_MAX_RECORDS);

        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> loader.loadSummaries(new ByteArrayInputStream(truncated)))
                .withMessageContaining("must hold a whole number of 100-byte records");

        verify(this.summaries, never()).insertSummaryIfAbsent(any());
    }

    /**
     * A hierarchical unload of the loaded rows reproduces the two fixture files byte for byte.
     *
     * <p>Assumptions: the circuit is closed rather than each direction being checked against a
     * hand-written expectation. Decoding and re-encoding through independent code paths and getting the
     * original bytes back is what detects an offset error in a packed money field, which a hand-written
     * expectation authored from the same misreading would not.</p>
     *
     * <p>Assumptions: the root file is reproduced in ASCENDING account order, which is why the ascending
     * sibling fixture is the comparison target and not the descending one this case loaded from. The unload
     * walks the table by key, so its output order is the table's and not the input file's; the two fixtures
     * exist as a pair precisely so that ordering is asserted rather than assumed, and a service that echoed
     * its input would fail here.</p>
     */
    @Test
    @DisplayName("a hierarchical unload of the loaded rows reproduces both fixture files byte for byte")
    void theHierarchicalUnloadReproducesTheFixtures() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        UnloadService.UnloadOutcome outcome = new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.PREFIXED, roots, children);

        assertThat(outcome.rootsWritten()).isEqualTo(ROOT_COUNT);
        assertThat(outcome.childrenWritten()).isEqualTo(CHILD_COUNT);
        assertThat(roots.toByteArray())
                .as("the unload emits roots in ascending key order, whatever order they were loaded in")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.toByteArray()).isEqualTo(prefixedChildrenGroupedByAccount());
    }

    /**
     * A sequential unload writes the same roots and BARE child segments, six bytes shorter each.
     *
     * <p>Assumptions: the two forms differ only in the child record, which is what lets one service serve
     * both reference programs. {@code cbl/DBUNLDGS.CBL} passes the segment alone to both of its inserts at
     * L302 to L304 and L321 to L323, so its child stride is 200 where the hierarchical form's is 206. The
     * root file is asserted IDENTICAL between the two forms, because both reference programs move the whole
     * hundred-byte root with no prefix.</p>
     */
    @Test
    @DisplayName("a sequential unload writes the same roots and bare 200-byte child segments")
    void theSequentialUnloadOmitsTheChildPrefix() {
        givenSummariesRemember();
        givenDetailsRemember();
        loadBothFixtures();
        givenWalksAnswerFromStoredRows();

        ByteArrayOutputStream roots = new ByteArrayOutputStream();
        ByteArrayOutputStream children = new ByteArrayOutputStream();
        new UnloadService(this.summaries, this.details)
                .unload(UnloadService.UnloadForm.SEQUENTIAL, roots, children);

        assertThat(roots.toByteArray())
                .as("the root record is the same in both forms")
                .isEqualTo(bytes(SEQUENTIAL_SUMMARY));
        assertThat(children.size())
                .as("four bare segments of 200 against four prefixed records of 206")
                .isEqualTo(CHILD_COUNT * PendingAuthDetailMapper.segmentLength())
                .isNotEqualTo(CHILD_COUNT * PendingAuthDetailMapper.unloadRecordLength());
        assertThat(children.toByteArray()).isEqualTo(bareChildrenGroupedByAccount());
    }

    /**
     * Confirms the declared strides are the geometry the fixtures were written to.
     *
     * <p>Assumptions: this guards the whole class. Every assertion above divides a fixture by a stride the
     * mappers declare, so a stride that drifted from the fixtures would turn every case here into a decode
     * of the wrong bytes -- and several would still pass, because a file divided by a wrong-but-factor
     * stride yields records that decode to something.</p>
     */
    @Test
    @DisplayName("the fixtures divide exactly by the strides the mappers declare")
    void theFixtureGeometryMatchesTheDeclaredStrides() {
        assertThat(PendingAuthSummaryMapper.unloadRecordLength()).isEqualTo(100);
        assertThat(PendingAuthDetailMapper.segmentLength()).isEqualTo(200);
        assertThat(PendingAuthDetailMapper.unloadRecordLength()).isEqualTo(206);

        assertThat(bytes(PREFIXED_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(SEQUENTIAL_SUMMARY)).hasSize(ROOT_COUNT * 100);
        assertThat(bytes(PREFIXED_DETAIL)).hasSize(CHILD_COUNT * 206);
        assertThat(bytes(SEQUENTIAL_DETAIL)).hasSize(CHILD_COUNT * 200);
    }

    /**
     * Answers the two repository walk methods from the rows the doubles have accepted.
     *
     * <p>Assumptions: the answers reproduce the ORDER the two query methods declare -- ascending account
     * for the outer walk, newest first within one account for the inner one -- because that order is the
     * contract the unload depends on and a double that returned insertion order would let a broken walk
     * pass. The page LIMIT is honoured for the same class of reason: the service decides a walk is
     * finished by receiving a page shorter than it asked for, so a double that ignored the limit would be
     * defining that signal rather than exercising it.</p>
     */
    private void givenWalksAnswerFromStoredRows() {
        when(this.summaries.findByAccountIdGreaterThanOrderByAccountIdAsc(any(), any()))
                .thenAnswer(invocation -> {
                    long after = invocation.<Long>getArgument(0).longValue();
                    Limit limit = invocation.getArgument(1);
                    return this.storedRoots.stream()
                            .filter(root -> root.getAccountId().longValue() > after)
                            .sorted((left, right) ->
                                    Long.compare(left.getAccountId(), right.getAccountId()))
                            .limit(limit.max())
                            .toList();
                });
        when(this.details.findByIdAccountIdOrderByIdAuthDateDescIdAuthTimeDesc(any()))
                .thenAnswer(invocation -> {
                    Long accountId = invocation.getArgument(0);
                    return this.storedChildren.stream()
                            .filter(child -> accountId.equals(child.getId().getAccountId()))
                            .sorted(AuthorizationExtractRoundTripTest::newestFirst)
                            .toList();
                });
    }

    /**
     * Rebuilds the expected prefixed child file in the order the reference walk emits.
     *
     * <p>Assumptions: the expectation is the fixture's own four records REORDERED, never re-encoded. The
     * fixture writes the two accounts alternating, and an unload writes one account's children before
     * moving to the next, so the two files hold the same four records in different orders. Reordering the
     * committed bytes keeps the fixture as the oracle for their CONTENT while letting the case assert the
     * order the walk produces.</p>
     *
     * <p>Assumptions: within one account the order is the RAW eight-byte key ascending, compared as
     * unsigned bytes, and that is derived from the reference declaration rather than from this migration's
     * decode. {@code ims/DBPAUTP0.dbd} L37 declares the child's unique sequence field over those eight
     * bytes as {@code TYPE=C}, so IMS sequences twins by byte-wise comparison of the stored NINES
     * COMPLEMENT -- and ascending on a complement is newest-first on the value. Stating the expectation
     * this way rather than by sorting the decoded keys is deliberate: it keeps the ordering expectation
     * independent of the decode the unload itself performs, so a decode that inverted the complement would
     * fail here instead of moving the expectation with it.</p>
     *
     * @return the four committed 206-byte records, account one's pair first and each pair newest first
     */
    private static byte[] prefixedChildrenGroupedByAccount() {
        return regroup(bytes(PREFIXED_DETAIL), PendingAuthDetailMapper.unloadRecordLength(),
                PendingAuthDetailMapper::unloadedAccountId);
    }

    /**
     * Compares two child records by the raw complement key IMS sequences twins on.
     *
     * @param left the first record, prefixed
     * @param right the second record, prefixed
     * @return a negative value when {@code left} sorts first in complement byte order
     */
    private static int byRawComplementKey(byte[] left, byte[] right) {
        int keyOffset = PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
        int keyEnd = keyOffset + RAW_KEY_WIDTH;
        return Arrays.compareUnsigned(Arrays.copyOfRange(left, keyOffset, keyEnd),
                Arrays.copyOfRange(right, keyOffset, keyEnd));
    }

    /**
     * Rebuilds the expected bare child file, with the four segments grouped by account.
     *
     * <p>Assumptions: the segments come from the PREFIXED fixture with the prefix stripped, and not from
     * the sequential fixture. The sequential fixture's own records carry no account at all, so grouping
     * them by account is not something their bytes can support; stripping the prefix from the attributable
     * file is the only way to state the expectation without re-encoding anything.</p>
     *
     * @return the four committed segments with their prefixes removed, account one's pair first
     */
    private static byte[] bareChildrenGroupedByAccount() {
        byte[] grouped = prefixedChildrenGroupedByAccount();
        int stride = PendingAuthDetailMapper.unloadRecordLength();
        ByteArrayOutputStream bare = new ByteArrayOutputStream();
        for (int offset = 0; offset < grouped.length; offset += stride) {
            byte[] segment = PendingAuthDetailMapper.unloadedSegment(
                    Arrays.copyOfRange(grouped, offset, offset + stride));
            bare.write(segment, 0, segment.length);
        }
        return bare.toByteArray();
    }

    /**
     * Groups fixed-length records by a key read from each, preserving order within each group.
     *
     * @param image the whole fixture
     * @param stride the declared record length
     * @param keyOf reads the grouping key from one record
     * @return the same records concatenated, grouped by ascending key
     */
    private static byte[] regroup(byte[] image, int stride, Function<byte[], Long> keyOf) {
        Map<Long, List<byte[]>> grouped = new LinkedHashMap<>();
        for (int offset = 0; offset < image.length; offset += stride) {
            byte[] record = Arrays.copyOfRange(image, offset, offset + stride);
            grouped.computeIfAbsent(keyOf.apply(record), key -> new ArrayList<>()).add(record);
        }
        ByteArrayOutputStream ordered = new ByteArrayOutputStream();
        grouped.keySet().stream().sorted().forEach(key -> {
            List<byte[]> beneath = new ArrayList<>(grouped.get(key));
            beneath.sort(AuthorizationExtractRoundTripTest::byRawComplementKey);
            beneath.forEach(record -> ordered.write(record, 0, record.length));
        });
        return ordered.toByteArray();
    }

    /**
     * Orders two authorizations newest first, which is the order the inner walk declares.
     *
     * @param left the first authorization
     * @param right the second authorization
     * @return a negative value when {@code left} is newer, positive when older, zero when equal
     */
    private static int newestFirst(PendingAuthDetail left, PendingAuthDetail right) {
        PendingAuthDetailKey leftKey = left.getId();
        PendingAuthDetailKey rightKey = right.getId();
        int byDate = Integer.compare(rightKey.getAuthDate(), leftKey.getAuthDate());
        return byDate != 0 ? byDate
                : Integer.compare(rightKey.getAuthTime(), leftKey.getAuthTime());
    }

    /**
     * Builds one prefixed child record from a valid prefix and the segment handed in.
     *
     * <p>Assumptions: the prefix is taken from the committed detail extract rather than encoded here, so
     * this helper cannot disagree with the loader about the packed representation of an account
     * identifier. What it varies is the segment alone.
     *
     * @param segment one detail segment image of exactly the declared segment length
     * @return a newly allocated record of exactly the declared unload stride
     */
    private static byte[] prefixedRecordCarrying(byte[] segment) {
        byte[] record = Arrays.copyOf(bytes(PREFIXED_DETAIL),
                PendingAuthDetailMapper.unloadRecordLength());
        System.arraycopy(segment, 0, record, prefixWidth(), segment.length);
        return record;
    }

    /**
     * The width of the packed parent-key prefix each unload record carries.
     *
     * @return the stride less the segment length, which is the prefix
     */
    private static int prefixWidth() {
        return PendingAuthDetailMapper.unloadRecordLength()
                - PendingAuthDetailMapper.segmentLength();
    }

    /**
     * The zero-based offset of the fraud position inside one segment, read from the layout registry.
     *
     * @return the declared start of the one-byte fraud field
     * @throws AssertionError if the registry holds no field of that name, which would mean this case is
     *     asserting about a layout that no longer declares the field it is named for
     */
    private static int fraudOffset() {
        return CopybookLayout.layout("PAUTDTL").fields().stream()
                .filter(field -> FRAUD_FIELD.equals(field.name()))
                .findFirst()
                .orElseThrow(() -> new AssertionError(
                        "the PAUTDTL layout declares no field named " + FRAUD_FIELD))
                .start();
    }

    /**
     * Reads a fixture from the test class path as a stream.
     *
     * @param name the file name inside the fixture directory
     * @return a stream over every byte of the file
     */
    private static InputStream open(String name) {
        return new ByteArrayInputStream(bytes(name));
    }

    /**
     * Reads a fixture from the test class path in full.
     *
     * @param name the file name inside the fixture directory
     * @return every byte of the file, unmodified
     * @throws AssertionError if the fixture is absent from the class path
     * @throws UncheckedIOException if the stream cannot be read
     */
    private static byte[] bytes(String name) {
        try (InputStream stream =
                AuthorizationExtractRoundTripTest.class.getResourceAsStream(ROOT + name)) {
            if (stream == null) {
                throw new AssertionError("fixture " + name + " is not on the test class path");
            }
            return stream.readAllBytes();
        } catch (IOException failure) {
            throw new UncheckedIOException("fixture " + name + " could not be read", failure);
        }
    }
}
