package com.carddemo.transaction.repository;

import com.carddemo.transaction.domain.TransactionReject;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * The sole data-access port onto {@code ledger.transaction_rejects}, the posting reject stream of the
 * LEDGER bounded context.
 *
 * <p>Every relational equivalent of a file operation the baseline issues against its {@code DALYREJS}
 * dataset is inherited into this interface, and none is expressed anywhere else in this module. The
 * package charter beside this file makes that the boundary: no controller, service, mapper, DTO or
 * domain type may hold a query against this table. The 430-byte record layout, the reason-code
 * register and the retention policy are set out in
 * {@code docs/architecture/data-model-and-schema-mapping.md}; the physical contract is
 * {@code db/migration/V1__ledger.sql}.
 *
 * <p>Alternatives Considered: decomposing the retained 350-byte image into the thirteen typed columns
 * {@code app/cpy/CVTRA06Y.cpy} would yield, so the rejected values were queryable. Rejected, because a
 * reject entry exists to reproduce exactly what arrived -- a re-drive replays the original bytes rather
 * than a re-serialisation of the parse that may itself be what failed -- and the rejected values are by
 * definition the ones validation would not accept, so typed columns would either refuse the input or
 * normalise the evidence away. {@code app/cbl/CBTRN02C.cbl} line 447 moves the payload wholesale for
 * the same reason. No member here parses, splits or reinterprets that image.
 *
 * <p>Alternatives Considered: modelling the reason as a closed Java type whose constants are exactly
 * the codes the baseline is observed to set. Rejected, because the source field is {@code PIC 9(04)} at
 * {@code app/cbl/CBTRN02C.cbl} line 181, so its declared domain is every value four digits admit and
 * the observed codes are not a closed set. Such a type would refuse an unmodelled code at the
 * persistence boundary, which for a stream whose purpose is to retain what happened turns a recordable
 * outcome into an unrecordable one.
 *
 * <p>Alternatives Considered: a finder by reason code, by the card number the retained image carries,
 * by description, or a key-ordered administrative browse. All four are rejected as surface no baseline
 * path asks for: the {@code SELECT} at {@code app/cbl/CBTRN02C.cbl} lines 46 to 49 declares
 * {@code ORGANIZATION IS SEQUENTIAL} with no {@code RECORD KEY}, line 293 opens it {@code OUTPUT}
 * rather than {@code I-O}, and no {@code READ} is issued against it anywhere. There is no read path to
 * transcribe, so none is invented, and what this interface contributes is the inherited write path.
 *
 * <p>Refactoring Rationale: no member returns a tally of rejected records. The baseline keeps that
 * tally in the job rather than in the dataset -- {@code WS-REJECT-COUNT} is incremented at
 * {@code app/cbl/CBTRN02C.cbl} line 214 and graded into the return code at lines 229 and 230 -- and the
 * migrated job keeps it in the same place. An aggregate declared here would compute a different number
 * as soon as more than one run's entries share the table, and a caller could not tell which of the two
 * answered the question it asked.
 *
 * <p>Assumptions: the identity is the reject-event ordinal {@code reject_seq}, generated by the
 * database and keyed by constraint {@code pk_transaction_rejects}. It corresponds to no field of the
 * 430-byte layout, because the baseline stream has no key of its own. What the addition buys is that
 * the ordinal identifies the reject EVENT while leaving the retained image free to repeat, so the same
 * record rejected on two runs stays two separately addressable entries -- which
 * {@code app/jcl/DALYREJS.jcl} lines 24 to 28 keep five generations of. No uniqueness is asserted over
 * the image, and none may be, because that would turn a faithful append into a constraint violation.
 *
 * <p>Refactoring Rationale: this interface has NO caller inside this module, and an earlier revision of
 * this note claimed it had one in the posting write path. That claim is not sustainable alongside the
 * cross-schema grant: the posting job reaches this table through a narrowly scoped {@code GRANT} and
 * maps it through its own entity in the batch deployable, which is what keeps the posting unit of work
 * one atomic commit across the three writes at {@code app/cbl/CBTRN02C.cbl} lines 440 to 442. What the
 * interface is for is stated positively instead: this module owns the {@code ledger} schema, so it is
 * the module whose migration declares this table and whose entity is the single source of its column
 * names, widths, nullability and key, and the repository is what lets this module's integration test
 * assert that physical contract against a live database. Deleting it would leave an owned table with a
 * declared entity and no way to exercise it from the module that owns it.
 *
 * <p>Assumptions: generation retention is an infrastructure concern and is deliberately not a member
 * here. The {@code LIMIT(5) SCRATCH} retention at {@code app/jcl/DALYREJS.jcl} lines 24 to 28 is
 * carried in the target by object-store lifecycle configuration declared in the infrastructure package.
 * A purge or bulk-delete member would put a retention policy in application code, where it could be
 * invoked out of band and would have to be kept in step with the lifecycle rule that actually governs
 * the stored generations.
 *
 * <p>Trade-offs: no version member, no transaction attribute and no stereotype annotation. The stream
 * is appended to and never re-read, so there is no before-image for a version check to detect and no
 * HTTP 409 originates here. The commit boundary belongs to the calling job rather than to a repository,
 * because the posting unit spans three record types at {@code app/cbl/CBTRN02C.cbl} lines 440 to 442
 * and no single repository can own it. The framework registers the proxy from the {@code JpaRepository}
 * supertype, so a stereotype would restate the declaration.

 */
public interface TransactionRejectRepository extends JpaRepository<TransactionReject, Long> {
}
