/**
 * Card-route contract shared by the router, links and API client.
 *
 * Refactoring Rationale: the baseline carried the full sixteen-digit card
 * number in selection context. Reusing it as a browser path segment would copy
 * PAN into CloudFront access logs, browser history and referrer metadata. The
 * service therefore returns a 22-character URL-safe HMAC token generated by
 * `OpaqueIdentifier`, and this module is the only code allowed to turn that
 * token into a card route.
 */

const OPAQUE_CARD_ID_PATTERN = /^[A-Za-z0-9_-]{22}$/u;

/** Browser path pattern for a card detail screen. */
export const CARD_DETAIL_ROUTE = "/cards/:opaqueCardId";

/** Browser path pattern for a card update screen. */
export const CARD_EDIT_ROUTE = "/cards/:opaqueCardId/edit";

/**
 * Reports whether a value has the bounded URL-safe form produced by the server.
 * @param {string} value - Candidate route or response value.
 * @returns {boolean} `true` only for a 22-character opaque identifier.
 */
export function isOpaqueCardId(value: string): boolean {
  return OPAQUE_CARD_ID_PATTERN.test(value);
}

/**
 * Validates a route identifier without echoing a rejected value.
 * @param {string | null | undefined} value - Candidate identifier from a route parameter or
 *   service response.
 * @returns {string} The validated opaque identifier.
 * @throws {RangeError} If the value is absent or not a server-issued token shape.
 */
export function requireOpaqueCardId(value: string | null | undefined): string {
  if (value === null || value === undefined || !isOpaqueCardId(value)) {
    throw new RangeError(
      `opaqueCardId must be a 22-character URL-safe token; received a value of length ${String(value?.length ?? 0)}.`,
    );
  }
  return value;
}

/**
 * Builds the browser location for one card without accepting a PAN.
 * @param {string} opaqueCardId - Server-issued opaque card identifier.
 * @returns {string} The card-detail route.
 * @throws {RangeError} If the identifier is not a valid opaque token.
 */
export function cardDetailPath(opaqueCardId: string): string {
  return `/cards/${requireOpaqueCardId(opaqueCardId)}`;
}

/**
 * Builds the browser location for editing one card without accepting a PAN.
 * @param {string} opaqueCardId - Server-issued opaque card identifier.
 * @returns {string} The card-update route.
 * @throws {RangeError} If the identifier is not a valid opaque token.
 */
export function cardEditPath(opaqueCardId: string): string {
  return `${cardDetailPath(opaqueCardId)}/edit`;
}
