# =============================================================================
# infra/modules/step-functions-batch/versions.tf
# -----------------------------------------------------------------------------
# Purpose:
#   The Terraform CLI and provider contract for the `step-functions-batch`
#   module, and nothing else. The module body provisions the batch orchestration
#   layer that replaces the mainframe's nightly job stream: the eleven-work-state
#   `carddemo-daily-batch` state machine, a second and much smaller state machine
#   for on-demand reports, one shared IAM execution role and one CloudWatch log
#   group per machine. Resources, inputs and outputs live in main.tf,
#   variables.tf and outputs.tf.
#
#   Assumptions: reusable MODULE, never a Terraform root. infra/envs/dev and
#   infra/envs/prod each consume it as
#   `source = "../../modules/step-functions-batch"`, so it is initialised
#   transitively inside a calling root's module graph and never applied on its
#   own. Every absence noted below follows from that one fact, and none of them
#   becomes appropriate later: a `provider` block would burn one region and one
#   credentials chain into a module both roots share, stop the root's
#   `default_tags` reaching these resources and bar a caller from passing an
#   aliased provider through `providers = {}`; a `backend` block would fail
#   `init` for every calling root, because Terraform accepts state configuration
#   only in a root module; `experiments` would propagate unstable language
#   features to every caller; and `provider_meta` serves a published provider
#   rather than a first-party module. `.terraform.lock.hcl` beside this file is
#   generated by module-level `init` and committed under this repository's
#   module-lock convention -- a calling root still resolves and locks the
#   combined graph independently. Note the deliberate contrast with
#   infra/bootstrap, which is a ROOT and therefore does own a provider
#   configuration; inverting those two cases is the error to avoid.
#
#   Lineage: the daily machine carries the step ordering of the job streams under
#   app/jcl/, of which app/jcl/POSTTRAN.jcl is the representative case -- a
#   single `EXEC PGM=` step at L23 with nine DD statements behind it, including
#   the newly-created reject stream at L34-L38 whose `(+1)` relative generation
#   becomes a new object generation rather than a new catalogued dataset. The
#   second machine carries the ad-hoc submission path that
#   app/csd/CARDDEMO.CSD:L499-L501 defines as a transient-data queue writing to
#   the internal reader. Both baseline artifacts are reference-only. The choice
#   of Terraform itself is settled in docs/adr/ADR-009-iac-tool.md.
#
#   Trade-offs: both constraints are character-for-character identical to those
#   in every sibling module, which is deliberate rather than copy-paste inertia.
#   A calling root intersects the constraints of every module in its graph and
#   resolves one release of each provider for the whole graph, so a range that
#   differs per module narrows that intersection and, in the limit, empties it.
#   Restating one contract per directory is accepted so that each states what it
#   needs on its own terms; the alternative -- letting a module inherit its
#   version contract from whichever root loaded it -- was rejected because a
#   module reached from an unexpected caller would then carry no contract at all.
#
#   Refactoring Rationale: the baseline expressed no platform contract of any
#   kind. A job stream such as app/jcl/POSTTRAN.jcl names the program it runs and
#   the datasets it needs but says nothing about the system level required to run
#   them, so a mismatch surfaced part-way through a night's chain as a failing
#   step rather than as a refusal to start. Declaring the CLI floor and the
#   provider range corrects that specific gap, which is why this file exists at
#   all in a module whose resources are declared elsewhere.
# =============================================================================

terraform {
  # Assumptions: 1.15.0 is the oldest release that parses what this tree writes
  #   and the package was validated on 1.15.8. A floor rather than an `=` pin
  #   because this module is reached from both environment roots and from the
  #   validate and lint jobs, none of whose CLI it controls, and a reusable module
  #   has no standing to oblige them onto one patch release. The consequence is
  #   the reason to declare it: a root on an older CLI stops at `init` with a
  #   version error pointing here instead of failing further along on whichever
  #   construct that CLI could not read. The roots additionally bound the minor
  #   line, because a root is the directory an operator actually runs.
  required_version = ">= 1.15.0"

  required_providers {
    # Assumptions: the 6.56 line carries every resource main.tf declares --
    #   `aws_sfn_state_machine` with its `logging_configuration` and
    #   `tracing_configuration` blocks, `aws_iam_role`, `aws_iam_role_policy`,
    #   `aws_cloudwatch_log_group`, and the `aws_partition`, `aws_region` and
    #   `aws_caller_identity` data sources the execution role's policy is composed
    #   from. Naming that surface is what makes the constraint load-bearing rather
    #   than decorative: it records what would break were the range widened
    #   downward.
    # Trade-offs: `~> 6.56` admits later 6.x and stops short of 7.0, so provider
    #   patch and minor releases reach this module with no edit here while a major
    #   move -- which may rename or drop an argument this module sets -- has to be
    #   a deliberate, reviewable change. An exact `= 6.56.0` would force every
    #   consuming root onto one build and block provider fixes; an unbounded
    #   `>= 6.56` would admit a breaking major silently, as a failed plan against
    #   configuration nobody had touched.
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.56"
    }

    # Alternatives Considered: declaring `hashicorp/random` here too, tempting
    #   because infra/modules/secrets and infra/modules/cognito do declare it to
    #   generate the database credential and the seed-user passwords straight into
    #   Secrets Manager. Rejected on two independent grounds: this module
    #   generates nothing, deriving every name and identifier from its inputs; and
    #   infra/.tflint.hcl enables terraform_unused_required_providers, which
    #   reports an entry no resource in the same directory consumes. Past the
    #   finding, a declared random provider would tell every reader that this
    #   module might mint a credential, and that would be false.
  }
}
