#!/bin/sh
# =============================================================================
# config/docker/generate-listener-material.sh
# Container entry point for every load-balanced CardDemo service image.
# -----------------------------------------------------------------------------
# Purpose:
#   Mint this TASK's own HTTPS listener key pair and self-signed certificate
#   into a PKCS#12 keystore, publish the keystore location and its one-time
#   password to the JVM through the environment, and then replace this shell
#   with the JVM.
#
#   The material exists only inside the task that uses it. It is generated at
#   startup, written to the task's own encrypted ephemeral volume, and destroyed
#   with the task. No key is stored in Terraform state, in Secrets Manager, in
#   an image layer, in a task definition or in plan output, and no two tasks
#   ever present the same key.
#
# Parameters (environment, all optional; every one has a working default):
#   CARDDEMO_SERVER_TLS_DIR
#     Absolute directory the keystore is written to. Defaults to
#     /tmp/carddemo-tls. Must sit under a path the task definition keeps
#     writable -- infra/modules/ecs-service defaults readonly_root_filesystem
#     to true and backs writable_mount_paths (default ["/tmp"]) with a Fargate
#     ephemeral volume that is encrypted at rest and destroyed with the task,
#     which is exactly the lifetime this material should have.
#   CARDDEMO_SERVER_TLS_KEY_ALIAS
#     Keystore alias. Defaults to carddemo-listener. Must match
#     server.ssl.key-alias, whose default in every service's application.yml is
#     the same literal.
#   CARDDEMO_SERVER_TLS_SUBJECT_CN
#     Certificate common name and DNS subject-alternative name. Defaults to the
#     container hostname, falling back to carddemo-service where the runtime
#     sets no HOSTNAME.
#   CARDDEMO_SERVER_TLS_VALIDITY_DAYS
#     Certificate validity in days. Defaults to 90. A task lives for hours, so
#     this is a ceiling on an already-short lifetime rather than a renewal
#     interval.
#   JAVA_OPTS
#     Optional JVM arguments, word-split and passed before -jar.
#
# Exports (consumed by server.ssl in each service's application.yml):
#   CARDDEMO_SERVER_TLS_KEYSTORE           file: URL of the generated keystore
#   CARDDEMO_SERVER_TLS_KEYSTORE_PASSWORD  the one-time keystore password
#   CARDDEMO_SERVER_TLS_KEY_ALIAS          the alias, defaulted if unset
#
# Exits:
#   Non-zero, before the JVM starts, if the directory cannot be created, if a
#   password cannot be drawn, or if keytool fails. It never starts the JVM
#   without a keystore: a service that came up on cleartext would pass its
#   health check while silently no longer meeting the encryption-in-transit
#   requirement, which is worse than a task that refuses to start.
# =============================================================================

set -eu

# WHY : Refactoring Rationale: this script exists because the listener key used
#       to be ONE key, generated by a managed `tls_private_key` in each
#       environment root, persisted in Terraform state, copied into two Secrets
#       Manager entries and injected into every online task. Anyone who could
#       read the state file held the server private key of all eight services at
#       once. Four resolutions were measured against the frozen provider set
#       before this one was chosen:
#         (a) make the key `ephemeral.tls_private_key` and write it through the
#             write-only sinks. `ephemeral` exists in hashicorp/tls 4.3.0 and
#             `secret_string_wo` / `private_key_wo` exist in hashicorp/aws
#             6.57.1, but `tls_self_signed_cert` has NO write-only attribute, and
#             `terraform validate` rejects the wiring outright: "Ephemeral values
#             are not valid for \"private_key_pem\", because it is not a
#             write-only attribute and must be persisted to state." So the KEY
#             could be kept out of state and the CERTIFICATE could then not be
#             produced at all.
#         (b) mint the pair in a Lambda and import it, leaving Terraform only an
#             ARN. Rejected on measurement: the AWS Lambda python:3.13 runtime
#             ships awslambdaric, boto3, botocore, dateutil, jmespath, pip,
#             s3transfer, simplejson, six, snapshot_restore_py and urllib3, and
#             carries neither an `openssl` nor a `keytool` binary -- so a
#             certificate could only be built by hand-rolling RSA key generation
#             and DER encoding, which is the wrong place to write new
#             cryptographic code.
#         (c) have ACM issue and hold the key. Rejected: ACM issues only against
#             a validated public domain or an AWS Private CA, this stack owns no
#             DNS zone, and a Private CA is a recurring monthly charge for one
#             internal listener.
#         (d) this script. The runtime image already contains everything needed
#             -- /usr/bin/keytool, /usr/bin/tr, /usr/bin/head and a readable
#             /dev/urandom were each verified inside the pinned digest -- so the
#             material is produced with no new dependency, no new AWS resource,
#             no recurring cost and no hand-written cryptography.
# WHY : Trade-offs: per-TASK material is stronger than the per-SERVICE material
#       the alternative designs would have produced, and it costs the ability to
#       pin a task's certificate fingerprint from outside the task. Nothing
#       needs that: an Application Load Balancer does not validate the
#       certificate a target in an HTTPS target group presents, which is the
#       same property the previous self-signed certificate already relied on,
#       and the container health probe passes --insecure for the same reason.
#       The certificate at the hop API Gateway verifies is unaffected -- that one
#       is the operator-supplied ACM certificate on the load balancer's own
#       listener, which this script does not touch.

tls_dir="${CARDDEMO_SERVER_TLS_DIR:-/tmp/carddemo-tls}"
key_alias="${CARDDEMO_SERVER_TLS_KEY_ALIAS:-carddemo-listener}"
subject_cn="${CARDDEMO_SERVER_TLS_SUBJECT_CN:-${HOSTNAME:-carddemo-service}}"
validity_days="${CARDDEMO_SERVER_TLS_VALIDITY_DAYS:-90}"
keystore="${tls_dir}/listener.p12"

# WHY : Assumptions: the directory is created with mode 0700 and the keystore
#       with 0600 BEFORE anything is written into it, so the file is never
#       briefly group- or world-readable. `umask` is set rather than relying on
#       a chmod afterwards, because keytool creates the file itself and a chmod
#       can only narrow permissions the file has already been visible with.
umask 0077
mkdir -p "${tls_dir}"
chmod 700 "${tls_dir}"

# WHY : Assumptions: a fresh keystore is generated on every start and any
#       previous one is removed first. keytool APPENDS to an existing keystore,
#       so a restarted container that reused a mounted directory would otherwise
#       accumulate aliases and fail on a duplicate. Removing it also means a
#       task never presents a predecessor's key.
rm -f "${keystore}"

# WHY : Assumptions: the password is drawn from /dev/urandom rather than being a
#       fixed literal. A literal in a committed application.yml would read as a
#       committed secret to every reader and to the repository's secret scanner,
#       and this project's constraint is that no secret is expressible in
#       source. The value protects a file that never leaves the task and whose
#       mode is already 0600, so its real job is to satisfy the PKCS#12 format's
#       requirement that one exist.
# WHY : Trade-offs: 40 alphanumeric characters rather than a longer or
#       punctuation-bearing string. Punctuation is excluded because the value is
#       passed to keytool as an argument and read back by the JVM from the
#       environment, and a quoting mistake in either place would be an
#       intermittent startup failure rather than a visible one.
keystore_password="$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 40)"
if [ "${#keystore_password}" -ne 40 ]; then
    echo "generate-listener-material: could not draw a keystore password from /dev/urandom" >&2
    exit 1
fi

# WHY : Assumptions: -storepass and -keypass are given the SAME value. PKCS#12
#       does not model a per-entry password distinct from the store password,
#       and keytool warns and silently uses the store password when they differ,
#       so passing one value states what actually happens.
# WHY : Assumptions: the subject-alternative names include localhost and
#       127.0.0.1 as well as the subject common name, because the container
#       health probe dials https://127.0.0.1:8080. The probe passes --insecure
#       and so does not require them, but a certificate that omits the name it
#       is actually presented for is misleading to anyone who inspects it.
# WHY : Trade-offs: keytool's own progress line is written to stderr and kept.
#       It names the algorithm, key size and validity and contains no secret --
#       the password is never echoed and appears in no log -- so keeping it
#       gives an operator positive evidence that this step ran.
keytool -genkeypair \
    -alias "${key_alias}" \
    -keyalg RSA \
    -keysize 2048 \
    -sigalg SHA256withRSA \
    -validity "${validity_days}" \
    -storetype PKCS12 \
    -keystore "${keystore}" \
    -storepass "${keystore_password}" \
    -keypass "${keystore_password}" \
    -dname "CN=${subject_cn}, O=CardDemo" \
    -ext "SAN=dns:${subject_cn},dns:localhost,ip:127.0.0.1"

chmod 600 "${keystore}"

# WHY : Assumptions: the three values are exported rather than appended to the
#       java command line. A JVM argument is visible in `ps` output and in a
#       container inspection to anything sharing the namespace, whereas the
#       environment of a process is readable only by that process's own user and
#       root. Spring Boot resolves ${...} placeholders from the environment, so
#       the properties in application.yml pick these up with no extra wiring.
export CARDDEMO_SERVER_TLS_KEYSTORE="file:${keystore}"
export CARDDEMO_SERVER_TLS_KEYSTORE_PASSWORD="${keystore_password}"
export CARDDEMO_SERVER_TLS_KEY_ALIAS="${key_alias}"

# WHY : Assumptions: `exec` is what preserves the property the previous
#       ENTRYPOINT was written for -- the JVM becomes PID 1 and receives SIGTERM
#       directly from ECS, so Spring runs its shutdown hooks and the task
#       drains instead of being killed on timeout. Without `exec` this shell
#       would stay PID 1 and would not forward the signal, which is the exact
#       failure the original exec-form ENTRYPOINT existed to avoid.
# WHY : Trade-offs: ${JAVA_OPTS} is left unquoted so a caller can pass several
#       arguments in one variable. That is deliberate word splitting, and it is
#       the only unquoted expansion in this script; every other expansion is
#       quoted because a split there would be a defect rather than a feature.
# shellcheck disable=SC2086
exec java ${JAVA_OPTS:-} -jar /app/app.jar "$@"
