package com.carddemo.authorization.fixtures;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.carddemo.common.codec.CopybookLayout;
import com.carddemo.common.codec.CopybookLayout.RecordSpec;
import com.carddemo.common.codec.CsvAuthCodec;
import com.carddemo.common.codec.CsvAuthCodec.AuthRequest;
import com.carddemo.common.codec.FixedWidthCodec;
import com.carddemo.common.money.Money;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Consumes every fixture in this module and asserts the contract each one carries.
 *
 * <p>Purpose: a fixture with no executable consumer is a file whose bytes can change while the whole
 * suite stays green. This class is the consumer for all sixteen resources under
 * {@code src/test/resources/fixtures}, and it asserts for each one what
 * {@code src/test/resources/fixtures/README.md} states about it: the record width, the field values,
 * the final record, and the failure path where one exists.
 *
 * <p>Assumptions: the tests read the resources through the classpath rather than through a filesystem
 * path, because that is how the packaged test jar reaches them and because a filesystem path would
 * make the suite depend on the working directory a runner happens to choose.
 *
 * <p>Assumptions: the inventory is asserted as a closed set before any file is read. A test that only
 * consumed the files it named would stay green after a fixture was added with no consumer, which is
 * the exact condition this class exists to prevent.
 *
 * <p>Trade-offs: the binary fixtures are decoded through {@link FixedWidthCodec} against the registry
 * layouts rather than by hand-slicing byte ranges here. Hand-slicing would have made this class a
 * second transcription of the same copybook, free to disagree with the registry it is supposed to
 * verify; decoding through the registry means a wrong offset in either the registry or a fixture
 * fails here. The independence that a second transcription would have provided is supplied instead by
 * the fixtures having been generated by the Python codec, as the README records.
 */
class AuthorizationFixtureContractTest {

    /**
     * The classpath directory every fixture in this module lives under.
     *
     * <p>Assumptions: the path is relative to the classpath root and carries no leading solidus, which
     * is what {@link Class#getResourceAsStream} requires when a name is resolved absolutely through
     * the class loader.</p>
     */
    private static final String FIXTURE_ROOT = "fixtures/";

    /**
     * Every fixture resource this module ships, as a closed set.
     *
     * <p>Assumptions: the README is listed alongside the data files. It is a fixture-directory
     * resource and its absence would mean the family had lost its documented contract, which is the
     * condition the inventory assertion is there to catch.</p>
     */
    private static final List<String> EVERY_FIXTURE = List.of(
            "README.md",
            "auth-request-amount-variants.csv",
            "auth-request-canonical-wire169.csv",
            "auth-request-copybook-wire170-decode-only.csv",
            "pautdtl-canonical.bin",
            "pautdtl-filler-nonblank.bin",
            "pautdtl-fraud-marked.bin",
            "pautdtl-line-terminator-bytes.bin",
            "pautdtl-match-status-domain.bin",
            "pautdtl-negative-zero-decode-only.bin",
            "pautdtl-purge-children.bin",
            "pautsum0-canonical.bin",
            "pautsum0-filler-nonblank.bin",
            "pautsum0-line-terminator-bytes.bin",
            "pautsum0-negative-zero-decode-only.bin",
            "pautsum0-purge-parent.bin",
            "unload-gsam-summary-100.bin",
            "unload-prefixed-summary-100.bin");

    /**
     * Supplies every binary fixture name paired with the layout it is written against.
     *
     * @return one argument row per binary fixture: the resource name and its layout name
     */
    private static List<org.junit.jupiter.params.provider.Arguments> everyBinaryFixture() {
        return List.of(
                org.junit.jupiter.params.provider.Arguments.of("pautsum0-canonical.bin", "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("pautsum0-filler-nonblank.bin",
                        "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("pautsum0-line-terminator-bytes.bin",
                        "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of(
                        "pautsum0-negative-zero-decode-only.bin", "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("pautsum0-purge-parent.bin",
                        "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("unload-gsam-summary-100.bin",
                        "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("unload-prefixed-summary-100.bin",
                        "PAUTSUM0"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-canonical.bin", "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-filler-nonblank.bin",
                        "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-fraud-marked.bin", "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-line-terminator-bytes.bin",
                        "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-match-status-domain.bin",
                        "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of(
                        "pautdtl-negative-zero-decode-only.bin", "PAUTDTL"),
                org.junit.jupiter.params.provider.Arguments.of("pautdtl-purge-children.bin",
                        "PAUTDTL"));
    }

    /**
     * Reads one fixture resource as raw bytes.
     *
     * @param name the resource name below the fixture root
     * @return the resource's bytes, exactly as stored
     * @throws AssertionError if the resource is not on the test classpath
     * @throws UncheckedIOException if the resource cannot be read once opened
     */
    private static byte[] bytesOf(String name) {
        try (InputStream stream = AuthorizationFixtureContractTest.class.getClassLoader()
                .getResourceAsStream(FIXTURE_ROOT + name)) {
            if (stream == null) {
                throw new AssertionError("fixture " + name + " is not on the test classpath");
            }
            return stream.readAllBytes();
        } catch (IOException failure) {
            throw new UncheckedIOException("fixture " + name + " could not be read", failure);
        }
    }

    /**
     * Reads one fixture resource as its lines, dropping a trailing newline only.
     *
     * <p>Assumptions: the split is on the newline alone and empty trailing entries are removed, so a
     * file whose last line ends with a terminator yields the same line count as one whose last line
     * does not. Every payload width asserted below is therefore the width of the payload rather than
     * of the payload plus a terminator.</p>
     *
     * @param name the resource name below the fixture root
     * @return the resource's lines with no terminator characters
     */
    private static List<String> linesOf(String name) {
        List<String> lines = new ArrayList<>();
        for (String line : new String(bytesOf(name), StandardCharsets.US_ASCII).split("\n")) {
            String stripped = line.endsWith("\r") ? line.substring(0, line.length() - 1) : line;
            if (!stripped.isEmpty()) {
                lines.add(stripped);
            }
        }
        return lines;
    }

    /**
     * Slices one fixed-length record out of a multi-record fixture.
     *
     * @param image the whole fixture image
     * @param ordinal the zero-based record ordinal
     * @param reclen the record length the layout declares
     * @return exactly {@code reclen} bytes beginning at the ordinal's offset
     */
    private static byte[] recordAt(byte[] image, int ordinal, int reclen) {
        byte[] record = new byte[reclen];
        System.arraycopy(image, ordinal * reclen, record, 0, reclen);
        return record;
    }

    /**
     * Returns one decoded field as text with its trailing blanks removed.
     *
     * @param fields the decoded record
     * @param name the copybook field name
     * @return the field's characters with trailing blanks stripped
     */
    private static String textField(Map<String, Object> fields, String name) {
        return String.valueOf(fields.get(name)).stripTrailing();
    }

    /**
     * Returns one decoded field as an exact decimal.
     *
     * @param fields the decoded record
     * @param name the copybook field name
     * @return the field's value as a {@link BigDecimal}
     */
    private static BigDecimal amountField(Map<String, Object> fields, String name) {
        return new BigDecimal(String.valueOf(fields.get(name)));
    }

    /**
     * Confirms the fixture directory holds exactly the resources this test consumes.
     *
     * <p>Assumptions: the set is asserted in both directions. Every name below is proved present, and
     * the count is proved equal, so a fixture added without a consumer fails here rather than sitting
     * unread.</p>
     */
    @Test
    @DisplayName("every fixture this module ships is on the classpath and is consumed here")
    void everyFixtureIsPresentAndConsumed() {
        for (String name : EVERY_FIXTURE) {
            assertThat(bytesOf(name)).as("fixture %s", name).isNotEmpty();
        }
        assertThat(EVERY_FIXTURE).doesNotHaveDuplicates().hasSize(18);
    }

    /**
     * Confirms the canonical request payload is the exact wire the encoder emits.
     *
     * <p>Assumptions: the assertion is byte equality against a freshly encoded payload, which makes
     * this fixture the encode oracle rather than merely a decodable example. A field-by-field
     * comparison would pass for a payload whose delimiter or field order had changed.</p>
     */
    @Test
    @DisplayName("the canonical request fixture is byte-identical to what the encoder emits")
    void canonicalRequestFixtureIsTheEncodeOracle() {
        List<String> lines = linesOf("auth-request-canonical-wire169.csv");
        assertThat(lines).hasSize(1);

        String payload = lines.get(0);
        assertThat(payload).hasSize(CsvAuthCodec.REQUEST_WIRE_LENGTH);
        assertThat(payload.split(",", -1)).hasSize(CsvAuthCodec.REQUEST_FIELD_COUNT);

        AuthRequest decoded = CsvAuthCodec.decodeRequest(payload);
        assertThat(decoded.cardNum()).isEqualTo("4000123456789010");
        assertThat(decoded.transactionAmount().amount()).isEqualByComparingTo("250.00");
        assertThat(decoded.transactionId()).isEqualTo("TXN000000000169");
        assertThat(CsvAuthCodec.encodeRequest(decoded)).isEqualTo(payload);
    }

    /**
     * Confirms the copybook-width payload decodes to the same amount and is never re-emitted.
     *
     * <p>Assumptions: the two properties are asserted together because either alone would be
     * misleading. That the wider payload decodes shows the tolerance the reference consumer has; that
     * re-encoding it yields the narrower payload shows the emission contract has not widened to match
     * it.</p>
     */
    @Test
    @DisplayName("the copybook-width request fixture decodes but is re-emitted at the narrower width")
    void copybookWidthRequestFixtureIsDecodeOnly() {
        List<String> lines = linesOf("auth-request-copybook-wire170-decode-only.csv");
        assertThat(lines).hasSize(1);

        String wide = lines.get(0);
        assertThat(wide).hasSize(CsvAuthCodec.REQUEST_WIRE_LENGTH + 1);

        AuthRequest decoded = CsvAuthCodec.decodeRequest(wide);
        assertThat(decoded.transactionAmount().amount()).isEqualByComparingTo("250.00");

        String reEmitted = CsvAuthCodec.encodeRequest(decoded);
        assertThat(reEmitted).hasSize(CsvAuthCodec.REQUEST_WIRE_LENGTH).isNotEqualTo(wide);
        assertThat(reEmitted.split(",", -1)[CsvAuthCodec.REQUEST_AMOUNT_ORDINAL])
                .hasSize(CsvAuthCodec.REQUEST_MONEY_WIDTH)
                .isEqualTo("0000000250.00");
    }

    /**
     * Confirms the canonical and copybook payloads differ in exactly one field.
     *
     * <p>Assumptions: this is asserted as a property of the PAIR rather than of either file, because
     * the pair's whole purpose is to isolate the money width. A difference in a second field would
     * make a failure ambiguous between the width and whatever else had changed.</p>
     */
    @Test
    @DisplayName("the two request fixtures differ in the money field alone")
    void theTwoRequestFixturesDifferInOneFieldOnly() {
        String[] canonical = linesOf("auth-request-canonical-wire169.csv").get(0).split(",", -1);
        String[] copybook =
                linesOf("auth-request-copybook-wire170-decode-only.csv").get(0).split(",", -1);

        assertThat(canonical).hasSameSizeAs(copybook);
        List<Integer> differing = new ArrayList<>();
        for (int index = 0; index < canonical.length; index++) {
            if (!canonical[index].equals(copybook[index])) {
                differing.add(index);
            }
        }
        assertThat(differing).containsExactly(CsvAuthCodec.REQUEST_AMOUNT_ORDINAL,
                CsvAuthCodec.REQUEST_FIELD_COUNT - 1);
    }

    /**
     * Confirms each money-boundary payload carries the canonical width and decodes exactly.
     *
     * @param ordinal the zero-based line ordinal within the fixture
     * @param expectedToken the money token that line is expected to carry
     * @param expectedAmount the amount that token is expected to decode to
     */
    @ParameterizedTest
    @CsvSource({
        "0, -000000250.00, -250.00",
        "1, 9999999999.99, 9999999999.99",
        "2, 0000000000.00, 0.00",
    })
    @DisplayName("every money-boundary payload is the canonical width and decodes exactly")
    void everyMoneyBoundaryPayloadDecodesExactly(int ordinal, String expectedToken,
            String expectedAmount) {
        List<String> lines = linesOf("auth-request-amount-variants.csv");
        assertThat(lines).hasSize(3);

        String payload = lines.get(ordinal);
        assertThat(payload).hasSize(CsvAuthCodec.REQUEST_WIRE_LENGTH);

        String token = payload.split(",", -1)[CsvAuthCodec.REQUEST_AMOUNT_ORDINAL];
        assertThat(token).isEqualTo(expectedToken).hasSize(CsvAuthCodec.REQUEST_MONEY_WIDTH);

        AuthRequest decoded = CsvAuthCodec.decodeRequest(payload);
        assertThat(decoded.transactionAmount().amount()).isEqualByComparingTo(expectedAmount);
        assertThat(CsvAuthCodec.encodeRequest(decoded)).isEqualTo(payload);
    }

    /**
     * Confirms the final record of the multi-record request fixture is the zero boundary.
     *
     * <p>Assumptions: the last record is asserted specifically. A loop over every line would pass on a
     * file that had lost its final line, because the loop would simply run one fewer time.</p>
     */
    @Test
    @DisplayName("the money-boundary fixture's final record is the zero amount")
    void theMoneyBoundaryFixtureEndsWithZero() {
        List<String> lines = linesOf("auth-request-amount-variants.csv");
        String last = lines.get(lines.size() - 1);

        assertThat(CsvAuthCodec.decodeRequest(last).transactionAmount().amount())
                .isEqualByComparingTo("0.00");
        assertThat(CsvAuthCodec.decodeRequest(last).transactionId())
                .isEqualTo("TXN000000000202");
    }

    /**
     * Confirms a payload with a truncated field is refused rather than padded back.
     *
     * <p>Assumptions: the failure path is exercised from a real fixture rather than an invented
     * string, so what is proved is that THIS wire's fields are width-checked. A shortened token means
     * the payload lost bytes, and reconstructing it by padding would put a wrong value into a field
     * that looked well formed.</p>
     */
    @Test
    @DisplayName("a request payload whose field lost bytes is refused, not padded back")
    void aTruncatedRequestFieldIsRefused() {
        String payload = linesOf("auth-request-canonical-wire169.csv").get(0);
        String[] fields = payload.split(",", -1);
        fields[2] = fields[2].substring(0, fields[2].length() - 1);

        assertThatThrownBy(() -> CsvAuthCodec.decodeRequest(String.join(",", fields)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("PA-RQ-CARD-NUM");
    }

    /**
     * Confirms a payload with the wrong field count is refused.
     */
    @Test
    @DisplayName("a request payload with the wrong field count is refused")
    void aRequestWithTheWrongFieldCountIsRefused() {
        String payload = linesOf("auth-request-canonical-wire169.csv").get(0);

        assertThatThrownBy(() -> CsvAuthCodec.decodeRequest(payload + ",EXTRA"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    /**
     * Confirms every binary fixture divides into whole records of its layout's declared length.
     *
     * <p>Assumptions: exact division is asserted before any field is read, because a remainder means
     * the image is truncated or written against the wrong geometry, and in either case no offset in
     * it can be trusted. This is the binary analogue of the field-width check on the CSV wire.</p>
     *
     * @param name the fixture resource name
     * @param layoutName the registry layout the fixture is written against
     */
    @ParameterizedTest
    @MethodSource("everyBinaryFixture")
    @DisplayName("every binary fixture divides into whole records of its declared length")
    void everyBinaryFixtureDividesIntoWholeRecords(String name, String layoutName) {
        RecordSpec spec = CopybookLayout.layout(layoutName);
        byte[] image = bytesOf(name);

        assertThat(image.length % spec.reclen())
                .as("fixture %s against %s-byte records", name, spec.reclen())
                .isZero();
        assertThat(image.length / spec.reclen()).isPositive();
    }

    /**
     * Confirms every record of every binary fixture decodes and re-encodes byte-identically.
     *
     * <p>Assumptions: byte identity on re-encode is the strongest property available here and it is
     * what proves the decode lost nothing -- not a sign, not a pad nibble, not a filler byte. It is
     * asserted for every record of every fixture, because a fixture family whose first record round
     * trips and whose fourth does not is exactly the case a single-record test misses.</p>
     *
     * <p>Trade-offs: the sign-preserving encoder is used rather than the plain one, because a
     * negatively-signed packed zero re-encodes to the POSITIVE sign nibble under the plain encoder --
     * documented divergence {@code D-SIGNED-ZERO-PACKED} -- so the two decode-only fixtures would fail
     * byte identity for a reason that is a deliberate normalisation rather than a loss.</p>
     *
     * @param name the fixture resource name
     * @param layoutName the registry layout the fixture is written against
     */
    @ParameterizedTest
    @MethodSource("everyBinaryFixture")
    @DisplayName("every record of every binary fixture round trips byte-identically")
    void everyBinaryRecordRoundTripsByteIdentically(String name, String layoutName) {
        RecordSpec spec = CopybookLayout.layout(layoutName);
        byte[] image = bytesOf(name);

        for (int ordinal = 0; ordinal < image.length / spec.reclen(); ordinal++) {
            byte[] record = recordAt(image, ordinal, spec.reclen());
            Map<String, Object> fields = FixedWidthCodec.decodeRecord(record, spec);

            assertThat(fields).as("record %s of %s", ordinal, name).isNotEmpty();
            assertThat(FixedWidthCodec.encodeRecordPreservingSign(fields, spec, record))
                    .as("record %s of %s re-encodes byte-identically", ordinal, name)
                    .isEqualTo(record);
        }
    }

    /**
     * Confirms the canonical summary fixture carries every documented field value.
     *
     * <p>Assumptions: the negative credit balance is asserted specifically. It is the one field in the
     * fixture whose sign a mis-decoded overpunch or a mis-read packed sign nibble would flip, and a
     * balance that came back positive would still be a well-formed amount.</p>
     */
    @Test
    @DisplayName("the canonical summary fixture decodes to its documented field values")
    void canonicalSummaryFixtureDecodesToItsDocumentedValues() {
        RecordSpec spec = CopybookLayout.layout("PAUTSUM0");
        Map<String, Object> fields =
                FixedWidthCodec.decodeRecord(bytesOf("pautsum0-canonical.bin"), spec);

        assertThat(amountField(fields, "PA-ACCT-ID")).isEqualByComparingTo("10000000001");
        // WHY : Assumptions: the customer identifier is asserted NUMERICALLY, because an unsigned
        //       display field decodes to a number and not to its stored characters -- the fixture
        //       stores "000000451" and the decode yields 451. Asserting the stored form here would
        //       be asserting the codec's UINT contract in the wrong place, and the fixture README
        //       records both forms so a reader of the bytes is not surprised by the decode.
        assertThat(amountField(fields, "PA-CUST-ID")).isEqualByComparingTo("451");
        assertThat(textField(fields, "PA-AUTH-STATUS")).isEqualTo("A");
        assertThat(textField(fields, "PA-ACCOUNT-STATUS")).isEqualTo("A1B2C3D4E5");
        assertThat(amountField(fields, "PA-CREDIT-LIMIT")).isEqualByComparingTo("5000.00");
        assertThat(amountField(fields, "PA-CASH-LIMIT")).isEqualByComparingTo("1000.00");
        assertThat(amountField(fields, "PA-CREDIT-BALANCE")).isEqualByComparingTo("-100.00");
        assertThat(amountField(fields, "PA-CASH-BALANCE")).isEqualByComparingTo("0.00");
        assertThat(amountField(fields, "PA-APPROVED-AUTH-CNT")).isEqualByComparingTo("42");
        assertThat(amountField(fields, "PA-DECLINED-AUTH-CNT")).isEqualByComparingTo("7");
        assertThat(amountField(fields, "PA-APPROVED-AUTH-AMT")).isEqualByComparingTo("4200.00");
        assertThat(amountField(fields, "PA-DECLINED-AUTH-AMT")).isEqualByComparingTo("700.00");
    }

    /**
     * Confirms the canonical detail fixture carries every documented field value.
     *
     * <p>Assumptions: the misspelt merchant-category field is read by its copybook name, because that
     * is the name the registry declares. Reading it by the corrected name would fail, which is the
     * point: the correction belongs to the mapping layer and not to the codec.</p>
     */
    @Test
    @DisplayName("the canonical detail fixture decodes to its documented field values")
    void canonicalDetailFixtureDecodesToItsDocumentedValues() {
        RecordSpec spec = CopybookLayout.layout("PAUTDTL");
        Map<String, Object> fields =
                FixedWidthCodec.decodeRecord(bytesOf("pautdtl-canonical.bin"), spec);

        assertThat(amountField(fields, "PA-AUTH-DATE-9C")).isEqualByComparingTo("24095");
        assertThat(amountField(fields, "PA-AUTH-TIME-9C")).isEqualByComparingTo("91500");
        assertThat(textField(fields, "PA-CARD-NUM")).isEqualTo("4000123456789010");
        assertThat(textField(fields, "PA-AUTH-TYPE")).isEqualTo("PURC");
        assertThat(textField(fields, "PA-AUTH-RESP-CODE")).isEqualTo("00");
        assertThat(amountField(fields, "PA-TRANSACTION-AMT")).isEqualByComparingTo("250.00");
        assertThat(amountField(fields, "PA-APPROVED-AMT")).isEqualByComparingTo("250.00");
        assertThat(textField(fields, "PA-MERCHANT-CATAGORY-CODE")).isEqualTo("5411");
        assertThat(textField(fields, "PA-TRANSACTION-ID")).isEqualTo("TXN000000000100");
        assertThat(textField(fields, "PA-MATCH-STATUS")).isEqualTo("P");
        assertThat(textField(fields, "PA-AUTH-FRAUD")).isEmpty();
        assertThat(textField(fields, "PA-FRAUD-RPT-DATE")).isEmpty();
    }

    /**
     * Confirms the fraud-marked detail fixture carries the state the fraud write produces.
     */
    @Test
    @DisplayName("the fraud-marked detail fixture carries the flag, status and report date")
    void fraudMarkedDetailFixtureCarriesTheFraudState() {
        Map<String, Object> fields = FixedWidthCodec.decodeRecord(
                bytesOf("pautdtl-fraud-marked.bin"), CopybookLayout.layout("PAUTDTL"));

        assertThat(textField(fields, "PA-AUTH-FRAUD")).isEqualTo("F");
        assertThat(textField(fields, "PA-MATCH-STATUS")).isEqualTo("M");
        assertThat(textField(fields, "PA-FRAUD-RPT-DATE")).isEqualTo("20240405");
    }

    /**
     * Confirms the match-status fixture holds one record per admitted status, in declaration order.
     *
     * <p>Assumptions: the order is asserted, not just the set, because the copybook declares its four
     * condition names in a fixed order and a fixture that shuffled them would still contain every
     * value while no longer documenting which record carries which.</p>
     */
    @Test
    @DisplayName("the match-status fixture holds P, D, E and M in copybook declaration order")
    void matchStatusFixtureHoldsTheClosedDomainInOrder() {
        RecordSpec spec = CopybookLayout.layout("PAUTDTL");
        byte[] image = bytesOf("pautdtl-match-status-domain.bin");
        assertThat(image.length / spec.reclen()).isEqualTo(4);

        List<String> statuses = new ArrayList<>();
        for (int ordinal = 0; ordinal < 4; ordinal++) {
            statuses.add(textField(
                    FixedWidthCodec.decodeRecord(recordAt(image, ordinal, spec.reclen()), spec),
                    "PA-MATCH-STATUS"));
        }
        assertThat(statuses).containsExactly("P", "D", "E", "M");
    }

    /**
     * Confirms the purge pair's detail amounts reproduce its parent summary's counters exactly.
     *
     * <p>Assumptions: this is the summary-to-detail correspondence assertion, and it is arithmetic
     * rather than a shared key because the detail segment carries no account identifier -- the IMS
     * parent-child relation supplied it. Summing the children's amounts by response code and
     * comparing against the parent's two counters and two totals is the strongest correspondence the
     * two layouts admit.</p>
     */
    @Test
    @DisplayName("the purge children's amounts reproduce their parent summary's counters exactly")
    void purgeChildrenCorrespondToTheirParentSummary() {
        Map<String, Object> parent = FixedWidthCodec.decodeRecord(
                bytesOf("pautsum0-purge-parent.bin"), CopybookLayout.layout("PAUTSUM0"));

        RecordSpec detailSpec = CopybookLayout.layout("PAUTDTL");
        byte[] children = bytesOf("pautdtl-purge-children.bin");
        int recordCount = children.length / detailSpec.reclen();

        int approvedCount = 0;
        int declinedCount = 0;
        Money approvedTotal = Money.of("0.00");
        Money declinedTotal = Money.of("0.00");
        for (int ordinal = 0; ordinal < recordCount; ordinal++) {
            Map<String, Object> child = FixedWidthCodec.decodeRecord(
                    recordAt(children, ordinal, detailSpec.reclen()), detailSpec);
            Money amount = Money.of(amountField(child, "PA-TRANSACTION-AMT"));
            if ("00".equals(textField(child, "PA-AUTH-RESP-CODE"))) {
                approvedCount++;
                approvedTotal = approvedTotal.plus(amount);
            } else {
                declinedCount++;
                declinedTotal = declinedTotal.plus(amount);
            }
        }

        assertThat(recordCount).isEqualTo(4);
        assertThat(approvedCount)
                .isEqualTo(amountField(parent, "PA-APPROVED-AUTH-CNT").intValueExact());
        assertThat(declinedCount)
                .isEqualTo(amountField(parent, "PA-DECLINED-AUTH-CNT").intValueExact());
        assertThat(approvedTotal.amount())
                .isEqualByComparingTo(amountField(parent, "PA-APPROVED-AUTH-AMT"));
        assertThat(declinedTotal.amount())
                .isEqualByComparingTo(amountField(parent, "PA-DECLINED-AUTH-AMT"));
    }

    /**
     * Confirms a declined child carries a zero approved amount.
     *
     * <p>Assumptions: this is asserted separately from the totals above, because a declined record
     * whose approved amount equalled its requested amount would leave the two parent totals correct
     * while publishing an approval that never happened.</p>
     */
    @Test
    @DisplayName("a declined authorization carries a zero approved amount")
    void aDeclinedChildCarriesNoApprovedAmount() {
        RecordSpec spec = CopybookLayout.layout("PAUTDTL");
        byte[] children = bytesOf("pautdtl-purge-children.bin");

        for (int ordinal = 0; ordinal < children.length / spec.reclen(); ordinal++) {
            Map<String, Object> child =
                    FixedWidthCodec.decodeRecord(recordAt(children, ordinal, spec.reclen()), spec);
            if (!"00".equals(textField(child, "PA-AUTH-RESP-CODE"))) {
                assertThat(amountField(child, "PA-APPROVED-AMT")).isEqualByComparingTo("0.00");
                assertThat(textField(child, "PA-MATCH-STATUS")).isEqualTo("D");
            }
        }
    }

    /**
     * Confirms the two unload fixtures carry the same two accounts in opposite orders.
     *
     * <p>Assumptions: the pair is asserted as a pair. Each file alone would be satisfied by a reader
     * that sorted its output, and it is exactly that sort which would destroy the unload order the
     * two files exist to distinguish.</p>
     */
    @Test
    @DisplayName("the two unload fixtures carry the same accounts in opposite orders")
    void theUnloadFixturesCarryOppositeOrders() {
        assertThat(unloadedAccounts("unload-gsam-summary-100.bin"))
                .containsExactly("10000000001", "10000000002");
        assertThat(unloadedAccounts("unload-prefixed-summary-100.bin"))
                .containsExactly("10000000002", "10000000001");
        assertThat(unloadedAccounts("unload-gsam-summary-100.bin"))
                .containsExactlyInAnyOrderElementsOf(
                        unloadedAccounts("unload-prefixed-summary-100.bin"));
    }

    /**
     * Confirms a decode-only fixture's negatively-signed zero reads as an unsigned zero.
     *
     * <p>Assumptions: the sign is asserted through {@link BigDecimal#signum()} as well as through
     * equality, because {@code new BigDecimal("-0.00").compareTo(BigDecimal.ZERO)} is zero -- an
     * equality check alone would pass for the very value the normalisation exists to prevent.</p>
     *
     * @param name the decode-only fixture under test
     * @param layoutName the registry layout it is written against
     * @param moneyField the money field carrying the negatively-signed zero
     */
    @ParameterizedTest
    @CsvSource({
        "pautsum0-negative-zero-decode-only.bin, PAUTSUM0, PA-CASH-BALANCE",
        "pautdtl-negative-zero-decode-only.bin, PAUTDTL, PA-TRANSACTION-AMT",
        "pautdtl-negative-zero-decode-only.bin, PAUTDTL, PA-APPROVED-AMT",
    })
    @DisplayName("a negatively-signed packed zero decodes as an unsigned zero")
    void aNegativelySignedZeroDecodesUnsigned(String name, String layoutName, String moneyField) {
        Map<String, Object> fields =
                FixedWidthCodec.decodeRecord(bytesOf(name), CopybookLayout.layout(layoutName));
        BigDecimal decoded = amountField(fields, moneyField);

        assertThat(decoded).isEqualByComparingTo("0.00");
        assertThat(decoded.signum()).isZero();
    }

    /**
     * Confirms a value-bearing trailing filler survives the decode instead of being blanked.
     *
     * @param name the fixture whose filler carries content
     * @param layoutName the registry layout it is written against
     */
    @ParameterizedTest
    @CsvSource({
        "pautsum0-filler-nonblank.bin, PAUTSUM0",
        "pautdtl-filler-nonblank.bin, PAUTDTL",
    })
    @DisplayName("a value-bearing trailing filler is preserved, not rebuilt as blanks")
    void aValueBearingFillerIsPreserved(String name, String layoutName) {
        RecordSpec spec = CopybookLayout.layout(layoutName);
        byte[] record = bytesOf(name);
        Map<String, Object> fields = FixedWidthCodec.decodeRecord(record, spec);

        assertThat(textField(fields, "FILLER")).isNotEmpty().isNotBlank();
        assertThat(FixedWidthCodec.encodeRecordPreservingSign(fields, spec, record))
                .isEqualTo(record);
    }

    /**
     * Confirms terminator-shaped bytes inside a field are data and not a record boundary.
     *
     * <p>Assumptions: the RECORD COUNT is asserted as well as the content, because a reader that split
     * on a terminator would produce a different number of records, and that is the failure mode the
     * fixture exists to catch. Asserting only the field content would pass for a reader that split and
     * then re-padded.</p>
     *
     * @param name the terminator fixture under test
     */
    @ParameterizedTest
    @ValueSource(strings = {
        "pautsum0-line-terminator-bytes.bin",
        "pautdtl-line-terminator-bytes.bin",
    })
    @DisplayName("terminator-shaped bytes inside a field never split a record")
    void terminatorBytesNeverSplitARecord(String name) {
        String layoutName = name.startsWith("pautsum0") ? "PAUTSUM0" : "PAUTDTL";
        RecordSpec spec = CopybookLayout.layout(layoutName);
        byte[] image = bytesOf(name);

        assertThat(image.length / spec.reclen()).isEqualTo(2);
        assertThat(new String(image, StandardCharsets.US_ASCII))
                .as("%s carries at least one terminator-shaped byte", name)
                .containsAnyOf("\n", "\r", "\u0015", "\u0025");

        for (int ordinal = 0; ordinal < 2; ordinal++) {
            byte[] record = recordAt(image, ordinal, spec.reclen());
            assertThat(record).hasSize(spec.reclen());
            assertThat(FixedWidthCodec.encodeRecordPreservingSign(
                    FixedWidthCodec.decodeRecord(record, spec), spec, record)).isEqualTo(record);
        }
    }

    /**
     * Confirms a truncated binary record is refused rather than decoded as a whole one.
     */
    @Test
    @DisplayName("a truncated binary record is refused, not decoded short")
    void aTruncatedBinaryRecordIsRefused() {
        RecordSpec spec = CopybookLayout.layout("PAUTDTL");
        byte[] record = bytesOf("pautdtl-canonical.bin");
        byte[] truncated = new byte[record.length - 1];
        System.arraycopy(record, 0, truncated, 0, truncated.length);

        assertThatThrownBy(() -> FixedWidthCodec.decodeRecord(truncated, spec))
                .isInstanceOf(RuntimeException.class);
    }

    /**
     * Returns the account identifiers of an unload fixture, in the order the file stores them.
     *
     * @param name the unload fixture resource name
     * @return one account identifier per record, in file order
     */
    private static List<String> unloadedAccounts(String name) {
        RecordSpec spec = CopybookLayout.layout("PAUTSUM0");
        byte[] image = bytesOf(name);

        List<String> accounts = new ArrayList<>();
        for (int ordinal = 0; ordinal < image.length / spec.reclen(); ordinal++) {
            Map<String, Object> fields =
                    FixedWidthCodec.decodeRecord(recordAt(image, ordinal, spec.reclen()), spec);
            accounts.add(amountField(fields, "PA-ACCT-ID").toBigIntegerExact().toString());
        }
        return accounts;
    }
}
