package com.carddemo.batch.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Records how far into one accumulating feed the posting step has already consumed.
 *
 * <p>Refactoring Rationale: this entity exists because the migrated posting pass had no notion of
 * "tonight's input". In the reference, {@code app/jcl/POSTTRAN.jcl:30-31} supplies the feed as the
 * flat sequential dataset {@code AWS.M2.CARDDEMO.DALYTRAN.PS} and {@code CBTRN02C} reads it to end
 * of file -- {@code app/cbl/CBTRN02C.cbl:29-32} declares it {@code ORGANIZATION IS SEQUENTIAL} with
 * no record key and the driver at {@code :202-219} advances it once, front to back. The dataset is
 * replaced between runs, so "the whole file" and "tonight's transactions" are the same set and the
 * program needs no cursor. The target's feed is a table that ACCUMULATES, because its rows are the
 * audit trail the three verification passes compare against, so a walk that started at the
 * beginning re-posted every previous night on every subsequent night -- adding those amounts to
 * account balances again and inserting a second posted row for each. This row carries the identity
 * the replaced dataset used to carry.</p>
 *
 * <h2>What the stored ordinal means</h2>
 *
 * <p>Assumptions: {@code lastIngestSeq} is an EXCLUSIVE upper bound on what has been consumed --
 * the ordinal of the last row posted -- so the next pass reads strictly greater than it. That
 * matches {@code DailyTransactionRepository}'s continuation finder, which is strictly greater for
 * the reason its own contract records: an inclusive bound re-delivers a row already posted, and
 * under the additive posting model of {@code app/cbl/CBTRN02C.cbl:202-219} a re-delivered row is a
 * double-counted amount rather than a harmless repeat.</p>
 *
 * <p>Assumptions: the ordinal is the feed's own {@code ingest_seq}, which
 * {@code services/transaction-service/src/main/resources/db/migration/V1__ledger.sql} declares
 * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} and keys the feed table on alone. It is a total
 * order assigned by a single-writer sequential load, which is what makes it usable as a cursor at
 * all; the feed's processing timestamp cannot serve, being blank on every unposted row.</p>
 *
 * <p>Assumptions: ABSENCE of a row means the feed has never been consumed, and no row is seeded by
 * the migration. The two diagnostic columns and the timestamp are therefore all {@code NOT NULL}:
 * every stored row was written by a run that really did consume something, so there is no state in
 * which they would have to be invented.</p>
 *
 * @see com.carddemo.batch.repository.DailyFeedWatermarkRepository
 */
@Entity
@Table(
        // WHY : Assumptions: Flyway migration V2__batch_feed_watermark.sql is the sole DDL source
        //       of truth for this table; the provider validates this shape and never creates or
        //       alters it, exactly as for BatchRun beside it.
        name = "daily_feed_watermark",
        // WHY : Assumptions: the schema is stated rather than inherited from the connection search
        //       path, for the reason BatchRun states: this module reaches four schemas under
        //       different grants, so the owning schema belongs at the mapping where a reader
        //       auditing the ownership boundary will see it.
        schema = "batch")
public class DailyFeedWatermark {

    /** Widths mirrored from V2__batch_feed_watermark.sql so mapping and DDL cannot drift. */
    private static final int FEED_NAME_MAX_LENGTH = 30;

    /** Width of the orchestrator execution identifier, matching {@code batch.batch_run.run_id}. */
    private static final int RUN_ID_MAX_LENGTH = 80;

    /**
     * Width of the business-date token, which {@code BusinessDate} fixes at ten characters.
     *
     * <p>Assumptions: the token is stored as CHARACTERS and not as a date, because
     * {@code com.carddemo.batch.dto.BusinessDate} admits both the compact layout the reference
     * injects at {@code app/jcl/INTCALC.jcl:22} and the separated ISO layout the migrated chain
     * injects, and carries whichever arrived verbatim. Parsing to store it would throw on the
     * compact form and would record something other than what the run was given.</p>
     */
    private static final int BUSINESS_DATE_TOKEN_LENGTH = 10;

    /**
     * Record-layout name of the feed this row governs, and the primary key.
     *
     * <p>Assumptions: the vocabulary is the RECORD LAYOUT name the migration registry, the
     * verification passes and the runbook all use -- {@code DALYTRAN} -- rather than the table name
     * or a service name, so one word names the feed everywhere it is discussed.</p>
     */
    @Id
    @Column(name = "feed_name", nullable = false, length = FEED_NAME_MAX_LENGTH)
    private String feedName;

    /** Ingestion ordinal of the last row consumed, an exclusive lower bound for the next pass. */
    @Column(name = "last_ingest_seq", nullable = false)
    private long lastIngestSeq;

    /** Orchestrator execution that last advanced this watermark. Diagnostic only. */
    @Column(name = "run_id", nullable = false, length = RUN_ID_MAX_LENGTH)
    private String runId;

    /** Injected business-date token of the run that last advanced this watermark. Diagnostic only. */
    @Column(name = "business_date", nullable = false, length = BUSINESS_DATE_TOKEN_LENGTH)
    private String businessDate;

    /** When the watermark was last advanced, zone-less to match {@code batch.batch_run}. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Creates an unpopulated instance for the persistence provider.
     *
     * <p>Assumptions: the provider requires a no-argument constructor and this one exists only for
     * it. It is {@code protected} rather than public so application code cannot reach a state with
     * no feed name, which the validating constructor below refuses.</p>
     */
    protected DailyFeedWatermark() {
        // Deliberately empty: the provider populates the fields through reflection.
    }

    /**
     * Creates a watermark row for one feed at one consumed position.
     *
     * @param feedName the record-layout name of the feed, for example {@code DALYTRAN}; must not be
     *     {@code null}, must not be blank, and must not exceed the mapped width
     * @param lastIngestSeq the ingestion ordinal of the last row consumed, as a {@code long}; must
     *     not be negative, and zero means nothing has been consumed
     * @param runId the orchestrator execution advancing the watermark; must not be {@code null},
     *     must not be blank, and must not exceed the mapped width
     * @param businessDate the injected business-date token of that run, a {@code String} of exactly
     *     ten characters; must not be {@code null}
     * @param updatedAt the moment the advance was recorded, as a {@code LocalDateTime}; must not be
     *     {@code null}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalArgumentException if a string argument is blank or exceeds its mapped width, if
     *     the business-date token is not exactly ten characters, or if the ordinal is negative -- each
     *     of which the column's own check constraint would refuse at the database, and refusing here
     *     names the offending value instead of the constraint
     */
    public DailyFeedWatermark(String feedName, long lastIngestSeq, String runId,
            String businessDate, LocalDateTime updatedAt) {

        this.feedName = requireBoundedText(feedName, FEED_NAME_MAX_LENGTH, "feedName");
        // WHY : Assumptions: the ordinal is validated here as well as by the column's check
        //       constraint, because a negative ordinal reaching the database would be reported as a
        //       constraint violation naming the constraint and not the value, and this row is
        //       written at the END of a posting pass -- so the diagnosis would arrive attached to
        //       the commit of a night's work rather than to the arithmetic that produced it.
        if (lastIngestSeq < 0L) {
            throw new IllegalArgumentException(
                    "lastIngestSeq must not be negative but was " + lastIngestSeq);
        }
        this.lastIngestSeq = lastIngestSeq;
        this.runId = requireBoundedText(runId, RUN_ID_MAX_LENGTH, "runId");
        this.businessDate = requireBusinessDateToken(businessDate);
        this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
    }

    /**
     * Moves this row to a new consumed position, recording which run got there.
     *
     * <p>Assumptions: the caller has already established that the new ordinal is higher. This
     * method does not compare, because the comparison belongs where the decision is -- the service
     * that owns the advance skips the write entirely when nothing was consumed, and a monotonicity
     * check here would either duplicate that or silently accept a no-op the caller thought had
     * happened.</p>
     *
     * @param ordinal the ingestion ordinal of the last row consumed by this run, as a {@code long};
     *     must not be negative
     * @param advancingRunId the orchestrator execution advancing the watermark; must not be
     *     {@code null}, must not be blank, and must not exceed the mapped width
     * @param date the injected business-date token of that run, a {@code String} of exactly ten
     *     characters; must not be {@code null}
     * @param at the moment the advance was recorded, as a {@code LocalDateTime}; must not be
     *     {@code null}
     * @throws NullPointerException if any reference argument is {@code null}
     * @throws IllegalArgumentException if the ordinal is negative, the run identifier is blank or
     *     over-wide, or the business-date token is not exactly ten characters
     */
    public void advanceTo(long ordinal, String advancingRunId, String date, LocalDateTime at) {
        if (ordinal < 0L) {
            throw new IllegalArgumentException("ordinal must not be negative but was " + ordinal);
        }
        this.lastIngestSeq = ordinal;
        this.runId = requireBoundedText(advancingRunId, RUN_ID_MAX_LENGTH, "advancingRunId");
        this.businessDate = requireBusinessDateToken(date);
        this.updatedAt = Objects.requireNonNull(at, "at must not be null");
    }

    /**
     * Reports the feed this row governs.
     *
     * @return the record-layout name of the feed, never {@code null} on a persisted row
     */
    public String getFeedName() {
        return this.feedName;
    }

    /**
     * Reports the exclusive lower bound the next pass reads from.
     *
     * @return the ingestion ordinal of the last row consumed, never negative
     */
    public long getLastIngestSeq() {
        return this.lastIngestSeq;
    }

    /**
     * Reports the run that last advanced this watermark.
     *
     * @return the orchestrator execution identifier, never {@code null} on a persisted row
     */
    public String getRunId() {
        return this.runId;
    }

    /**
     * Reports the business-date token of the run that last advanced this watermark.
     *
     * @return the injected token, ten characters, never {@code null} on a persisted row
     */
    public String getBusinessDate() {
        return this.businessDate;
    }

    /**
     * Reports when the watermark was last advanced.
     *
     * @return the recorded moment, never {@code null} on a persisted row
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Validates a business-date token against the one property the column constrains, its width.
     *
     * <p>Assumptions: the check is on LENGTH alone and is blind to what the ten characters mean,
     * which is exactly the check {@code com.carddemo.batch.dto.BusinessDate} performs and for the
     * same reason: both the compact and the separated layout are legitimate, and no reference
     * program parses the token before using it.</p>
     *
     * @param token the candidate token; must not be {@code null} and must be exactly ten characters
     * @return the token unchanged, never {@code null}
     * @throws NullPointerException if {@code token} is {@code null}
     * @throws IllegalArgumentException if the token is not exactly ten characters
     */
    private static String requireBusinessDateToken(String token) {
        Objects.requireNonNull(token, "businessDate must not be null");
        if (token.length() != BUSINESS_DATE_TOKEN_LENGTH) {
            throw new IllegalArgumentException("businessDate must be exactly "
                    + BUSINESS_DATE_TOKEN_LENGTH + " characters but was " + token.length());
        }
        return token;
    }

    /**
     * Validates one bounded, non-blank text value against its mapped width.
     *
     * @param value the candidate value; must not be {@code null} or blank
     * @param maxLength the mapped column width, as an {@code int}
     * @param field the field name, used only in the diagnostics; must not be {@code null}
     * @return the value unchanged, never {@code null}
     * @throws NullPointerException if {@code value} is {@code null}
     * @throws IllegalArgumentException if the value is blank or longer than the mapped width
     */
    private static String requireBoundedText(String value, int maxLength, String field) {
        Objects.requireNonNull(value, field + " must not be null");
        // WHY : Assumptions: the value is NOT trimmed before storing, only rejected when blank. The
        //       column's check constraint tests btrim(...) <> '', so a value with significant
        //       leading or trailing space would satisfy the database; trimming here would make the
        //       stored run identifier differ from the one batch.batch_run holds for the same run,
        //       and the two are meant to be comparable by eye.
        if (value.isBlank()) {
            throw new IllegalArgumentException(field + " must not be blank");
        }
        if (value.length() > maxLength) {
            throw new IllegalArgumentException(
                    field + " must not exceed " + maxLength + " characters but was "
                            + value.length());
        }
        return value;
    }
}
