package com.carddemo.transaction.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.carddemo.transaction.domain.Transaction;
import jakarta.persistence.EntityManager;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.data.domain.Limit;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.test.context.ActiveProfiles;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

/**
 * Pins the three ordered access paths of {@code ledger.transactions} onto a real PostgreSQL engine,
 * together with the two facts every other test in this package depends on and none of them should
 * re-assert: that Flyway applied the migration, and that an unqualified entity resolves to
 * {@code ledger} rather than to whatever else the connection can see.
 *
 * <p>Assumptions: the engine is real and not a substitute. What this class covers is engine-specific
 * -- the keyset access paths and the deliberately NON-UNIQUE index over the processing timestamp. That
 * index is the surviving half of the batch alternate index over {@code TRAN-PROC-TS}, and its
 * non-uniqueness is load-bearing rather than incidental: many transactions share one processing
 * timestamp, so a unique index would reject the second row of any posting run. In PostgreSQL a plain
 * {@code CREATE INDEX} is non-unique, so the property is carried by the ABSENCE of {@code UNIQUE} in
 * the migration -- which means a test that cannot insert two rows sharing one timestamp is not meeting
 * a fussier engine, it is observing a broken contract and must fail.
 *
 * <p>Assumptions: connection coordinates arrive as a bean and never as text. The container field below
 * carries {@code @ServiceConnection}, which contributes a {@code JdbcConnectionDetails} bean that the
 * auto-configuration reads in preference to any {@code spring.datasource} property, so no URL, host,
 * port, user name or password appears anywhere in this file. The container's port is assigned at run
 * time, so a written connection string would either address nothing or address whichever database
 * happens to be listening on the author's machine -- and the second failure mode is the worse of the
 * two, because it passes.
 *
 * <p>Trade-offs: {@code @ActiveProfiles("test")} is load-bearing rather than conventional. The profile
 * document holds the only surviving mechanism that reaches the {@code ledger} schema inside a container
 * database that starts empty -- its Flyway and Hibernate default-schema settings together with its
 * create-schemas allowance -- because the JDBC URL is generated by the container and a pooled
 * search-path statement cannot report failure, PostgreSQL accepting a path that names an absent
 * schema. Omitting the annotation does not degrade a run, it fails it on a missing schema before any
 * assertion executes.
 *
 * <p>Alternatives Considered: authoring the module's missing {@code @SpringBootApplication} class so
 * that the test context could find a configuration the ordinary way. Rejected as out of scope and as
 * the wrong shape: that class is a production artifact this checkpoint does not land, and adding one
 * solely to satisfy a test would put a deployable entry point in the tree ahead of the controllers it
 * would have to serve. The nested configuration below is declared in this file instead of as a sixth
 * member of this package, because the package charter closes the file set at five and a test-only
 * configuration is not one of the five.
 *
 * <p>A test class accepts no parameter, yields no value and raises nothing, so this block carries no
 * parameter, return or exception at-clause; the members below carry their own.
 */
@Testcontainers
@SpringBootTest(
        classes = TransactionRepositoryIT.LedgerPersistenceTestApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test")
class TransactionRepositoryIT {

    /**
     * The engine the assertions run against, pinned to the major version the deployed cluster targets.
     *
     * <p>Assumptions: the tag is pinned rather than floating because the properties under test are
     * engine behaviours -- index uniqueness semantics and keyset ordering -- and a floating tag would
     * let those behaviours change without any change in this repository. The Alpine variant is used
     * because it starts faster and this suite starts one container per class.
     *
     * <p>Assumptions: the type comes from {@code org.testcontainers.postgresql} and NOT from
     * {@code org.testcontainers.containers}. Testcontainers 2.0.5 ships both -- the module jar carries
     * {@code org/testcontainers/postgresql/PostgreSQLContainer.class} alongside the legacy
     * {@code org/testcontainers/containers/PostgreSQLContainer.class} -- and only the legacy one is
     * deprecated. Alternatives Considered: keeping the legacy import and suppressing the notice;
     * rejected because the deprecation is the library telling this repository where the type now lives,
     * and suppressing it would carry a compile-time notice into every future build of this module for
     * no benefit. Trade-offs: the replacement is not generic, so the declaration loses the
     * {@code <?>} wildcard and the self-type it parameterised; nothing here relied on that self-type,
     * because the container is configured entirely through {@code @ServiceConnection} rather than by
     * chained builder calls whose return type the parameter existed to refine.
     */
    @Container
    @ServiceConnection
    static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:17-alpine");

    /** The repository under test. */
    @Autowired
    private TransactionRepository transactions;

    /**
     * Used to read the schema an unqualified entity actually resolved to.
     *
     * <p>Assumptions: the resolution is asserted through a native query rather than by inspecting
     * configuration, because a configured default schema and an effective one are different facts and
     * only the second one matters to every other test in this package.
     */
    @Autowired
    private EntityManager entityManager;

    /** The processing timestamp two rows deliberately share, to exercise the non-unique index. */
    private static final LocalDateTime SHARED_PROC_TS =
            LocalDateTime.of(2022, 7, 18, 0, 0, 0, 0);

    /**
     * Empties the table before each case.
     *
     * <p>Assumptions: each case seeds exactly the rows it reasons about, so a case cannot pass on a
     * row another case left behind. Deleting rather than recreating the schema keeps the Flyway
     * migration applied once per container, which is what makes the migration assertion below a
     * statement about the migration rather than about this method.
     */
    @BeforeEach
    void clearTable() {
        this.transactions.deleteAll();
    }

    /**
     * Confirms Flyway applied the module's migration and that an unqualified entity resolves to
     * {@code ledger}.
     *
     * <p>Assumptions: both halves are asserted here and nowhere else in this package. The schema is
     * read back from the engine's own catalogue for the table the entity maps to, so a mapping that
     * resolved to a different schema -- {@code public}, most plausibly, on a container database that
     * starts with one -- fails here with the schema it found rather than failing later as a missing
     * column.
     */
    @Test
    void theMigrationIsAppliedAndTheEntityResolvesToTheLedgerSchema() {
        Object schema = this.entityManager
                .createNativeQuery("select table_schema from information_schema.tables"
                        + " where table_name = 'transactions'")
                .getSingleResult();

        assertThat(schema).isEqualTo("ledger");

        Object migrated = this.entityManager
                .createNativeQuery("select count(*) from flyway_schema_history"
                        + " where success = true")
                .getSingleResult();

        assertThat(((Number) migrated).intValue()).isPositive();
    }

    /**
     * Confirms the primary-key path round-trips a row through the {@code CHAR(16)} key.
     *
     * <p>Assumptions: the identifier is written at exactly sixteen characters and read back
     * unchanged, which is the property the explicit fixed-length JDBC binding exists to protect. A
     * variable-length binding would leave a stored blank-padded value comparing unequal to the
     * unpadded value bound on lookup, and the failure would appear as a row that cannot be found
     * rather than as anything about a type.
     */
    @Test
    void thePrimaryKeyPathRoundTripsTheFixedWidthIdentifier() {
        this.transactions.save(posted("0000000000683580", "4859452612877065", SHARED_PROC_TS));

        assertThat(this.transactions.findById("0000000000683580")).isPresent();
        assertThat(this.transactions.findMaxTranId()).contains("0000000000683580");
    }

    /**
     * Confirms two rows may share one processing timestamp, proving the index is not unique.
     *
     * <p>Assumptions: this is the one case in the suite whose failure means the migration is wrong
     * rather than the test. A {@code UNIQUE} index over the processing timestamp would reject the
     * second row of any posting run, because a run stamps every row it posts with the same instant.
     */
    @Test
    void twoRowsMayShareOneProcessingTimestampBecauseTheIndexIsNotUnique() {
        this.transactions.save(posted("0000000000683580", "4859452612877065", SHARED_PROC_TS));
        this.transactions.save(posted("0000000000683581", "4859452612877065", SHARED_PROC_TS));

        List<Transaction> both = this.transactions.findAllByOrderByTranIdAsc(Limit.of(10));

        assertThat(both).hasSize(2);
        assertThat(both).allSatisfy(row -> assertThat(row.getProcTs()).isEqualTo(SHARED_PROC_TS));
    }

    /**
     * Confirms the card-ordered path returns only that card's rows, in identifier order.
     *
     * <p>Assumptions: a second card is seeded so the assertion can fail. A single-card fixture would
     * pass against a query that ignored its argument entirely, which is the defect most worth catching
     * on a derived query whose predicate is expressed only in its method name.
     */
    @Test
    void theCardOrderedPathReturnsOnlyThatCardsRowsInIdentifierOrder() {
        this.transactions.save(posted("0000000000683580", "4859452612877065", SHARED_PROC_TS));
        this.transactions.save(posted("0000000000683582", "4859452612877065", SHARED_PROC_TS));
        this.transactions.save(posted("0000000000683581", "0927987108636232", SHARED_PROC_TS));

        List<Transaction> mine =
                this.transactions.findByCardNumOrderByTranIdAsc("4859452612877065", Limit.of(10));

        assertThat(mine).extracting(Transaction::getTranId)
                .containsExactly("0000000000683580", "0000000000683582");
    }

    /**
     * Confirms the forward and backward keyset paths page by key rather than by position.
     *
     * <p>Assumptions: the backward path returns rows in DESCENDING identifier order, which is what
     * makes it the equivalent of the baseline's read-previous rather than a reversed page of the
     * forward query. Asserting the order explicitly is the point: a caller reverses the list for
     * display, so a path that returned ascending rows would look correct on the first page and place
     * the wrong row at the page boundary.
     */
    @Test
    void theKeysetPathsPageForwardAndBackwardByKey() {
        this.transactions.save(posted("0000000000683580", "4859452612877065", SHARED_PROC_TS));
        this.transactions.save(posted("0000000000683581", "4859452612877065", SHARED_PROC_TS));
        this.transactions.save(posted("0000000000683582", "4859452612877065", SHARED_PROC_TS));

        List<Transaction> forward = this.transactions
                .findByTranIdGreaterThanOrderByTranIdAsc("0000000000683580", Limit.of(2));
        List<Transaction> backward = this.transactions
                .findByTranIdLessThanOrderByTranIdDesc("0000000000683582", Limit.of(2));

        assertThat(forward).extracting(Transaction::getTranId)
                .containsExactly("0000000000683581", "0000000000683582");
        assertThat(backward).extracting(Transaction::getTranId)
                .containsExactly("0000000000683581", "0000000000683580");
    }

    /**
     * Builds a posted transaction row carrying every column the migration declares NOT NULL.
     *
     * <p>Assumptions: the card number and amount are demonstration values taken from the published
     * CardDemo seed rather than minted, so nothing here identifies a real person or a real account.
     * The nullable columns are populated too, because a row with only its mandatory columns filled
     * would not exercise the fixed-length bindings on the other four {@code CHAR} members.
     *
     * @param tranId the sixteen-character identifier, which is the primary key
     * @param cardNum the sixteen-character card number
     * @param procTs the processing timestamp, which the table declares NOT NULL
     * @return a transient entity ready to save, never {@code null}
     */
    private Transaction posted(String tranId, String cardNum, LocalDateTime procTs) {
        return new Transaction(tranId, "01", "0001", "POS TERM  ",
                "Purchase at Abshire-Lowe", new BigDecimal("504.77"), 800000000L,
                "Abshire-Lowe", "North Enoshaven", "72112     ", cardNum,
                LocalDateTime.of(2022, 6, 10, 19, 27, 53), procTs);
    }

    /**
     * The minimal Spring Boot configuration this suite runs against.
     *
     * <p>Assumptions: the module lands no {@code @SpringBootApplication} class at this checkpoint, so
     * the test context needs a configuration of its own to find. This one enables auto-configuration
     * and names the two packages the persistence layer occupies, and nothing else -- no web layer, no
     * security filter chain, no API documentation -- because the suite runs with no servlet
     * environment and every additional auto-configured concern is one more way for a persistence
     * assertion to fail for an unrelated reason.
     *
     * <p>Trade-offs: declaring it nested rather than as a file of its own keeps the package charter's
     * five-file set true, at the cost of this configuration not being reusable by the three sibling
     * integration tests the charter plans. When the second of them is authored, the right move is to
     * promote this class into the module's production tree as the real application class, not to copy
     * it -- two nested configurations enabling different auto-configuration subsets would let two
     * tests disagree about the context they share a schema through.
     */
    @SpringBootConfiguration
    @EnableAutoConfiguration
    @EntityScan("com.carddemo.transaction.domain")
    @EnableJpaRepositories("com.carddemo.transaction.repository")
    static class LedgerPersistenceTestApplication {
    }
}
