package com.carddemo.auth.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.Objects;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * One row of {@code auth.identity_sync_task}: a change this context still owes the managed user pool.
 *
 * <p>Purpose: carry, durably and transactionally with the {@code auth.users} change that caused it, the
 * intention to provision, re-project or withdraw a managed identity. A row is written inside the same
 * database transaction as the user-row change and applied after that transaction commits, which is what
 * lets the two stores converge without either being held open across a call to the other.</p>
 *
 * <p>Refactoring Rationale: this entity exists because the three write operations previously called the
 * identity provider from inside their database transaction and described the arrangement as though it
 * made the two stores atomic. It cannot. A provider call that succeeds followed by a commit that fails
 * leaves a pool account with no local row -- for an administrator, signed authority the local store does
 * not record -- and the update path could leave a token minting authorities {@code auth.users} no longer
 * describes. Only a row committed with the data survives a process death between the two stores: after
 * any crash the intended change is either recorded and pending, or absent because the data change never
 * happened. The physical contract, including why the attempt counter is four bytes and why the pending
 * index is partial, is stated in {@code V2__auth_identity_sync.sql}, which owns it.</p>
 *
 * <p>Assumptions: the PROJECTION the provider is to hold is carried on the task rather than re-read when
 * the task is applied, and the reason is not caching. A withdrawal's row is gone by then; and a
 * projection task applied after a later change would otherwise push the LATER values under the EARLIER
 * task's intention, silently reordering two changes an operator asked for in a definite order.</p>
 *
 * <p>Assumptions: this type carries no reference to the identity provider, to any AWS type or to any web
 * type, which is the layering the context's architecture test enforces. It is a mapping from a Java
 * object onto a physical row; deciding what a row MEANS and calling the provider belong to the service
 * layer.</p>
 *
 * <p>Trade-offs: the status transitions are expressed as methods on this type rather than as a state
 * machine held elsewhere, so an invalid transition is refused at the object that owns the field. The cost
 * is three small methods on an entity; the gain is that no caller can mark a task applied twice or revive
 * a settled one, which is the property the idempotent applier depends on.</p>
 */
@Entity
@Table(name = "identity_sync_task", schema = "auth")
public class IdentitySyncTask {

    /** The status of a task still owed to the provider. */
    public static final String STATUS_PENDING = "PENDING";

    /** The status of a task the provider confirmed. */
    public static final String STATUS_APPLIED = "APPLIED";

    /** The status of a task that reached the attempt ceiling and awaits an operator. */
    public static final String STATUS_ABANDONED = "ABANDONED";

    /** The operation that creates a pool account and returns its subject. */
    public static final String OPERATION_PROVISION = "PROVISION";

    /** The operation that brings a pool account's projection and group in line with the row. */
    public static final String OPERATION_SYNCHRONISE = "SYNCHRONISE";

    /** The operation that removes a pool account. */
    public static final String OPERATION_WITHDRAW = "WITHDRAW";

    /**
     * The surrogate key, generated by the database.
     *
     * <p>Assumptions: {@code IDENTITY} and not a table or sequence generator, matching the
     * {@code GENERATED BY DEFAULT AS IDENTITY} column the migration declares and the idiom the sibling
     * outbox in the authorization context already uses. It is also the fair-selection order the applier
     * drains in, so one user's repeated failures cannot starve another user's first task.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "task_id", nullable = false, updatable = false)
    private Long taskId;

    /**
     * The user this task concerns.
     *
     * <p>Assumptions: eight characters, matching {@code SEC-USR-ID PIC X(08)} at line 18 of
     * {@code app/cpy/CSUSR01Y.cpy} and the {@code CHAR(8)} primary key of {@code auth.users}, so the two
     * compare without an implicit cast.</p>
     */
    // WHY : Assumptions: the three fixed-width columns below carry an explicit JDBC type code, because the
    //       provider maps a String to VARCHAR by default while V2__auth_identity_sync.sql declares CHAR --
    //       and the mismatch is not cosmetic. Schema validation is enabled in every profile, so it refuses
    //       to start against a CHAR column mapped as VARCHAR; the User entity states the same code over the
    //       same two physical types for the same reason. Alternatives Considered: widening the columns to
    //       VARCHAR so no annotation were needed. Rejected because the widths are the baseline record's own
    //       -- SEC-USR-ID is X(08) and the type is one character -- and a variable-width column would stop
    //       the database enforcing them.
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "user_id", length = 8, nullable = false, updatable = false)
    private String userId;

    /** Which of the three provider verbs this task expresses. */
    @Column(name = "operation", length = 12, nullable = false, updatable = false)
    private String operation;

    /** The given name the provider is to hold, or {@code null} for a withdrawal. */
    @Column(name = "first_name", length = 20, updatable = false)
    private String firstName;

    /** The family name the provider is to hold, or {@code null} for a withdrawal. */
    @Column(name = "last_name", length = 20, updatable = false)
    private String lastName;

    /**
     * The user type the provider currently holds, or {@code null} when there is nothing to leave.
     *
     * <p>Assumptions: this is carried because a group reassignment is a PAIR of provider operations --
     * leave the old group, join the new -- and the applier cannot derive the old value after the row has
     * already been written with the new one.</p>
     */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "previous_user_type", length = 1, updatable = false)
    private String previousUserType;

    /** The user type the provider is to hold, or {@code null} for a withdrawal. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "user_type", length = 1, updatable = false)
    private String userType;

    /** Whether the task is still owed, was confirmed, or was abandoned. */
    @Column(name = "status", length = 10, nullable = false)
    private String status;

    /** How many times the provider call has been attempted. */
    @Column(name = "attempts", nullable = false)
    private int attempts;

    /** When the task was recorded. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** When the task reached a terminal status, or {@code null} while it is pending. */
    @Column(name = "settled_at")
    private LocalDateTime settledAt;

    /** The stable code of the most recent failure, or {@code null} if none has occurred. */
    @Column(name = "last_failure_code", length = 64)
    private String lastFailureCode;

    /**
     * Required by the persistence provider, which instantiates an entity reflectively before populating
     * it.
     *
     * <p>Assumptions: {@code protected} rather than public, so application code cannot build a task in a
     * state no factory would produce -- a task with no operation and no user, which the columns declare
     * not null and which would fail only at flush.</p>
     */
    protected IdentitySyncTask() {
        // Populated by the persistence provider.
    }

    /**
     * Records one intended change against one user.
     *
     * @param userId the user the change concerns; must not be {@code null}
     * @param operation one of {@link #OPERATION_PROVISION}, {@link #OPERATION_SYNCHRONISE} or
     *     {@link #OPERATION_WITHDRAW}; must not be {@code null}
     * @param firstName the given name the provider is to hold, or {@code null} for a withdrawal
     * @param lastName the family name the provider is to hold, or {@code null} for a withdrawal
     * @param previousUserType the user type the provider currently holds, or {@code null} when there is
     *     no group to leave
     * @param userType the user type the provider is to hold, or {@code null} for a withdrawal
     * @param recordedAt the instant the task was recorded; must not be {@code null}
     * @throws NullPointerException if {@code userId}, {@code operation} or {@code recordedAt} is
     *     {@code null}
     */
    public IdentitySyncTask(String userId, String operation, String firstName, String lastName,
            String previousUserType, String userType, LocalDateTime recordedAt) {
        this.userId = Objects.requireNonNull(userId, "userId must not be null");
        this.operation = Objects.requireNonNull(operation, "operation must not be null");
        this.firstName = firstName;
        this.lastName = lastName;
        this.previousUserType = previousUserType;
        this.userType = userType;
        this.status = STATUS_PENDING;
        this.attempts = 0;
        this.createdAt = Objects.requireNonNull(recordedAt, "recordedAt must not be null");
    }

    /**
     * Returns the surrogate key, or {@code null} before the row is inserted.
     *
     * @return the task identifier, or {@code null} while the task is unsaved
     */
    public Long getTaskId() {
        return this.taskId;
    }

    /**
     * Returns the user this task concerns.
     *
     * @return the eight-character identifier, never {@code null}
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Returns which provider verb this task expresses.
     *
     * @return one of the three operation constants, never {@code null}
     */
    public String getOperation() {
        return this.operation;
    }

    /**
     * Returns the given name the provider is to hold.
     *
     * @return the given name, or {@code null} for a withdrawal
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Returns the family name the provider is to hold.
     *
     * @return the family name, or {@code null} for a withdrawal
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Returns the user type the provider currently holds.
     *
     * @return the previous user type, or {@code null} when there is no group to leave
     */
    public String getPreviousUserType() {
        return this.previousUserType;
    }

    /**
     * Returns the user type the provider is to hold.
     *
     * @return the intended user type, or {@code null} for a withdrawal
     */
    public String getUserType() {
        return this.userType;
    }

    /**
     * Returns whether the task is pending, applied or abandoned.
     *
     * @return one of the three status constants, never {@code null}
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Returns how many times the provider call has been attempted.
     *
     * @return the attempt count, never negative
     */
    public int getAttempts() {
        return this.attempts;
    }

    /**
     * Returns when the task was recorded.
     *
     * @return the recording instant, never {@code null} once constructed
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Returns when the task reached a terminal status.
     *
     * @return the settling instant, or {@code null} while the task is pending
     */
    public LocalDateTime getSettledAt() {
        return this.settledAt;
    }

    /**
     * Returns the stable code of the most recent failure.
     *
     * @return the failure code, or {@code null} if no attempt has failed
     */
    public String getLastFailureCode() {
        return this.lastFailureCode;
    }

    /**
     * Reports whether this task is still owed to the provider.
     *
     * @return {@code true} while the status is pending
     */
    public boolean isPending() {
        return STATUS_PENDING.equals(this.status);
    }

    /**
     * Marks the task confirmed by the provider.
     *
     * <p>Assumptions: this is refused on a task that is not pending, which is what makes double
     * application detectable rather than silent. The applier reads a task, calls the provider and marks
     * it; if two appliers overlap, the second one's mark fails here rather than overwriting a settled
     * row's timestamp with a later one.</p>
     *
     * @param settledAt the instant the provider confirmed the change; must not be {@code null}
     * @throws NullPointerException if {@code settledAt} is {@code null}
     * @throws IllegalStateException if the task is not pending
     */
    public void markApplied(LocalDateTime settledAt) {
        requirePending("applied");
        this.status = STATUS_APPLIED;
        this.settledAt = Objects.requireNonNull(settledAt, "settledAt must not be null");
        this.lastFailureCode = null;
    }

    /**
     * Records a failed attempt, abandoning the task once the ceiling is reached.
     *
     * <p>Refactoring Rationale: the counter is incremented exactly ONCE per attempt and the ceiling is
     * applied in the same call, so a task whose provider call can never succeed stops being retried and
     * stops hiding the tasks queued behind it. A counter incremented in two places, or a ceiling checked
     * somewhere else, is how an attempt limit turns into an unbounded retry.</p>
     *
     * @param failureCode the stable code of the fault, derived from its type and never from its message;
     *     must not be {@code null}
     * @param ceiling the number of attempts after which the task is abandoned; must be positive
     * @param observedAt the instant of the attempt, recorded only when the task is abandoned; must not be
     *     {@code null}
     * @throws NullPointerException if {@code failureCode} or {@code observedAt} is {@code null}
     * @throws IllegalArgumentException if {@code ceiling} is not positive
     * @throws IllegalStateException if the task is not pending
     */
    public void recordFailedAttempt(String failureCode, int ceiling, LocalDateTime observedAt) {
        requirePending("failed");
        Objects.requireNonNull(failureCode, "failureCode must not be null");
        Objects.requireNonNull(observedAt, "observedAt must not be null");
        if (ceiling <= 0) {
            throw new IllegalArgumentException(
                    "ceiling must be positive; a non-positive ceiling abandons every task on its first"
                            + " attempt and would make the ledger unable to retry anything");
        }
        this.attempts = this.attempts + 1;
        this.lastFailureCode = failureCode;
        if (this.attempts >= ceiling) {
            this.status = STATUS_ABANDONED;
            this.settledAt = observedAt;
        }
    }

    /**
     * Refuses a transition on a task that has already been settled.
     *
     * @param transition the transition being attempted, reproduced in the refusal so it names which one
     *     failed
     * @throws IllegalStateException if the task is not pending
     */
    private void requirePending(String transition) {
        if (!isPending()) {
            throw new IllegalStateException("identity sync task " + this.taskId + " is " + this.status
                    + " and cannot be marked " + transition
                    + "; a settled task is terminal so that a second applier cannot revive it");
        }
    }
}
