-- =============================================================================
-- V2__auth_identity_sync.sql -- the durable intended-change ledger for the AUTH
--                               bounded context's managed-identity provider
-- =============================================================================
--
-- Purpose:
--   Record, transactionally with the row change that caused it, the change that
--   still has to be applied to the managed user pool. One row here is one
--   intended change: provision an account, bring an account's projection in
--   line, or withdraw an account. The row is written inside the same database
--   transaction as the user-row change and applied AFTER that transaction
--   commits, so the two stores converge without either one being held open
--   across a call to the other.
--
-- WHY (Refactoring Rationale):
--   The three write operations previously called the identity provider from
--   INSIDE their database transaction and documented that arrangement as though
--   it made the two stores atomic. It cannot: a provider call that succeeds
--   followed by a commit that fails leaves a pool account whose local row does
--   not exist, and for an administrator that means signed authority the local
--   store does not record. The update path had the sharper version of the same
--   problem -- a group reassignment that succeeded and then rolled back left a
--   token minting authorities auth.users no longer describes -- and the delete
--   path held a transaction open across network latency while removing an
--   identity it might have to put back. A ledger row is the only construction
--   that survives a process death between the two stores: it commits with the
--   data, so after any crash the intended change is either recorded and
--   pending, or absent because the data change never happened.
--
-- WHY (Alternatives Considered):
--   (1) Two-phase commit across PostgreSQL and the identity provider. Not
--       available: the provider exposes no transaction manager and enlists in no
--       coordinator, so there is nothing to prepare.
--   (2) Ordering the calls so the recoverable direction is taken and accepting
--       the divergence, which is what the delete path documented. Rejected
--       because "recoverable" there meant recoverable BY AN OPERATOR who first
--       has to notice, and nothing recorded that there was anything to notice.
--   (3) Retrying the provider call in-process until it succeeds. Rejected
--       because a retry loop inside a request cannot outlive the request: a task
--       restart during the loop loses the intention entirely, which is the exact
--       failure this table exists to make impossible.
--
-- WHY (Trade-offs):
--   The pool converges a moment after the commit rather than at it, so a caller
--   that creates an administrator and immediately signs in as one could in
--   principle race the group assignment. That window is bounded by one provider
--   call and is the price of never leaving the two stores permanently
--   disagreeing; the previous arrangement had no window and no bound on the
--   divergence it could leave behind.
--
-- Idempotency:
--   Application is idempotent by construction rather than by convention. Each
--   operation is expressed so that applying it twice reaches the same state --
--   provisioning tolerates an existing account, withdrawal tolerates an absent
--   one, and a projection update is an assignment -- and the terminal status
--   transition is conditional on the row still being pending.
-- =============================================================================

CREATE TABLE auth.identity_sync_task (

    -- WHY : Assumptions: a generated surrogate key rather than the user
    --   identifier, because one user legitimately accumulates several tasks over
    --   its lifetime -- provisioned, renamed, promoted, withdrawn -- and the
    --   ledger has to keep them in the order they were intended. The identifier
    --   is also the fair-selection order the applier drains in.
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- WHY : Assumptions: CHAR(8) and not VARCHAR, matching auth.users.user_id
    --   exactly, so a comparison between the two needs no implicit cast. No
    --   foreign key is declared, and that is deliberate: a WITHDRAW task
    --   outlives the row it refers to by design, so a reference constraint would
    --   either forbid the delete or cascade away the record of what still has to
    --   be undone.
    user_id CHAR(8) NOT NULL,

    -- WHY : Assumptions: the three operations are the complete set, because the
    --   provider surface this context uses has exactly three verbs -- create an
    --   account and return its subject, assign or reassign its group and
    --   projection, and remove it. The CHECK is what keeps a fourth from being
    --   inserted by a caller that the applier's exhaustive switch could not act
    --   on.
    operation VARCHAR(12) NOT NULL
        CONSTRAINT ck_identity_sync_task_operation
        CHECK (operation IN ('PROVISION', 'SYNCHRONISE', 'WITHDRAW')),

    -- WHY : Assumptions: the projection the provider is to hold is carried on the
    --   task rather than re-read from auth.users when the task is applied. Two
    --   reasons, and the second is the load-bearing one: a WITHDRAW task's row is
    --   gone by then, and a SYNCHRONISE task applied after a later change would
    --   otherwise push the LATER values under the EARLIER task's identity, which
    --   silently reorders two intentions.
    first_name VARCHAR(20),
    last_name VARCHAR(20),

    -- WHY : Assumptions: both the previous and the intended user type are
    --   carried, because a group reassignment is a pair of provider operations --
    --   leave the old group, join the new -- and the applier cannot derive the
    --   old one after the row has already been written with the new.
    previous_user_type CHAR(1)
        CONSTRAINT ck_identity_sync_task_previous_user_type
        CHECK (previous_user_type IS NULL OR previous_user_type IN ('A', 'U')),
    user_type CHAR(1)
        CONSTRAINT ck_identity_sync_task_user_type
        CHECK (user_type IS NULL OR user_type IN ('A', 'U')),

    -- WHY : Assumptions: three statuses and no more. PENDING is the only state an
    --   applier acts on, APPLIED is terminal and successful, and ABANDONED is
    --   terminal and unsuccessful -- reached only after the attempt ceiling, so
    --   that a task whose provider call can never succeed stops consuming every
    --   pass and stops hiding the tasks behind it.
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING'
        CONSTRAINT ck_identity_sync_task_status
        CHECK (status IN ('PENDING', 'APPLIED', 'ABANDONED')),

    -- WHY : Assumptions: attempts is INTEGER and not SMALLINT. A two-byte counter
    --   on a row that is retried by a scheduled pass reaches its ceiling in a
    --   finite time and then wraps negative, which turns an attempt ceiling into
    --   an unbounded retry; four bytes cannot be exhausted by any real rate.
    attempts INTEGER NOT NULL DEFAULT 0
        CONSTRAINT ck_identity_sync_task_attempts CHECK (attempts >= 0),

    -- WHY : Assumptions: microsecond precision, matching the 26-character
    --   timestamp form the migration carries everywhere else, so a task can be
    --   lined up against an application log line without either being rounded.
    created_at TIMESTAMP(6) NOT NULL,
    settled_at TIMESTAMP(6),

    -- WHY : Assumptions: a STABLE CODE and never a provider message. A provider
    --   fault message can carry an account identifier or a request identifier,
    --   and this column is read by operators and dumped into support tickets; a
    --   class-name-derived code identifies the fault kind without carrying a
    --   value.
    last_failure_code VARCHAR(64),

    CONSTRAINT pk_identity_sync_task PRIMARY KEY (task_id)
);

-- WHY : Assumptions: the index is PARTIAL, covering only pending rows. The
--   applier's only query is "the oldest pending tasks", and a complete index
--   would grow with every task ever applied while answering a question that
--   concerns a set which stays small in a healthy deployment. The index also
--   carries user_id so the per-user drain the write paths perform after their
--   own commit is served without touching the table.
CREATE INDEX idx_identity_sync_task_pending
    ON auth.identity_sync_task (task_id, user_id)
    WHERE status = 'PENDING';

COMMENT ON TABLE auth.identity_sync_task IS
    'Durable intended-change ledger: one row per change owed to the managed user '
    'pool, written in the same transaction as the auth.users change that caused '
    'it and applied after that transaction commits.';

COMMENT ON COLUMN auth.identity_sync_task.operation IS
    'PROVISION, SYNCHRONISE or WITHDRAW -- the three provider verbs this context uses.';

COMMENT ON COLUMN auth.identity_sync_task.status IS
    'PENDING while the change is still owed; APPLIED once the provider confirmed '
    'it; ABANDONED once the attempt ceiling was reached, which is the state an '
    'operator reconciles by hand.';
