package com.carddemo.common.config;

import java.util.regex.Pattern;

/**
 * A configured schema-owner role name, validated against a strict allow-list and rendered once as the
 * {@code SET ROLE} statement that assumes it.
 *
 * <h2>Purpose</h2>
 *
 * <p>Two collaborators need the same role name in the same two forms: the raw identifier, for
 * diagnostics, and a quoted {@code SET ROLE} statement, to issue against a connection. This type
 * holds the validation and the quoting so that both reach the server through one allow-list, and so
 * that no code path can obtain the statement without having passed the check.
 *
 * <h2>Why the configured value is validated rather than interpolated</h2>
 *
 * <p>Assumptions: the role name arrives from configuration, and {@code SET ROLE} takes an identifier
 * rather than a bind parameter, so there is no prepared-statement form of the statement to hide
 * behind. An unvalidated value would therefore be concatenated into a privileged statement -- an
 * injection seam a deployment could reach by editing one property. Two independent controls apply: the
 * value must match {@link #ROLE_NAME} in full, an allow-list admitting only lower-case letters, digits
 * and underscores after a leading letter; and it is then quoted as an identifier with any embedded
 * quote doubled. The quoting is redundant given the allow-list and is kept deliberately, so that a
 * later widening of the pattern cannot silently turn into an injection.
 *
 * <p>Trade-offs: the allow-list rejects role names PostgreSQL itself would accept -- mixed case,
 * spaces, dollar signs and names longer than 63 bytes among them. That is accepted because every role
 * this project defines is lower-case snake case, generated by
 * {@code data-migration/sql/V0__schemas_and_roles.sql} from the context name, and a deployment
 * needing another shape is better served by a reviewed change to this pattern than by a value that
 * reaches the server unchecked.
 *
 * <h2>Why this is a type rather than two static helpers</h2>
 *
 * <p>Refactoring Rationale: the pattern, the quoting and the diagnostic all lived inside
 * {@link FlywayOwnerRoleCallback} while that callback was the only consumer. A second consumer --
 * {@link FlywayOwnerRoleDataSourceCustomizer}, which has to assume the role before Flyway wraps a
 * connection -- would have had to restate them, and a security allow-list restated in two classes is
 * one that drifts. Extracting a value type rather than a pair of static methods is what makes the
 * validated state unforgeable: an instance exists only if the check passed, so
 * {@link #setRoleStatement()} cannot return an unchecked identifier.
 *
 * <p>Alternatives Considered: a Java {@code record} over the two strings. Rejected because a record's
 * canonical constructor is public and its components are settable from any value, so a caller could
 * construct one whose statement had never been validated -- which is precisely the state this type
 * exists to make unreachable.
 *
 * @see FlywayOwnerRoleCallback
 * @see FlywayOwnerRoleDataSourceCustomizer
 */
final class MigrationOwnerRole {

    /**
     * The full-match allow-list a configured role name has to satisfy: a lower-case letter followed by
     * up to sixty-two further lower-case letters, digits or underscores.
     *
     * <p>Assumptions: sixty-three characters is PostgreSQL's identifier limit at the default
     * {@code NAMEDATALEN}, so a longer value would be silently truncated by the server. Rejecting it
     * here means a deployment learns its role name is too long rather than discovering that its
     * objects are owned by a role whose name is a prefix of the one it configured.
     */
    private static final Pattern ROLE_NAME = Pattern.compile("[a-z][a-z0-9_]{0,62}");

    /**
     * A shared instance representing a configured value that was absent or blank, and therefore an
     * explicit opt-out from the ownership split.
     *
     * <p>Assumptions: the inert case is a single immutable value with no name and no statement, so
     * every consumer can test it the same way rather than each deciding what a blank value means.
     */
    private static final MigrationOwnerRole INERT = new MigrationOwnerRole(null, null);

    /** The validated role name, or {@code null} when this value is inert. */
    private final String name;

    /** The statement that assumes {@link #name}, or {@code null} when this value is inert. */
    private final String setRoleStatement;

    /**
     * Stores an already-validated pair, or the inert pair.
     *
     * @param validatedName the validated role name, or {@code null} for the inert value
     * @param renderedStatement the rendered statement, or {@code null} for the inert value
     */
    private MigrationOwnerRole(String validatedName, String renderedStatement) {
        this.name = validatedName;
        this.setRoleStatement = renderedStatement;
    }

    /**
     * Validates a configured value and renders the statement that assumes it.
     *
     * <p>Assumptions: a blank value is an explicit opt-out rather than a mistake, and it is what a
     * profile uses when it deliberately runs no ownership split -- the authorization context's test
     * profile is the one such case, where the role belongs to a bootstrap no throwaway container has
     * run. Surrounding whitespace is trimmed before the check, because a YAML value carrying a
     * trailing space is a formatting artefact rather than a different role.
     *
     * <p>Alternatives Considered: rejecting blank as invalid and expressing the opt-out by removing
     * the property in the overriding profile. Rejected because a YAML overlay can override a value but
     * cannot unset a key its base document declares, so with that rule the one profile that needs to
     * opt out could not.
     *
     * @param configuredValue the value read from configuration; may be {@code null} or blank, either
     *     of which yields the inert value
     * @param propertyName the configuration key the value came from, named in the diagnostic so a
     *     reader is told which key to edit rather than which class rejected it
     * @return a validated value, never {@code null}; inert when {@code configuredValue} was blank
     * @throws IllegalArgumentException if a non-blank value does not match {@link #ROLE_NAME} in full,
     *     which fails the application context at assembly rather than letting an unchecked identifier
     *     reach a privileged statement
     */
    static MigrationOwnerRole of(String configuredValue, String propertyName) {
        String trimmed = configuredValue == null ? "" : configuredValue.trim();
        if (trimmed.isEmpty()) {
            return INERT;
        }
        if (!ROLE_NAME.matcher(trimmed).matches()) {
            throw new IllegalArgumentException(
                    propertyName + " must be a lower-case identifier of at most 63 characters"
                            + " matching " + ROLE_NAME.pattern() + ", because it is interpolated into"
                            + " a SET ROLE statement rather than bound as a parameter; the configured"
                            + " value was '" + trimmed + "'");
        }
        return new MigrationOwnerRole(trimmed, "SET ROLE \"" + trimmed.replace("\"", "\"\"") + "\"");
    }

    /**
     * Reports whether the configured value opted out of the ownership split.
     *
     * @return {@code true} when no role is configured and nothing should be assumed
     */
    boolean isInert() {
        return name == null;
    }

    /**
     * Returns the validated role name.
     *
     * @return the role name, or {@code null} when this value is inert
     */
    String name() {
        return name;
    }

    /**
     * Returns the statement that assumes the role, with the name quoted as an identifier.
     *
     * @return the {@code SET ROLE} statement, or {@code null} when this value is inert
     */
    String setRoleStatement() {
        return setRoleStatement;
    }
}
